// Один evidence-only initial load; не повтор полной LAB приёмки или scientific run.
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { once } from "node:events";
import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { createServer } from "node:http";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), ".."), output = join(root, "target/qa/lab-transport-diagnostic");
const scriptPath = "scripts/check_lab_transport_diagnostic.mjs", manifestPath = "scripts/lab-transport-diagnostic-assets.json";
const candidate = "1be0d0940ef75aa00d6152e5b718df0cc5fb446f", candidateTree = "64bdb5f4794f48907f99886c540f6391571b1914";
const filenames = ["lab.html", "lab.js", "lab.css", "lab-data.mjs", "data/lab-2/descriptor.json", "data/lab-2/results.json", "data/lab-2/comparisons.json", "data/lab-2/manifest.json"];
const initialSearch = "?condition=baseline&seed=1&sample=0", limits = { run: 150_000, operation: 15_000, cdp: 5000, launch: 20_000, cleanup: 5000, requests: 32, events: 4096, activeCallbacks: 32 };
const sha = (b) => createHash("sha256").update(b).digest("hex"), git = (...args) => execFileSync("git", args, { cwd: root, encoding: "utf8" }).trim();
const sleep = (ms) => new Promise((done) => setTimeout(done, ms));
const report = { status: "DIAGNOSTIC_NOT_RUN", scope: "Single initial page transport diagnostic ONLY; does not replace nine LAB gates, exact-head full CI or scientific validation; original 1be failure remains FAIL.", startedAt: new Date().toISOString(), limits, sources: [], serverRequests: [], network: [], fetch: [], requestFailures: [], pageErrors: [], runtimeExceptions: [], consoleErrors: [], nodeUnhandled: [], callbackErrors: [], cleanupErrors: [], guard: { status: "NOT_RUN", blocked: [] }, sandbox: { status: "NOT_RUN" }, screenshot: { status: "NOT_RUN" }, qualifications: ["Exactly eight original pinned candidate1be assets. Current diagnostic HEAD/tree/script are separate from product candidate HEAD/tree and historical scientific producer.", "One CDP Fetch owner; no Playwright routes, positive fulfillment, takeResponseBodyAsStream, second fetch, native fetch/read Promise observer, model execution or synthetic model response.", "Fetch.getResponseBody pauses an original response, records body bytes/SHA, then continueResponse has only requestId. This observation can change timing; uninstrumented transport behavior and full LAB acceptance are unasserted.", "Node server write/finish and CDP response-body observations are separate. Driver loadingFinished/failed timelines and encoded lengths are retained; no generic cancellation exception.", "No achieved FPS, hardware backend, native touch, full accessibility or kernel isolation attestation. Trace is not requested: bounded CDP timelines/body digests and one actual PNG form this diagnostic."] };
let manifest, browser, context, page, session, server, origin, stopped = false, running, actionsPassed = false, pageClosed = false, eventCount = 0;
const assets = new Map(), networks = new Map(), fetchByNetwork = new Map(), paused = new Map(), actions = new Set();
const readerProof = report.readerLifecycle = { case: "unchanged-source-false-condition-logpoints", status: "NOT_RUN", scripts: [], breakpoints: [], pauses: [], events: [], errors: [], clocks: [], order: [] };
const clockPrecisionAllowanceSeconds = .001;
report.qualifications.push("This separate case adds four native CDP conditional breakpoints returning false on the exact original lab-data.mjs. Only primitive locals are copied; fetch/Response/Reader/Promise objects and their methods remain untouched. Debugger observation can affect timing and liveness; no cancellation cause, GC explanation or product fix is inferred.", "Reader JS clocks and native Network clocks are recorded separately. Timestamp sandwiches bound a possible offset interval; overlapping event intervals give UNKNOWN order, and Node callback arrival is never used as browser event time.");
function fail(error, stage) { stopped = true; report.status = "DIAGNOSTIC_FAIL"; process.exitCode = 1; (report.failures ||= []).push({ stage, error: error?.stack || String(error) }); }
process.on("unhandledRejection", (e) => { report.nodeUnhandled.push(e?.stack || String(e)); fail(e, "Node unhandled rejection"); });
async function bounded(promise, ms, label) { let timer; try { return await Promise.race([promise, new Promise((_, reject) => { timer = setTimeout(() => reject(new Error(`Timed out: ${label}`)), ms); })]); } finally { clearTimeout(timer); } }
function keys(value, names) { assert.ok(value && typeof value === "object" && !Array.isArray(value)); assert.deepEqual(Object.keys(value).sort(), [...names].sort()); }
async function prepare() {
  manifest = JSON.parse(await readFile(join(root, manifestPath))); keys(manifest, ["schema_version", "scope", "candidate_head", "candidate_tree", "reader_logpoints", "assets"]); assert.equal(manifest.schema_version, 1); assert.equal(manifest.scope, "single_initial_page_transport_diagnostic_only"); assert.equal(manifest.candidate_head, candidate); assert.equal(manifest.candidate_tree, candidateTree); assert.equal(git("rev-parse", `${candidate}^{tree}`), candidateTree);
  assert.ok(Array.isArray(manifest.assets)); assert.deepEqual(manifest.assets.map((a) => a.filename), filenames); let total = 0;
  for (const asset of manifest.assets) { keys(asset, ["filename", "bytes", "sha256"]); assert.ok(Number.isSafeInteger(asset.bytes) && asset.bytes > 0 && typeof asset.sha256 === "string" && /^[a-f0-9]{64}$/.test(asset.sha256)); total += asset.bytes; assert.ok(total <= 8 * 1024 * 1024); const filename = `site/${asset.filename}`, bytes = await readFile(join(root, filename)); assert.equal(bytes.length, asset.bytes); assert.equal(sha(bytes), asset.sha256); for (const head of [candidate, "HEAD"]) assert.deepEqual(bytes, execFileSync("git", ["show", `${head}:${filename}`], { cwd: root, maxBuffer: 8 * 1024 * 1024 })); assets.set(`/${asset.filename}`, { ...asset, bytesBuffer: bytes, mime: asset.filename.endsWith(".json") ? "application/json" : asset.filename.endsWith(".css") ? "text/css" : asset.filename.endsWith(".html") ? "text/html" : "text/javascript" }); report.sources.push(asset); }
  report.candidateHead = candidate; report.candidateTree = candidateTree; report.candidateTotalBytes = total; report.diagnosticHead = git("rev-parse", "HEAD"); report.diagnosticTree = git("rev-parse", "HEAD^{tree}"); report.scriptSha256 = sha(await readFile(join(root, scriptPath))); report.manifestSha256 = sha(await readFile(join(root, manifestPath)));
  const config = manifest.reader_logpoints; keys(config, ["filename", "sha256", "max_events", "anchors"]); assert.equal(config.filename, "lab-data.mjs"); assert.equal(config.sha256, "b0341865222c0692a86daf73b8611205aa99d27e54f96968c8a31851a0c2353a"); assert.equal(config.sha256, assets.get("/lab-data.mjs").sha256); assert.equal(config.max_events, 32); assert.ok(Array.isArray(config.anchors)); assert.deepEqual(config.anchors.map((a) => [a.phase, a.line, a.column, a.max_column]), [["entry", 131, 2, 25], ["finally", 139, 4, 24], ["pre_release", 142, 10, 23], ["post_release", 144, 4, 41]]);
  const lines = assets.get("/lab-data.mjs").bytesBuffer.toString("utf8").split("\n"); for (const anchor of config.anchors) { keys(anchor, ["phase", "line", "column", "max_column", "source_line"]); assert.equal(anchor.source_line, lines[anchor.line - 1]); } readerProof.config = config;
}
// Не сохраняем произвольные query/userinfo внешних URL. Allowed URL здесь literal loopback.
function location(url) { try { const u = new URL(url); return { origin: u.origin, path: assets.has(u.pathname) ? u.pathname : "UNAPPROVED_PATH", initialQuery: u.pathname === "/lab.html" && u.search === initialSearch }; } catch { return { invalid: true }; } }
function admitted(url, method) { const u = new URL(url); return method === "GET" && u.origin === origin && !u.username && !u.password && !u.hash && assets.has(u.pathname) && u.search === (u.pathname === "/lab.html" ? initialSearch : ""); }
function timeline(id, event, fields) { assert.ok(typeof id === "string" && id.length <= 128); assert.ok(++eventCount <= limits.events, "Bounded CDP event inventory"); let entry = networks.get(id); if (!entry) { assert.ok(networks.size < limits.requests); entry = { requestId: id, events: [] }; networks.set(id, entry); report.network.push(entry); } entry.events.push({ event, observedMonotonicMs: performance.now(), ...fields }); return entry; }
function ownedEvent(name, handler) { session.on(name, (event) => { try { handler(event); } catch (e) { report.callbackErrors.push({ event: name, error: e.stack || String(e) }); fail(e, name); } }); }
function ownedAction(name, operation) { assert.ok(actions.size < limits.activeCallbacks); const action = operation().catch((e) => { report.callbackErrors.push({ event: name, error: e.stack || String(e) }); fail(e, name); }).finally(() => actions.delete(action)); actions.add(action); }
function logCondition(phase) {
  const entry = phase === "entry", after = phase === "post_release";
  // Entry не обращается даже через typeof к ещё не инициализированным const/let.
  const fields = `completed:${entry ? "null" : "completed"},primaryFailed:${entry ? "null" : "primaryFailed"},length:${entry ? "null" : "length"},cleanupFailed:${after ? "cleanupFailed" : "null"},bodyUsed:${entry ? "null" : "response.bodyUsed"},locked:${entry ? "null" : "response.body.locked"}`;
  return `(()=>{const proof=globalThis.__labReaderLifecycleProof;try{if(!proof)return false;if(proof.events.length>=32){proof.overflow=true;return false;}proof.events.push({seq:++proof.sequence,phase:${JSON.stringify(phase)},path:url.pathname,limit,now:performance.now(),timeOrigin:performance.timeOrigin,${fields}});}catch(error){if(proof){if(proof.errors.length<32)proof.errors.push({phase:${JSON.stringify(phase)},error:String(error?.message||error).slice(0,256)});else proof.overflow=true;}}return false;})()`;
}
async function observeScript(event) {
  assert.equal(readerProof.scripts.length, 0, "Exactly one compiled original lab-data module"); const script = { scriptId: event.scriptId, url: event.url, engineHash: event.hash, startLine: event.startLine, startColumn: event.startColumn }; readerProof.scripts.push(script); assert.equal(event.startLine, 0); assert.equal(event.startColumn, 0);
  const source = await bounded(session.send("Debugger.getScriptSource", { scriptId: event.scriptId }), limits.cdp, "compiled original source"); assert.equal(typeof source.scriptSource, "string"); script.sha256 = sha(Buffer.from(source.scriptSource, "utf8")); assert.equal(script.sha256, manifest.reader_logpoints.sha256); assert.deepEqual(Buffer.from(source.scriptSource, "utf8"), assets.get("/lab-data.mjs").bytesBuffer);
  for (const anchor of manifest.reader_logpoints.anchors) { const possible = await bounded(session.send("Debugger.getPossibleBreakpoints", { start: { scriptId: event.scriptId, lineNumber: anchor.line - 1, columnNumber: anchor.column }, end: { scriptId: event.scriptId, lineNumber: anchor.line, columnNumber: 0 }, restrictToFunction: true }), limits.cdp, "exact source-anchor locations"); assert.ok(Array.isArray(possible.locations) && possible.locations.length > 0 && possible.locations.length <= 32); const candidates = possible.locations.filter((p) => p.scriptId === event.scriptId && p.lineNumber === anchor.line - 1 && p.columnNumber >= anchor.column && p.columnNumber <= anchor.max_column).sort((a, b) => a.columnNumber - b.columnNumber); assert.ok(candidates.length, `No breakpoint boundary within ${anchor.phase}`); const bp = readerProof.breakpoints.find((b) => b.phase === anchor.phase); bp.possible = possible.locations; bp.expectedLocation = candidates[0]; }
}
async function armReaderProof() {
  readerProof.status = "ARMING"; readerProof.url = origin + "/lab-data.mjs";
  ownedEvent("Debugger.breakpointResolved", (event) => { const bp = readerProof.breakpoints.find((b) => b.breakpointId === event.breakpointId); assert.ok(bp, "Known conditional breakpoint"); assert.equal(bp.resolved.length, 0); bp.resolved.push(event.location); });
  ownedEvent("Debugger.paused", (event) => { readerProof.pauses.push({ reason: event.reason, hits: event.hitBreakpoints || [], observedMonotonicMs: performance.now() }); fail(new Error("Unexpected actual debugger pause"), "Debugger pause"); ownedAction("resume unexpected pause", () => bounded(session.send("Debugger.resume"), limits.cdp, "resume after diagnostic failure")); });
  ownedEvent("Debugger.scriptParsed", (event) => { if (event.url === readerProof.url) ownedAction("compiled source and breakpoint boundaries", () => observeScript(event)); });
  await bounded(session.send("Debugger.enable", { maxScriptsCacheSize: 1024 * 1024 }), limits.cdp, "Debugger enable"); await bounded(session.send("Debugger.setPauseOnExceptions", { state: "none" }), limits.cdp, "no exception pauses"); await bounded(session.send("Performance.enable", { timeDomain: "timeTicks" }), limits.cdp, "monotonic metrics enable");
  for (const anchor of manifest.reader_logpoints.anchors) { const bp = { phase: anchor.phase, requestedLocation: { lineNumber: anchor.line - 1, columnNumber: anchor.column }, resolved: [], conditionSha256: sha(Buffer.from(logCondition(anchor.phase))) }; readerProof.breakpoints.push(bp); const result = await bounded(session.send("Debugger.setBreakpointByUrl", { url: readerProof.url, ...bp.requestedLocation, condition: logCondition(anchor.phase) }), limits.cdp, "arm false source logpoint"); assert.equal(typeof result.breakpointId, "string"); bp.breakpointId = result.breakpointId; assert.ok(Array.isArray(result.locations) && result.locations.length === 0, "Arm before the original module is compiled"); }
  readerProof.status = "ARMED";
}
async function clockSample(label) {
  const stamp = async () => { const r = await bounded(session.send("Performance.getMetrics"), limits.cdp, "monotonic Timestamp"); const values = r.metrics.filter((m) => m.name === "Timestamp"); assert.equal(values.length, 1); assert.ok(Number.isFinite(values[0].value)); return values[0].value; };
  const before = await stamp(), value = await bounded(session.send("Runtime.evaluate", { expression: "({now:performance.now(),timeOrigin:performance.timeOrigin,url:location.href})", returnByValue: true, awaitPromise: false }), limits.cdp, "actual document clock"), after = await stamp(); assert.equal(value.exceptionDetails, undefined); const js = value.result.value; assert.equal(js.url, origin + "/lab.html" + initialSearch); assert.ok(Number.isFinite(js.now) && Number.isFinite(js.timeOrigin) && before <= after); const sample = { label, beforeTimestamp: before, afterTimestamp: after, now: js.now, timeOrigin: js.timeOrigin, precisionAllowanceSeconds: clockPrecisionAllowanceSeconds, offsetSeconds: [before - js.now / 1000 - clockPrecisionAllowanceSeconds, after - js.now / 1000 + clockPrecisionAllowanceSeconds], qualification: "Timestamp/timeTicks alignment and a conservative 1ms allowance for this Chrome document's coarsened JS clock are assumptions; this is not an exact offset or universal precision bound." }; readerProof.clocks.push(sample); return sample;
}
async function collectReaderProof(label) {
  const value = await bounded(session.send("Runtime.evaluate", { expression: "globalThis.__labReaderLifecycleProof", returnByValue: true, awaitPromise: false }), limits.cdp, "primitive reader log observation"); assert.equal(value.exceptionDetails, undefined); const state = value.result.value; assert.ok(state && Array.isArray(state.events) && state.events.length <= 32 && Array.isArray(state.errors) && state.errors.length <= 32); assert.deepEqual(state.events.slice(0, readerProof.events.length), readerProof.events, "Raw reader logs cannot disappear"); readerProof.events = state.events; readerProof.errors = state.errors; readerProof.overflow = state.overflow; readerProof.sequence = state.sequence; (readerProof.observations ||= []).push({ label, count: state.events.length, observedMonotonicMs: performance.now() });
}
function verifyReaderProof() {
  assert.equal(readerProof.scripts.length, 1); assert.equal(readerProof.scripts[0].sha256, manifest.reader_logpoints.sha256); assert.deepEqual(readerProof.pauses, []); assert.deepEqual(readerProof.errors, []); assert.equal(readerProof.overflow, false); assert.equal(readerProof.sequence, 16); assert.equal(readerProof.events.length, 16); assert.equal(readerProof.breakpoints.length, 4); const coordinates = new Set();
  for (const bp of readerProof.breakpoints) { assert.equal(bp.resolved.length, 1); const actual = bp.resolved[0], expected = bp.expectedLocation; assert.ok(expected); assert.deepEqual(actual, { scriptId: expected.scriptId, lineNumber: expected.lineNumber, columnNumber: expected.columnNumber }); assert.equal(actual.scriptId, readerProof.scripts[0].scriptId); const key = `${actual.scriptId}:${actual.lineNumber}:${actual.columnNumber}`; assert.ok(!coordinates.has(key)); coordinates.add(key); }
  const clocks = readerProof.clocks; assert.ok(clocks.length >= 2 && clocks.length <= 3); const timeOrigin = clocks[0].timeOrigin; assert.ok(clocks.every((c) => c.timeOrigin === timeOrigin)); const intersection = [Math.max(...clocks.map((c) => c.offsetSeconds[0])), Math.min(...clocks.map((c) => c.offsetSeconds[1]))], offset = intersection[0] <= intersection[1] ? intersection : null; readerProof.offsetIntervalSeconds = offset; readerProof.clockConsistency = offset ? "CONSISTENT_WITH_DECLARED_CLOCK_ASSUMPTIONS" : "INCONSISTENT_OFFSETS_CROSS_CLOCK_ORDER_UNKNOWN";
  const paths = filenames.filter((f) => f.endsWith(".json")), order = []; for (const [index, e] of readerProof.events.entries()) { keys(e, ["seq", "phase", "path", "limit", "now", "timeOrigin", "completed", "primaryFailed", "length", "cleanupFailed", "bodyUsed", "locked"]); assert.equal(e.seq, index + 1); assert.ok(typeof e.path === "string" && paths.includes(e.path.slice(1)) && e.path[0] === "/"); assert.ok(Number.isFinite(e.now) && e.now >= 0 && e.timeOrigin === timeOrigin); assert.ok(Object.values(e).every((v) => v === null || ["number", "string", "boolean"].includes(typeof v))); }
  for (const filename of paths) { const events = readerProof.events.filter((e) => e.path === `/${filename}`), bytes = assets.get(`/${filename}`).bytes; assert.deepEqual(events.map((e) => e.phase), ["entry", "finally", "pre_release", "post_release"]); assert.ok(events.every((e) => e.limit === (filename.endsWith("descriptor.json") ? 256 * 1024 : bytes))); for (let i = 1; i < 4; i++) { assert.ok(events[i].now >= events[i - 1].now); assert.equal(events[i].completed, true); assert.equal(events[i].primaryFailed, false); assert.equal(events[i].length, bytes); assert.equal(events[i].bodyUsed, true); assert.equal(events[i].locked, i !== 3); assert.equal(events[i].cleanupFailed, i === 3 ? false : null); } for (const key of ["completed", "primaryFailed", "length", "cleanupFailed", "bodyUsed", "locked"]) assert.equal(events[0][key], null);
    const network = report.network.find((n) => n.filename === filename), failed = network?.events.find((e) => e.event === "loadingFailed"); if (failed) for (const event of events.slice(1)) { const interval = offset ? [event.now / 1000 + offset[0] - clockPrecisionAllowanceSeconds, event.now / 1000 + offset[1] + clockPrecisionAllowanceSeconds] : null; order.push({ filename, phase: event.phase, jsEventChromeIntervalSeconds: interval, nativeFailureTimestamp: failed.timestamp, relation: !interval ? "UNKNOWN_INCONSISTENT_CLOCK_INTERVALS" : interval[1] < failed.timestamp ? "JS_PHASE_BEFORE_NATIVE_FAILURE" : interval[0] > failed.timestamp ? "NATIVE_FAILURE_BEFORE_JS_PHASE" : "UNKNOWN_OVERLAPPING_INTERVALS", qualification: "Conditional on protocol clock alignment and declared precision allowance; ordering is not a cancellation-cause proof." }); }
  } readerProof.order = order; readerProof.status = "PRIMITIVE_SOURCE_PATH_OBSERVED";
}
async function startServer() {
  server = createServer((request, response) => { const url = new URL(request.url, "http://127.0.0.1"), asset = assets.get(url.pathname), entry = { id: report.serverRequests.length + 1, method: request.method, path: asset ? url.pathname : "UNAPPROVED_PATH", receivedUnixMs: Date.now() }; report.serverRequests.push(entry); if (report.serverRequests.length > limits.requests) fail(new Error("Server request inventory overflow"), "server"); response.once("finish", () => { entry.finishedUnixMs = Date.now(); }); response.once("close", () => { entry.closedUnixMs = Date.now(); entry.closedAfterFinish = response.writableFinished; }); request.once("aborted", () => { entry.abortedUnixMs = Date.now(); });
    if (request.method !== "GET" || !asset) { entry.status = 404; response.writeHead(404); response.end("Unknown diagnostic route"); return; } entry.status = 200; entry.bytes = asset.bytes; entry.sha256 = asset.sha256; response.writeHead(200, { "content-type": asset.mime, "content-length": asset.bytes, "cache-control": "no-store" }); response.end(asset.bytesBuffer);
  }); server.listen(0, "127.0.0.1"); await bounded(once(server, "listening"), limits.cdp, "loopback listen"); origin = `http://127.0.0.1:${server.address().port}`; report.origin = origin;
}
async function pausedRequest(event) {
  assert.ok(actions.size <= limits.activeCallbacks); assert.ok(typeof event.networkId === "string", "Every paused hop must map to a native Network request ID"); const url = new URL(event.request.url), asset = assets.get(url.pathname), responseStage = event.responseStatusCode !== undefined || event.responseErrorReason !== undefined;
  if (!responseStage) {
    assert.ok(!fetchByNetwork.has(event.networkId), "One Request-stage pause per original network ID; redirects/retries are not admitted");
    const entry = { networkId: event.networkId, requestFetchId: event.requestId, method: event.request.method, location: location(event.request.url), requestPausedMs: performance.now(), status: "REQUEST_PAUSED" }; assert.ok(report.fetch.length < limits.requests); fetchByNetwork.set(event.networkId, entry); report.fetch.push(entry); paused.set(event.requestId, "Request");
    if (!admitted(event.request.url, event.request.method)) { report.guard.blocked.push(entry); fail(new Error("Out-of-scope request refused BEFORE transmission"), "Request-stage guard"); await bounded(session.send("Fetch.failRequest", { requestId: event.requestId, errorReason: "BlockedByClient" }), limits.cdp, "out-of-scope block"); paused.delete(event.requestId); entry.status = "BLOCKED"; return; }
    entry.filename = asset.filename; await bounded(session.send("Fetch.continueRequest", { requestId: event.requestId }), limits.cdp, "unchanged Request-stage continuation"); paused.delete(event.requestId); entry.requestContinuedMs = performance.now(); entry.status = "REQUEST_CONTINUED"; return;
  }
  const entry = fetchByNetwork.get(event.networkId); assert.ok(entry && admitted(event.request.url, event.request.method)); assert.equal(entry.filename, asset.filename); assert.equal(entry.responseFetchId, undefined); entry.responseFetchId = event.requestId; entry.responsePausedMs = performance.now(); entry.httpStatus = event.responseStatusCode; entry.responseErrorReason = event.responseErrorReason || null; paused.set(event.requestId, "Response");
  try {
    assert.equal(event.responseErrorReason, undefined); assert.equal(event.responseStatusCode, 200); assert.ok(Array.isArray(event.responseHeaders) && event.responseHeaders.length <= 32); const headers = event.responseHeaders.filter((h) => ["content-length", "content-type", "content-encoding"].includes(h.name.toLowerCase())); assert.ok(headers.every((h) => typeof h.value === "string" && h.value.length <= 256)); entry.headers = headers;
    const length = headers.filter((h) => h.name.toLowerCase() === "content-length"), encoding = headers.filter((h) => h.name.toLowerCase() === "content-encoding"); assert.equal(length.length, 1); assert.equal(length[0].value, String(asset.bytes)); assert.equal(encoding.length, 0);
    entry.getBodyStartedMs = performance.now(); const body = await bounded(session.send("Fetch.getResponseBody", { requestId: event.requestId }), limits.operation, "original response-stage body"); entry.getBodyCompletedMs = performance.now(); assert.equal(typeof body.body, "string"); assert.equal(typeof body.base64Encoded, "boolean"); const bytes = Buffer.from(body.body, body.base64Encoded ? "base64" : "utf8"); if (body.base64Encoded) assert.equal(bytes.toString("base64"), body.body); entry.body = { bytes: bytes.length, sha256: sha(bytes), base64Encoded: body.base64Encoded }; assert.equal(bytes.length, asset.bytes); assert.equal(entry.body.sha256, asset.sha256); entry.status = "ORIGINAL_BODY_PINNED";
  } catch (e) { entry.status = "BODY_PROOF_FAILED"; entry.error = e.stack || String(e); throw e; }
  finally {
    // Даже при diagnostic FAIL освобождаем только original response, без replacement.
    await bounded(session.send("Fetch.continueResponse", { requestId: event.requestId }), limits.cdp, "original response continuation with no overrides"); paused.delete(event.requestId); entry.responseContinuedMs = performance.now(); entry.continuationArguments = ["requestId"];
  }
}
async function drain() { await bounded((async () => { while (actions.size) await Promise.all([...actions]); })(), limits.operation, "owned CDP callback drain"); }
function installObservers() {
  ownedEvent("Network.requestWillBeSent", (e) => { const entry = timeline(e.requestId, "requestWillBeSent", { timestamp: e.timestamp, wallTime: e.wallTime, method: e.request.method, location: location(e.request.url), type: e.type }); assert.equal(entry.started, undefined); assert.equal(e.redirectResponse, undefined); assert.ok(admitted(e.request.url, e.request.method)); entry.started = true; entry.filename = assets.get(new URL(e.request.url).pathname).filename; });
  ownedEvent("Network.responseReceived", (e) => { const entry = timeline(e.requestId, "responseReceived", { timestamp: e.timestamp, status: e.response.status, mimeType: e.response.mimeType, encodedDataLength: e.response.encodedDataLength, fromDiskCache: e.response.fromDiskCache, fromServiceWorker: e.response.fromServiceWorker }); assert.equal(entry.responseSeen, undefined); entry.responseSeen = true; assert.equal(e.response.status, 200); });
  ownedEvent("Network.dataReceived", (e) => { const entry = timeline(e.requestId, "dataReceived", { timestamp: e.timestamp, dataLength: e.dataLength, encodedDataLength: e.encodedDataLength }); assert.ok(Number.isFinite(e.dataLength) && e.dataLength >= 0 && Number.isFinite(e.encodedDataLength) && e.encodedDataLength >= 0); entry.decodedDataLength = (entry.decodedDataLength || 0) + e.dataLength; entry.encodedDataLength = (entry.encodedDataLength || 0) + e.encodedDataLength; });
  ownedEvent("Network.loadingFinished", (e) => { const entry = timeline(e.requestId, "loadingFinished", { timestamp: e.timestamp, encodedDataLength: e.encodedDataLength }); assert.equal(entry.terminal, undefined); entry.terminal = "loadingFinished"; });
  ownedEvent("Network.loadingFailed", (e) => { const entry = timeline(e.requestId, "loadingFailed", { timestamp: e.timestamp, errorText: e.errorText, canceled: e.canceled === true, blockedReason: e.blockedReason || null, type: e.type }); entry.terminal = "loadingFailed"; fail(new Error(`Native Network loadingFailed: ${e.errorText}`), "Network loadingFailed"); });
  ownedEvent("Runtime.exceptionThrown", (e) => { report.runtimeExceptions.push(e.exceptionDetails); fail(new Error(e.exceptionDetails.text), "Runtime exception"); });
  session.on("Fetch.requestPaused", (event) => { const action = pausedRequest(event).catch((e) => { report.callbackErrors.push({ event: "Fetch.requestPaused", networkId: event.networkId, requestId: event.requestId, error: e.stack || String(e) }); fail(e, "Fetch callback"); }).finally(() => actions.delete(action)); actions.add(action); });
  page.on("requestfailed", (request) => { const entry = { method: request.method(), location: location(request.url()), errorText: request.failure()?.errorText, observedMonotonicMs: performance.now() }; report.requestFailures.push(entry); fail(new Error(entry.errorText), "Playwright requestfailed"); });
  page.on("pageerror", (e) => { report.pageErrors.push(e.stack || String(e)); fail(e, "Page error"); }); page.on("console", (m) => { if (m.type() === "error") { report.consoleErrors.push({ text: m.text(), location: location(m.location().url), observedMonotonicMs: performance.now() }); fail(new Error(m.text()), "Console error"); } });
}
function readyUi() {
  const host = document.getElementById("plots"), workspace = document.getElementById("lab-workspace"), error = document.getElementById("lab-error"), plots = [...(host?.querySelectorAll(".metric-plot") || [])];
  return !!host && workspace?.hidden === false && error?.hidden === true && host.dataset.layout === "ready" && host.getAttribute("aria-busy") === "false" && plots.length === 4 && plots.every((svg) => getComputedStyle(svg).visibility === "visible" && svg.getBoundingClientRect().width > 96);
}
function uiState() {
  const host = document.getElementById("plots"), workspace = document.getElementById("lab-workspace"), error = document.getElementById("lab-error"), stamp = document.getElementById("sample-stamp"), plots = [...(host?.querySelectorAll(".metric-plot") || [])].map((svg) => ({ metric: svg.dataset.metric, visible: getComputedStyle(svg).visibility, width: svg.getBoundingClientRect().width, height: svg.getBoundingClientRect().height }));
  return { ready: !!host && workspace?.hidden === false && error?.hidden === true && host.dataset.layout === "ready" && host.getAttribute("aria-busy") === "false" && plots.length === 4 && plots.every((svg) => svg.visible === "visible" && svg.width > 96), workspaceHidden: workspace?.hidden, errorVisible: error?.hidden !== true, layout: host?.dataset.layout, ariaBusy: host?.getAttribute("aria-busy"), status: document.getElementById("lab-status")?.textContent, matrixRows: document.querySelectorAll("#run-matrix tbody tr").length, plots, runId: stamp?.dataset.runId, tick: stamp?.dataset.tick, unhandled: window.__labTransportUnhandled || [] };
}
function proof() {
  verifyReaderProof();
  assert.equal(actionsPassed, true); assert.equal(pageClosed, true); assert.equal(actions.size, 0); assert.equal(paused.size, 0); assert.equal(stopped, false); for (const name of ["requestFailures", "pageErrors", "runtimeExceptions", "consoleErrors", "nodeUnhandled", "callbackErrors", "cleanupErrors"]) assert.deepEqual(report[name], []); assert.deepEqual(report.guard.blocked, []); assert.equal(networks.size, 8); assert.equal(report.fetch.length, 8); assert.equal(report.serverRequests.length, 8);
  for (const asset of manifest.assets) { const network = report.network.filter((n) => n.filename === asset.filename), fetched = report.fetch.filter((f) => f.filename === asset.filename), served = report.serverRequests.filter((r) => r.path === `/${asset.filename}`); assert.equal(network.length, 1); assert.equal(fetched.length, 1); assert.equal(served.length, 1); assert.equal(network[0].started, true); assert.equal(network[0].responseSeen, true); assert.equal(network[0].terminal, "loadingFinished"); assert.equal(fetched[0].networkId, network[0].requestId); assert.equal(fetched[0].status, "ORIGINAL_BODY_PINNED"); assert.equal(fetched[0].body.bytes, asset.bytes); assert.equal(fetched[0].body.sha256, asset.sha256); assert.ok(fetched[0].responseContinuedMs >= fetched[0].getBodyCompletedMs); assert.deepEqual(fetched[0].continuationArguments, ["requestId"]); assert.equal(served[0].method, "GET"); assert.equal(served[0].status, 200); assert.ok(served[0].finishedUnixMs && served[0].closedAfterFinish); assert.equal(served[0].abortedUnixMs, undefined); }
  assert.equal(report.screenshot.status, "PASS"); for (const state of [report.ui, report.finalPage]) { assert.equal(state.ready, true); assert.equal(state.workspaceHidden, false); assert.equal(state.errorVisible, false); assert.equal(state.layout, "ready"); assert.equal(state.ariaBusy, "false"); assert.equal(state.matrixRows, 24); assert.equal(state.runId, "seed-1-baseline"); assert.equal(state.tick, "0"); assert.deepEqual(state.unhandled, []); } assert.equal(report.sandbox.status, "PASS"); report.guard.status = "PASS";
}
async function main() {
  await prepare(); assert.equal(report.diagnosticHead, process.env.LIMINIS_EXPECTED_HEAD); assert.equal(report.diagnosticTree, process.env.LIMINIS_EXPECTED_TREE); assert.equal(git("status", "--porcelain", "--untracked-files=no"), ""); for (const path of [scriptPath, manifestPath]) assert.deepEqual(await readFile(join(root, path)), execFileSync("git", ["show", `HEAD:${path}`], { cwd: root })); await startServer();
  const require = createRequire(import.meta.url), moduleId = process.env.LIMINIS_PLAYWRIGHT_MODULE; assert.ok(moduleId); const pkg = require(`${moduleId}/package.json`); assert.equal(pkg.name, "playwright"); assert.equal(pkg.version, "1.61.1"); browser = await require(moduleId).chromium.launch({ headless: true, chromiumSandbox: true, args: ["--enable-automation"], timeout: limits.launch }); report.browser = { playwright: pkg.version, version: browser.version(), node: process.version, runner: process.env.ImageOS || null, workflowRun: process.env.GITHUB_RUN_ID || null };
  const argvSession = await bounded(browser.newBrowserCDPSession(), limits.cdp, "argv CDP"); try { const { arguments: argv } = await bounded(argvSession.send("Browser.getBrowserCommandLine"), limits.cdp, "actual argv"); const forbidden = new Set(["--no-sandbox", "--no-zygote-sandbox", "--disable-setuid-sandbox", "--disable-namespace-sandbox", "--disable-seccomp-filter-sandbox", "--disable-gpu-sandbox", "--allow-sandbox-debugging", "--single-process", "--ignore-gpu-blocklist", "--disable-web-security"]); report.sandbox.arguments = argv; assert.ok(argv.length && argv.every((a) => typeof a === "string")); assert.deepEqual(argv.map((a) => a.split("=", 1)[0]).filter((a) => forbidden.has(a) || /^--disable-.*sandbox$/.test(a)), []); report.sandbox.status = "PASS"; report.sandbox.launchSettings = { headless: true, chromiumSandbox: true, args: ["--enable-automation"] }; } finally { await bounded(argvSession.detach(), limits.cdp, "argv detach"); }
  context = await bounded(browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1, acceptDownloads: false }), limits.operation, "one context"); page = await bounded(context.newPage(), limits.operation, "one page"); page.setDefaultTimeout(limits.operation); page.setDefaultNavigationTimeout(limits.operation); session = await bounded(context.newCDPSession(page), limits.cdp, "sole page Fetch owner"); installObservers();
  await page.addInitScript(() => { window.__labReaderLifecycleProof = { sequence: 0, events: [], errors: [], overflow: false }; window.__labTransportUnhandled = []; addEventListener("unhandledrejection", (e) => window.__labTransportUnhandled.push(String(e.reason?.stack || e.reason))); }); for (const [method, args] of [["Network.enable", {}], ["Network.setCacheDisabled", { cacheDisabled: true }], ["Runtime.enable", {}], ["Fetch.enable", { patterns: [{ urlPattern: "*", requestStage: "Request" }, { urlPattern: "*", requestStage: "Response" }] }]]) await bounded(session.send(method, args), limits.cdp, method); await armReaderProof(); assert.equal(stopped, false); report.guard.status = "RUNNING"; report.status = "DIAGNOSTIC_RUNNING";
  await page.goto(origin + "/lab.html" + initialSearch, { waitUntil: "domcontentloaded" }); await clockSample("actual document after DOM before UI observation"); await page.waitForFunction(readyUi);
  report.ui = await page.evaluate(uiState); assert.equal(report.ui.ready, true); assert.equal(report.ui.matrixRows, 24); assert.equal(report.ui.runId, "seed-1-baseline"); assert.equal(report.ui.tick, "0");
  await collectReaderProof("initial UI observation"); await bounded((async () => { while (networks.size !== 8 || [...networks.values()].some((n) => !n.terminal)) { assert.equal(stopped, false); await sleep(20); } })(), limits.operation, "native request terminal settlement after UI ready"); await drain(); assert.equal(stopped, false); actionsPassed = true;
}
if (process.argv.includes("--source-preflight-only")) { await prepare(); console.log(JSON.stringify({ status: "SOURCE_PREFLIGHT_PASS", scope: report.scope, candidateHead: candidate, candidateTree, diagnosticHead: report.diagnosticHead, diagnosticTree: report.diagnosticTree, scriptSha256: report.scriptSha256, manifestSha256: report.manifestSha256, assets: report.sources, totalBytes: report.candidateTotalBytes, network: "NOT_RUN", browser: "NOT_RUN" })); }
else {
  await rm(output, { recursive: true, force: true }); await mkdir(output, { recursive: true }); try { running = main(); await bounded(running, limits.run, "one diagnostic run"); } catch (e) { fail(e, "main"); if (running) await bounded(running.catch((e) => fail(e, "main settlement")), limits.operation + limits.launch, "interrupted main settlement").catch((e) => fail(e, "settlement deadline")); }
  finally {
    const cleanup = async (name, action, ms = limits.cleanup) => { try { await bounded(action(), ms, name); } catch (e) { report.cleanupErrors.push({ name, error: e.stack || String(e) }); fail(e, name); } };
    if (page && !page.isClosed()) { await cleanup("actual PNG even on diagnostic failure", async () => { const bytes = await page.screenshot({ path: join(output, "page.png"), fullPage: true, timeout: limits.cleanup }); report.screenshot = { status: "PASS", bytes: bytes.length, sha256: sha(bytes) }; }, limits.cleanup); if (actionsPassed) await cleanup("actual post-PNG ready plots", () => page.waitForFunction(readyUi, undefined, { timeout: limits.cleanup })); await cleanup("final live-page state and unhandled observation", async () => { report.finalPage = await page.evaluate(uiState); assert.deepEqual(report.finalPage.unhandled, []); if (actionsPassed) { assert.equal(report.finalPage.ready, true); assert.equal(report.finalPage.errorVisible, false); } }); await cleanup("final same-document clock and primitive logs even on FAIL", async () => { await clockSample("actual document after PNG before closure"); await collectReaderProof("final live page"); }, limits.operation); await cleanup("preclose owned callbacks", drain, limits.operation); await cleanup("independent primitive source-path verification", async () => verifyReaderProof()); await cleanup("acknowledged page closure with guard retained", async () => { await page.close(); pageClosed = true; }); }
    if (context) await cleanup("context close", () => context.close()); if (browser) await cleanup("browser close", () => browser.close()); await cleanup("postclose owned callbacks", drain, limits.operation); if (server) await cleanup("server close", () => new Promise((done, reject) => { server.close((e) => e ? reject(e) : done()); server.closeAllConnections(); })); await sleep(50);
    try { proof(); assert.equal(git("rev-parse", "HEAD"), report.diagnosticHead); assert.equal(git("rev-parse", "HEAD^{tree}"), report.diagnosticTree); assert.equal(git("status", "--porcelain", "--untracked-files=no"), ""); report.status = "DIAGNOSTIC_PASS"; } catch (e) { fail(e, "post-cleanup aggregate"); } report.finalization = { pageClosed, pendingCallbacks: actions.size, pausedRequests: paused.size, contextAndBrowserCleanupErrors: report.cleanupErrors.length, networkRequests: networks.size, timelineEvents: eventCount, actionsPassed }; report.finishedAt = new Date().toISOString(); await writeFile(join(output, "report.json"), JSON.stringify(report, null, 2) + "\n"); console.log(JSON.stringify({ status: report.status, candidateHead: candidate, diagnosticHead: report.diagnosticHead, output })); if (report.status !== "DIAGNOSTIC_PASS") process.exitCode = 1;
  }
}
