// LIVE-3b source, not browser-run evidence. Existing protected Playwright only.
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { spawn, execFileSync } from "node:child_process";
import { once } from "node:events";
import { createServer } from "node:net";
import { mkdir, mkdtemp, readFile, writeFile, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { createRequire } from "node:module";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
import { inflateSync } from "node:zlib";

const root = resolve(dirname(fileURLToPath(import.meta.url)), ".."), output = join(root, "target/qa/physical-3d-browser"), binary = join(root, "target/release/liminis"), config = join(root, "configs/scenarios/cell-chamber-physical.toml");
const sha = (value) => createHash("sha256").update(value).digest("hex"), sleep = (ms) => new Promise((done) => setTimeout(done, ms));
const git = (...args) => execFileSync("git", args, { cwd: root, encoding: "utf8" }).trim();
const limits = { run: 300_000, operation: 15_000, api: 5000, launch: 20_000, cdp: 5000, division: 90_000, history: 20_000, cleanup: 5000, trace: 15_000 };
const report = { status: "NOT_RUN", startedAt: new Date().toISOString(), limits, checks: [], sources: [], hosts: [], geometry: [], screenshots: [], pages: [], pageErrors: [], consoleErrors: [], unhandled: [], cleanupErrors: [], oracle: null, trace: { status: "NOT_RUN" }, sandbox: { status: "NOT_RUN" },
  qualifications: ["Actual release host and saved current API centers only; no fabricated cells, interpolated motion or model helper/hit-map geometry proof.", "Independent orthographic math uses copied actual camera facts and actual compositor PNG pixels, not Three projection functions.", "Center Sprite display pixels are not bodies, hydrodynamic radii, morphology or collisions; shared well-mixed chemistry is unchanged.", "Four Chromium viewport sizes; no achieved FPS, full accessibility, native background, cross-platform float or new science claim.", "WebGL loss/unavailable controls are explicitly negative renderer/input controls, not model states. Full existing 2D/chamber1 acceptance remains a separate protected regression gate."],
  workflowRun: process.env.GITHUB_RUN_ID ? `${process.env.GITHUB_SERVER_URL || "https://github.com"}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}` : null,
  runner: { node: process.version, os: process.env.RUNNER_OS || process.platform, image: process.env.ImageOS || null } };
let browser, context, page, traffic, host, temporary, origin, stopped = false, tracing = false, releaseHistory, releaseModule, running, hostLog = "";
const origins = new Set();
function fail(error, stage = "run") { stopped = true; report.status = "FAIL"; process.exitCode = 1; (report.failures ||= []).push({ stage, error: error.stack || String(error) }); }
process.on("unhandledRejection", (error) => { report.unhandled.push(error?.stack || String(error)); fail(error instanceof Error ? error : new Error(String(error)), "Node unhandled rejection"); });
async function bounded(operation, ms, label) { let timer; try { return await Promise.race([operation, new Promise((_, reject) => { timer = setTimeout(() => reject(new Error(`Timed out: ${label}`)), ms); })]); } finally { clearTimeout(timer); } }
async function check(name, action) { const start = Date.now(); try { assert.equal(stopped, false); await action(); report.checks.push({ name, status: "PASS", elapsedMs: Date.now() - start }); } catch (error) { report.checks.push({ name, status: "FAIL", elapsedMs: Date.now() - start, error: error.stack || String(error) }); throw error; } }
async function eventually(predicate, label, ms = limits.operation) { const end = Date.now() + ms; while (Date.now() < end) { assert.equal(stopped, false); if (host && (host.exitCode !== null || host.signalCode !== null)) throw new Error(`Host exited: ${hostLog}`); if (await predicate()) return; await sleep(40); } throw new Error(`Timed out: ${label}`); }
async function evaluate(...args) { return bounded(page.evaluate(...args), limits.operation, "browser evaluation"); }
async function api(path, body) { const response = await fetch(origin + path, { signal: AbortSignal.timeout(limits.api), cache: "no-store", ...(body ? { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) } : {}) }); assert.equal(response.status, 200, path); return response.json(); }
async function state(physical = true) { const value = await api("/api/state"); assert.equal(value.kind, "cells"); assert.equal(value.seed, "42"); assert.equal(value.dt_seconds, 30); assert.equal(value.chamber_format, physical ? 2 : 1); assert.equal(value.error, null); assert.equal(value.running, false); assert.ok(value.cells.length > 0 && value.cells.length <= 512); if (physical) { assert.equal(value.model.spatial_positions, true); assert.ok(value.model.dimensions_m.every((n) => Number.isFinite(n) && n > 0)); for (const cell of value.cells) assert.ok(typeof cell.id === "string" && cell.position_m.every((n, i) => Number.isFinite(n) && n >= 0 && n <= value.model.dimensions_m[i])); } return value; }
const heldFacts = (value) => ({ tick: value.tick, dt: value.dt_seconds, model: value.model, pacing: value.pacing, cells: value.cells, summary: value.summary, residual: value.residual });
async function source(filename) { const value = await readFile(join(root, filename)); assert.deepEqual(value, execFileSync("git", ["show", `HEAD:${filename}`], { cwd: root, maxBuffer: 16 * 1024 * 1024 })); report.sources.push({ filename, bytes: value.length, sha256: sha(value) }); return value; }
async function stopHost() { if (!host) return; if (host.exitCode === null && host.signalCode === null) { const exited = once(host, "exit"); host.kill("SIGTERM"); try { await bounded(exited, 3000, "host SIGTERM"); } catch { host.kill("SIGKILL"); await bounded(exited, 3000, "host SIGKILL"); } } host = null; }
async function startHost(label, filename, physical = true) {
  assert.equal(stopped, false); const reservation = createServer(); reservation.listen(0, "127.0.0.1"); await bounded(once(reservation, "listening"), 5000, "port reservation"); const port = reservation.address().port; await bounded(new Promise((done, reject) => reservation.close((error) => error ? reject(error) : done())), 3000, "port release");
  const dir = join(temporary, label); await mkdir(dir); const args = ["cells", "--seed", "42", "--port", String(port), "--data-dir", dir]; if (filename) args.push("--config", filename); origin = `http://127.0.0.1:${port}`; origins.add(origin); assert.equal(stopped, false);
  host = spawn(binary, args, { cwd: root, stdio: ["ignore", "pipe", "pipe"] }); const append = (value) => { hostLog = (hostLog + `[${label}] ${value}`).slice(-1024 * 1024); }; host.on("error", append); host.stdout.on("data", append); host.stderr.on("data", append);
  await eventually(async () => { try { return (await api("/api/state")).kind === "cells"; } catch { return false; } }, "actual host readiness"); await api("/api/control", { action: "pause" }); const snapshot = await state(physical);
  const response = await fetch(origin, { signal: AbortSignal.timeout(limits.api) }); assert.equal(response.status, 200); const served = Buffer.from(await response.arrayBuffer()); assert.deepEqual(served, await readFile(join(root, "crates/liminis/src/cell-viewer.html")));
  report.hosts.push({ label, args, origin, viewerSha256: sha(served), initialTick: snapshot.tick, model: snapshot.model, worldFormat: snapshot.world_format_version }); return snapshot;
}

// Tiny independent oracle. No Three.js imports or production projection helpers.
const dot = (a, b) => a.reduce((sum, n, i) => sum + n * b[i], 0), sub = (a, b) => a.map((n, i) => n - b[i]);
const cross = (a, b) => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];
const norm = (a) => { const length = Math.hypot(...a); assert.ok(length > 0 && Number.isFinite(length)); return a.map((n) => n / length); };
function rotate(q, v) { const u = q.slice(0, 3), t = cross(u, v).map((n) => n * 2), next = cross(u, t); return v.map((n, i) => n + q[3] * t[i] + next[i]); }
function near(a, b, label, tolerance = 1e-9) { assert.ok(Number.isFinite(a) && Number.isFinite(b) && Math.abs(a - b) <= tolerance, `${label}: ${a} / ${b}`); }
function cameraBasis(audit) {
  const c = audit.camera; assert.ok(c.position.length === 3 && c.quaternion.length === 4 && c.target.length === 3); assert.ok([...c.position, ...c.quaternion, ...c.target, ...c.up, c.left, c.right, c.top, c.bottom, c.near, c.far, c.zoom].every(Number.isFinite) && c.right > c.left && c.top > c.bottom && c.zoom > 0 && c.near > 0 && c.far > c.near); near(Math.hypot(...c.quaternion), 1, "unit quaternion");
  const right = rotate(c.quaternion, [1, 0, 0]), up = rotate(c.quaternion, [0, 1, 0]), back = rotate(c.quaternion, [0, 0, 1]);
  const expectedBack = norm(sub(c.position, c.target)), expectedRight = norm(cross(c.up, expectedBack)), expectedUp = cross(expectedBack, expectedRight);
  for (let i = 0; i < 3; i++) { near(back[i], expectedBack[i], "camera look direction"); near(right[i], expectedRight[i], "right-handed camera right"); near(up[i], expectedUp[i], "camera up"); }
  near(dot(cross(right, up), back), 1, "right-handed determinant"); return { right, up, back };
}
function project(position_m, audit) {
  const c = audit.camera, v = audit.viewport, basis = cameraBasis(audit), delta = sub(position_m.map((n) => n * audit.sceneScale), c.position), x = dot(delta, basis.right), y = dot(delta, basis.up), depth = -dot(delta, basis.back);
  const cx = (c.left + c.right) / 2, cy = (c.top + c.bottom) / 2, nx = (x - cx) * c.zoom * 2 / (c.right - c.left), ny = (y - cy) * c.zoom * 2 / (c.top - c.bottom);
  return { x: v.left + (nx + 1) * v.width / 2, y: v.top + (1 - ny) * v.height / 2, depth, inside: nx >= -1 && nx <= 1 && ny >= -1 && ny <= 1 && depth >= c.near && depth <= c.far };
}
function oracleCheck() {
  const audit = { sceneScale: 1, camera: { position: [0, 0, 2], target: [0, 0, 0], up: [0, 1, 0], quaternion: [0, 0, 0, 1], left: -2, right: 2, top: 1, bottom: -1, near: .01, far: 10, zoom: 1 }, viewport: { left: 5, top: 7, width: 400, height: 200 } };
  assert.deepEqual(project([0, 0, 0], audit), { x: 205, y: 107, depth: 2, inside: true }); near(project([1, 0, 0], audit).x, 305, "+x right"); near(project([0, 1, 0], audit).y, 7, "+y up"); near(project([0, 0, 1], audit).depth, 1, "+z depth"); assert.equal(project([3, 0, 0], audit).inside, false);
  const quarter = { ...audit, camera: { ...audit.camera, position: [2, 0, 0], quaternion: [0, Math.SQRT1_2, 0, Math.SQRT1_2] } }; near(project([0, 0, 1], quarter).x, 105, "+z rotates left"); return { status: "PASS", kind: "Synthetic arithmetic unit oracle, not API/model/browser states", cases: 6 };
}
function pngPixels(bytes) {
  assert.ok(bytes.length < 16 * 1024 * 1024 && bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))); let width, height, channels, offset = 8; const blocks = [];
  while (offset < bytes.length) { const length = bytes.readUInt32BE(offset), type = bytes.toString("ascii", offset + 4, offset + 8); assert.ok(offset + 12 + length <= bytes.length); const value = bytes.subarray(offset + 8, offset + 8 + length); if (type === "IHDR") { width = value.readUInt32BE(0); height = value.readUInt32BE(4); assert.equal(value[8], 8); assert.ok([2, 6].includes(value[9])); channels = value[9] === 6 ? 4 : 3; assert.equal(value[12], 0); } if (type === "IDAT") blocks.push(value); offset += length + 12; if (type === "IEND") break; }
  assert.ok(width > 0 && height > 0 && width * height <= 4 * 1024 * 1024); const stride = width * channels, raw = inflateSync(Buffer.concat(blocks), { maxOutputLength: height * (stride + 1) }); assert.equal(raw.length, height * (stride + 1)); const pixels = Buffer.alloc(width * height * channels);
  const paeth = (a, b, c) => { const p = a + b - c, x = Math.abs(p - a), y = Math.abs(p - b), z = Math.abs(p - c); return x <= y && x <= z ? a : y <= z ? b : c; };
  for (let row = 0; row < height; row++) { const filter = raw[row * (stride + 1)]; assert.ok(filter <= 4); for (let col = 0; col < stride; col++) { const index = row * stride + col, a = col >= channels ? pixels[index - channels] : 0, b = row ? pixels[index - stride] : 0, c = row && col >= channels ? pixels[index - stride - channels] : 0; pixels[index] = (raw[row * (stride + 1) + col + 1] + [0, a, b, Math.floor((a + b) / 2), paeth(a, b, c)][filter]) & 255; } }
  const rgba = Buffer.alloc(width * height * 4);
  for (let pixel = 0; pixel < width * height; pixel++) {
    pixels.copy(rgba, pixel * 4, pixel * channels, pixel * channels + 3);
    rgba[pixel * 4 + 3] = channels === 4 ? pixels[pixel * channels + 3] : 255;
  }
  return { width, height, rgba, at(x, y) { const i = (Math.max(0, Math.min(height - 1, Math.floor(y))) * width + Math.max(0, Math.min(width - 1, Math.floor(x)))) * 4; return [...rgba.subarray(i, i + 3)]; } };
}
// Exact whole compositor pixels, including alpha. PNG encoding is retained
// separately; no crop, mask, tolerance or repeated capture can hide a mismatch.
function pixelDifference(expected, actual) {
  const sameDimensions = expected.width === actual.width && expected.height === actual.height;
  if (!sameDimensions) return { equal: false, sameDimensions, changedPixels: null, bounds: null };
  let changedPixels = 0, left = expected.width, top = expected.height, right = -1, bottom = -1;
  for (let pixel = 0; pixel < expected.width * expected.height; pixel++) {
    const i = pixel * 4;
    if (expected.rgba.subarray(i, i + 4).equals(actual.rgba.subarray(i, i + 4))) continue;
    changedPixels++; const x = pixel % expected.width, y = Math.floor(pixel / expected.width);
    left = Math.min(left, x); top = Math.min(top, y); right = Math.max(right, x); bottom = Math.max(bottom, y);
  }
  return { equal: changedPixels === 0, sameDimensions, changedPixels, bounds: changedPixels ? { left, top, right, bottom } : null };
}
function contrast(image, x, y, radius = 2) { let result = 0; for (let dy = -radius; dy <= radius; dy++) for (let dx = -radius; dx <= radius; dx++) result = Math.max(result, ...image.at(x + dx, y + dy).map((n, i) => Math.abs(n - [8, 13, 11][i]))); return result; }
function glyphPixels(result, point) { const xs = [], ys = [], x = point.x * result.scaleX, y = point.y * result.scaleY; for (let dy = -10; dy <= 10; dy++) for (let dx = -10; dx <= 10; dx++) if (contrast(result.image, x + dx, y + dy, 0) > 8) { xs.push(dx); ys.push(dy); } assert.ok(xs.length); const widthCSS = (Math.max(...xs) - Math.min(...xs) + 1) / result.scaleX, heightCSS = (Math.max(...ys) - Math.min(...ys) + 1) / result.scaleY; assert.ok(widthCSS >= 5 && widthCSS <= 9 && heightCSS >= 5 && heightCSS <= 9, `Actual center Sprite screen dimensions: ${widthCSS}×${heightCSS}`); return { widthCSS, heightCSS, nominalCSS: 7, rasterToleranceCSS: 2 }; }
async function audit() { const value = await evaluate(() => getCellViewAudit()); assert.ok(value && Number.isSafeInteger(value.revision)); return value; }
async function shown(snapshot, mode = "3d") { await page.waitForFunction(({ tick, mode }) => { const a = getCellViewAudit(); return Number(document.getElementById("tick").textContent.replaceAll(",", "")) === tick && a.mode === mode && a.drawnTick === tick && a.drawnRevision === a.revision; }, { tick: snapshot.tick, mode }); }
async function choose3d(snapshot) { assert.equal(await page.locator("#view-mode").inputValue(), "2d"); await page.locator("#view-mode").selectOption("3d"); await shown(snapshot); assert.equal(await page.locator("#view-3d-status").textContent(), "Orthographic 3D · centers only"); }
async function sliceFacts() { return evaluate(() => ({ plane: document.getElementById("projection-plane").value, enabled: document.getElementById("slice-enabled").checked, center: document.getElementById("slice-center").valueAsNumber / 1e6, thickness: document.getElementById("slice-thickness").valueAsNumber / 1e6, centers: document.getElementById("layer-centers").checked, opacity: document.getElementById("centers-opacity").valueAsNumber })); }
function visibleCells(snapshot, settings) { const axis = { xy: 2, xz: 1, yz: 0 }[settings.plane]; return snapshot.cells.filter((cell) => !settings.enabled || cell.position_m[axis] >= Math.max(0, settings.center - settings.thickness / 2) && cell.position_m[axis] <= Math.min(snapshot.model.dimensions_m[axis], settings.center + settings.thickness / 2)); }
async function geometry(snapshot, label) {
  await shown(snapshot); const value = await audit(), settings = await sliceFacts(); assert.deepEqual(value.dimensions_m, snapshot.model.dimensions_m); near(value.sceneScale * Math.max(...snapshot.model.dimensions_m), 1, "one common XYZ scale"); const c = value.camera, v = value.viewport; cameraBasis(value); near(v.width * c.zoom / (c.right - c.left) / (v.height * c.zoom / (c.top - c.bottom)), 1, "orthographic equal screen scale");
  assert.ok(v.width > 0 && v.height > 0 && v.left >= 0 && v.top >= 0 && v.left + v.width <= v.rect.width + 1 && v.top + v.height <= v.rect.height + 1); assert.match(await page.locator("#chamber-3d").getAttribute("aria-label"), /centers|center/i);
  const bytes = await bounded(page.locator("#chamber-3d").screenshot(), limits.operation, "actual compositor canvas PNG"), image = pngPixels(bytes), scaleX = image.width / v.rect.width, scaleY = image.height / v.rect.height; near(scaleX, scaleY, "canvas screenshot pixel aspect", .01);
  const cells = visibleCells(snapshot, settings), points = cells.map((cell) => ({ id: cell.id, ...project(cell.position_m, value) }));
  if (settings.centers && settings.opacity > 0) for (const point of points.filter((item) => item.inside)) assert.ok(contrast(image, point.x * scaleX, point.y * scaleY, 2) > 8, `Actual API→PNG marker missing: ${point.id}`);
  const displayed = settings.centers && settings.opacity > 0 ? points.filter((item) => item.inside).length : 0;
  assert.equal(await page.locator("#cell-count").textContent(), `${displayed.toLocaleString("en-US")} / ${snapshot.cells.length.toLocaleString("en-US")}`);
  const nativeGL = await evaluate(() => window.__threeQaGL); assert.equal(nativeGL.creations, 1); assert.match(nativeGL.backend.version, /WebGL 2/i); assert.equal(value.resources.contextCreations, 1); assert.equal(value.resources.paletteMaterials, 8); assert.equal(value.resources.materials, 15); assert.equal(value.resources.textures, 2); assert.equal(value.resources.geometries, 7); assert.ok(value.resources.sprites <= snapshot.cells.length && value.resources.visibleSprites === displayed && value.resources.selectionSprites <= 1 && value.resources.rendererGeometries <= 16 && value.resources.rendererTextures <= 4);
  report.geometry.push({ label, tick: snapshot.tick, audit: value, slice: settings, visibleIds: points.filter((p) => p.inside && settings.centers && settings.opacity > 0).map((p) => p.id), independentlyProjected: points, compositorSha256: sha(bytes), pixelScale: [scaleX, scaleY] }); return { audit: value, points, bytes, image, scaleX, scaleY };
}
function boxPoints(snapshot, value) { const corners = Array.from({ length: 8 }, (_, mask) => snapshot.model.dimensions_m.map((n, axis) => mask >> axis & 1 ? n : 0)), edges = []; for (let mask = 0; mask < 8; mask++) for (let axis = 0; axis < 3; axis++) if (!(mask >> axis & 1)) edges.push({ axis, a: project(corners[mask], value), b: project(corners[mask | 1 << axis], value) }); return edges; }
async function boxPixels(snapshot, result, label) {
  const edges = boxPoints(snapshot, result.audit); for (const edge of edges) { assert.ok(edge.a.inside && edge.b.inside); const x = (edge.a.x + edge.b.x) / 2, y = (edge.a.y + edge.b.y) / 2; assert.ok(contrast(result.image, x * result.scaleX, y * result.scaleY, 2) > 12, `Real box edge missing: ${label}/${edge.axis}`); }
  const labels = await page.locator("#axis-labels > *").evaluateAll((nodes) => nodes.map((n) => ({ text: n.textContent, left: parseFloat(n.style.left), top: parseFloat(n.style.top), hidden: n.hidden })));
  assert.equal(labels.length, 3); for (let axis = 0; axis < 3; axis++) { const p = [0, 0, 0]; p[axis] = snapshot.model.dimensions_m[axis]; const expected = project(p, result.audit); assert.equal(labels[axis].text, `${["x", "y", "z"][axis]} · ${(p[axis] * 1e6).toLocaleString("en-US", { maximumSignificantDigits: 6 })} µm`); assert.equal(labels[axis].hidden, false); near(labels[axis].left, expected.x + 5, "axis label CSS projection", .02); near(labels[axis].top, expected.y - 16, "axis label CSS projection", .02); }
  assert.match(await page.locator("#projection-range").textContent(), /Box x .*µm.*y .*µm.*z .*µm/); report.boxPixels = { label, edgeCount: edges.length, labels, independentlyProjectedEdges: edges };
}
async function slice(center, thickness) { await page.locator("#slice-center").fill(String(center * 1e6)); await page.locator("#slice-thickness").fill(String(thickness * 1e6)); await page.locator("#slice-thickness").dispatchEvent("change"); assert.equal(await page.locator("#slice-error").isVisible(), false); return sliceFacts(); }
async function opacity(value) { await page.locator("#centers-opacity").evaluate((node, value) => { node.value = String(value); node.dispatchEvent(new Event("input", { bubbles: true })); }, value); }
async function drag(dx, dy, button = "left", returnToOrigin = false) { const a = await audit(), rect = a.viewport.rect, x = rect.left + a.viewport.left + a.viewport.width / 2, y = rect.top + a.viewport.top + a.viewport.height / 2; await page.mouse.move(x, y); await page.mouse.down({ button }); try { await page.mouse.move(x + dx, y + dy, { steps: 8 }); if (returnToOrigin) await page.mouse.move(x, y, { steps: 8 }); } finally { await page.mouse.up({ button }); } }
async function candidateIds() { return page.locator("#candidate-list option").evaluateAll((nodes) => nodes.map((n) => n.value)); }
async function responsive(snapshot) {
  for (const [label, width, height] of [["desktop", 1440, 900], ["short", 1440, 720], ["mobile390", 390, 844], ["mobile320", 320, 844]]) {
    await page.setViewportSize({ width, height }); await page.locator("#camera-reset").click(); const g = await geometry(snapshot, label); await boxPixels(snapshot, g, label);
    const layout = await evaluate(() => { const a = getCellViewAudit(), controls = document.getElementById("projection-controls").getBoundingClientRect(), caption = document.querySelector(".stage-caption").getBoundingClientRect(), meta = document.querySelector(".stage-meta").getBoundingClientRect(); return { overflow: document.documentElement.scrollWidth > innerWidth, controls: { bottom: controls.bottom, left: controls.left, right: controls.right }, captionBottom: caption.bottom, metaTop: meta.top, viewportTop: a.viewport.rect.top + a.viewport.top, viewportBottom: a.viewport.rect.top + a.viewport.top + a.viewport.height }; });
    assert.equal(layout.overflow, false); assert.ok(layout.controls.left >= 0 && layout.controls.right <= width + 1 && layout.viewportTop > layout.controls.bottom && layout.viewportTop > layout.captionBottom && layout.viewportBottom < layout.metaTop); for (const selector of ["#view-mode", "#camera-reset", "#layer-centers", "#layer-box", "#layer-slice", "#centers-opacity", "#step", "#screen-fps"]) assert.equal(await page.locator(selector).isVisible(), true);
    (report.layouts ||= []).push({ label, width, height, layout, actualViewport: g.audit.viewport }); await screenshot(`${label}.png`);
  }
  await page.setViewportSize({ width: 1440, height: 900 }); await page.locator("#camera-reset").click(); await shown(snapshot);
}
async function assets() {
  const paths = [["/assets/cell-viewer-3d.mjs", "crates/liminis/src/cell-viewer-3d.mjs"], ...["three.module.js", "three.core.js", "OrbitControls.js", "LICENSE", "provenance.json"].map((n) => [`/assets/vendor/three-r180/${n}`, `crates/liminis/src/vendor/three-r180/${n}`])];
  for (const [url, filename] of paths) { const bytes = await source(filename), response = await fetch(origin + url, { signal: AbortSignal.timeout(limits.api) }); assert.equal(response.status, 200); assert.match(response.headers.get("content-type"), filename.endsWith(".json") ? /json/ : filename.endsWith("LICENSE") ? /text\/plain/ : /javascript/); const actual = Buffer.from(await response.arrayBuffer()); assert.deepEqual(actual, bytes); (report.assets ||= []).push({ url, filename, bytes: actual.length, sha256: sha(actual), contentType: response.headers.get("content-type") }); }
  const provenance = JSON.parse(await readFile(join(root, "crates/liminis/src/vendor/three-r180/provenance.json"))); assert.equal(provenance.version, "0.180.0"); assert.equal(provenance.commit, "0af9729d0c143a86a1d725d6e2c3ad83301f3f34"); assert.equal(provenance.unmodified, true); for (const item of provenance.files) { const bytes = await readFile(join(root, "crates/liminis/src/vendor/three-r180", item.path)); assert.equal(bytes.length, item.bytes); assert.equal(sha(bytes), item.sha256); } report.vendor = { version: provenance.version, commit: provenance.commit, provenanceSha256: sha(await readFile(join(root, "crates/liminis/src/vendor/three-r180/provenance.json"))) };
}
async function inspector() { return page.locator("#cell-detail").evaluate((node) => Object.fromEntries([...node.querySelectorAll("dt")].map((term) => [term.textContent, term.nextElementSibling.textContent]))); }
async function inspect(cell, tick) { await eventually(async () => (await inspector()).id === cell.id && (await inspector())["shown snapshot tick"] === String(tick), "exact ID/current inspector"); const fields = await inspector(); for (const [index, axis] of ["x", "y", "z"].entries()) { assert.match(fields[`${axis} center`], / µm$/); near(Number(fields[`${axis} center`].replace(" µm", "").replaceAll(",", "")), cell.position_m[index] * 1e6, "inspector actual µm", .002); } }
async function search(id) { await page.locator("#cell-id").fill(id); await page.locator("#cell-search button[type=submit]").click(); }
async function tap(point) { const rect = await page.locator("#chamber-3d").boundingBox(); await page.mouse.click(rect.x + point.x, rect.y + point.y); }
async function screenshot(filename) { const bytes = await bounded(page.screenshot({ fullPage: true, path: join(output, filename) }), limits.operation, "full page PNG"); report.screenshots.push({ filename, bytes: bytes.length, sha256: sha(bytes) }); }
async function newPage(options = {}) {
  assert.equal(stopped, false); page = await bounded(context.newPage(), limits.operation, "page creation"); traffic = { origin, stateStarts: [], activeState: 0, maxState: 0, posts: [], failures: [], external: [], resources: [] }; report.pages.push(traffic); const active = new Set();
  const localTraffic = traffic, pageOrigin = origin; // Each page retains its own identities even after the next page opens.
  page.on("request", (request) => { const url = new URL(request.url()); if (url.origin !== pageOrigin) localTraffic.external.push(request.url()); if (url.pathname === "/api/state") { active.add(request); localTraffic.activeState = active.size; localTraffic.stateStarts.push(Date.now()); localTraffic.maxState = Math.max(localTraffic.maxState, active.size); } if (request.method() === "POST") localTraffic.posts.push(request.postData()); localTraffic.resources.push({ url: request.url(), method: request.method(), type: request.resourceType() }); });
  const finish = (request) => { active.delete(request); localTraffic.activeState = active.size; }; page.on("requestfinished", finish); page.on("requestfailed", (request) => { finish(request); localTraffic.failures.push({ url: request.url(), error: request.failure()?.errorText }); });
  page.on("pageerror", (error) => report.pageErrors.push(error.stack || error.message)); page.on("console", (message) => { if (message.type() !== "error") return; const record = { text: message.text(), location: message.location(), page: report.pages.indexOf(localTraffic), expectedNegativeControl: false }; if (options.unavailable === true && record.text === "THREE.WebGLRenderer: Error creating WebGL context." && record.location.url === pageOrigin + "/assets/vendor/three-r180/three.module.js" && !localTraffic.expectedCreationError) { record.expectedNegativeControl = true; localTraffic.expectedCreationError = true; } report.consoleErrors.push(record); });
  await page.addInitScript(({ unavailable }) => {
    window.__threeQaUnhandled = []; addEventListener("unhandledrejection", (event) => window.__threeQaUnhandled.push(String(event.reason?.stack || event.reason))); window.__threeQaGL = { creations: 0, calls: [], backend: null }; const contexts = new WeakSet(), original = HTMLCanvasElement.prototype.getContext;
    HTMLCanvasElement.prototype.getContext = function (...args) { const webgl = String(args[0]).startsWith("webgl"), target = this.id === "chamber-3d" && webgl; if (target && unavailable) return null; const result = Reflect.apply(original, this, args); if (webgl) { if (window.__threeQaGL.calls.length < 32) window.__threeQaGL.calls.push({ canvasId: this.id, type: args[0], success: result !== null }); else throw new Error("QA context observation bound exceeded"); if (result && !contexts.has(result)) { contexts.add(result); window.__threeQaGL.creations++; const e = result.getExtension("WEBGL_debug_renderer_info"); window.__threeQaGL.backend = { version: result.getParameter(result.VERSION), vendor: result.getParameter(e ? e.UNMASKED_VENDOR_WEBGL : result.VENDOR), renderer: result.getParameter(e ? e.UNMASKED_RENDERER_WEBGL : result.RENDERER) }; } } return result; };
  }, { unavailable: options.unavailable === true });
  await page.goto(origin, { waitUntil: "domcontentloaded" }); await page.waitForFunction(() => document.getElementById("live-label").textContent === "paused"); return traffic;
}
async function pageEnd() { traffic.unhandled = await evaluate(() => window.__threeQaUnhandled); traffic.nativeGL = await evaluate(() => window.__threeQaGL); assert.deepEqual(traffic.unhandled, []); assert.deepEqual(traffic.external, []); assert.deepEqual(traffic.failures, []); assert.equal(traffic.maxState, 1); await eventually(() => traffic.activeState === 0, "page network drain before closure"); await page.close(); traffic.closed = true; page = null; }
async function step(before, mode = "3d") { await page.locator("#step").click(); let next; await eventually(async () => { next = await state(); return next.tick === before.tick + 1; }, "one actual paused Step"); await shown(next, mode); assert.equal(await page.locator("#control-error").textContent(), ""); return next; }
async function holdOriginal(path, key) {
  let capture, release; const captured = new Promise((done) => { capture = done; }), held = new Promise((done) => { release = done; }); let used = false;
  await context.route(origin + path, async (route) => { if (used) return route.continue(); used = true; try { const response = await route.fetch({ timeout: limits.operation }), bytes = await bounded(response.body(), limits.operation, "original bounded response bytes"); assert.equal(response.status(), 200); report[key] = { status: "HELD", path, bytes: bytes.length, sha256: sha(bytes), originalStatus: response.status(), originalHeaders: response.headers(), qualification: "Delayed route.fetch original response; only exact original bytes are fulfilled" }; await writeFile(join(output, key === "delayedHistory" ? "held-history.json" : "held-module.mjs"), bytes); capture(); await bounded(held, limits.history, "intentional original response hold"); await route.fulfill({ response, body: bytes }); report[key].status = "RELEASED"; } catch (error) { (report.routeErrors ||= []).push(error.stack || String(error)); capture(); await route.abort().catch((error) => (report.routeErrors ||= []).push(String(error))); } });
  return { captured, release };
}

async function run() {
  report.sourceHead = git("rev-parse", "HEAD"); report.sourceTree = git("rev-parse", "HEAD^{tree}"); assert.ok(process.env.LIMINIS_EXPECTED_HEAD && process.env.LIMINIS_EXPECTED_TREE); assert.equal(report.sourceHead, process.env.LIMINIS_EXPECTED_HEAD); assert.equal(report.sourceTree, process.env.LIMINIS_EXPECTED_TREE); assert.equal(git("status", "--porcelain", "--untracked-files=no"), "");
  for (const name of ["scripts/check_physical_3d_browser.mjs", "crates/liminis/src/cell-viewer.html", "crates/liminis/src/cell-viewer-3d.mjs", "configs/scenarios/cell-chamber-physical.toml"]) await source(name);
  const info = await stat(binary); assert.ok(info.size < 128 * 1024 * 1024); report.binary = { bytes: info.size, sha256: sha(await readFile(binary)), provenance: "Existing protected CI release build, not cryptographic standalone source attestation" }; report.oracle = oracleCheck();
  const original = await readFile(config), text = original.toString(), pattern = /^dimensions_m = \[1\.0e-4, 1\.0e-4, 1\.0e-4\]$/m; assert.ok(pattern.test(text)); assert.equal((text.match(/^dimensions_m\s*=/gm) || []).length, 1); temporary = await mkdtemp(join(tmpdir(), "liminis-3d-browser-")); const fixture = Buffer.from(text.replace(pattern, "dimensions_m = [2.0e-4, 1.0e-4, 5.0e-5]")), fixturePath = join(temporary, "physical-nonsquare.toml"); await writeFile(fixturePath, fixture); await writeFile(join(output, "physical-nonsquare.toml"), fixture); report.configs = { sourceSha256: sha(original), fixtureSha256: sha(fixture), onlyChange: "dimensions [2e-4,1e-4,5e-5]; same mathematical product, binary volume recorded separately" };
  const require = createRequire(import.meta.url), moduleId = process.env.LIMINIS_PLAYWRIGHT_MODULE; assert.ok(moduleId); const pkg = require(`${moduleId}/package.json`); assert.equal(pkg.name, "playwright"); assert.equal(pkg.version, "1.61.1"); browser = await require(moduleId).chromium.launch({ headless: true, chromiumSandbox: true, args: ["--enable-automation"], timeout: limits.launch }); report.browser = { version: browser.version(), playwright: pkg.version, chromiumSandbox: true };
  await check("Observed official Chromium argv preserves sandbox; exact stock launch adds only enable-automation", async () => { const session = await bounded(browser.newBrowserCDPSession(), limits.cdp, "CDP session"); try { const { arguments: argv } = await bounded(session.send("Browser.getBrowserCommandLine"), limits.cdp, "actual browser argv"); const forbidden = new Set(["--no-sandbox", "--no-zygote-sandbox", "--disable-setuid-sandbox", "--disable-namespace-sandbox", "--disable-seccomp-filter-sandbox", "--disable-gpu-sandbox", "--allow-sandbox-debugging", "--single-process", "--ignore-gpu-blocklist", "--disable-web-security"]); report.sandbox.arguments = argv; report.sandbox.launchSettings = { headless: true, chromiumSandbox: true, args: ["--enable-automation"] }; report.sandbox.stockGPUFlags = argv.filter((n) => /swiftshader|^--use-gl=|^--use-angle=/.test(n)); report.sandbox.qualification = "Pinned official Playwright defaults may include enable-unsafe-swiftshader. No extra GPU switches supplied; actual backend is reported, hardware GPU is unasserted. Same accepted sandbox process model."; assert.ok(argv.length > 0 && argv.every((n) => typeof n === "string")); assert.deepEqual(argv.map((n) => n.split("=", 1)[0]).filter((n) => forbidden.has(n) || /^--disable-.*sandbox$/.test(n)), []); report.sandbox.status = "PASS"; } finally { await bounded(session.detach(), limits.cdp, "CDP detach"); } });
  assert.equal(stopped, false); context = await bounded(browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1, hasTouch: true }), limits.operation, "context creation"); context.setDefaultTimeout(limits.operation); context.setDefaultNavigationTimeout(limits.operation); await context.route("**/*", async (route) => { if (!origins.has(new URL(route.request().url()).origin)) { (report.prohibitedRequests ||= []).push(route.request().url()); await route.abort(); } else await route.continue(); }); await bounded(context.tracing.start({ screenshots: true, snapshots: true, sources: true }), limits.cdp, "trace start"); tracing = true; report.status = "RUNNING";
  await check("Actual source cube defaults to 2D; WebGL2 and independent SI centers/box match compositor pixels", async () => { const initial = await startHost("source-cube", config); await assets(); await newPage(); assert.equal((await audit()).mode, "2d"); assert.equal((await audit()).resources.contextCreations, 0); await choose3d(initial); const result = await geometry(initial, "source-cube"); await boxPixels(initial, result, "source-cube"); report.sourceVolume = initial.model.volume_m3; report.backend = result.audit.backend; assert.match(report.backend.version, /WebGL 2/i); assert.ok(report.backend.vendor && report.backend.renderer); await writeFile(join(output, "source-cube-state.json"), JSON.stringify(initial, null, 2) + "\n"); await screenshot("source-cube.png"); await pageEnd(); await stopHost(); });
  let snapshot = await startHost("nonsquare", fixturePath); assert.deepEqual(snapshot.model.dimensions_m, [2e-4, 1e-4, 5e-5]); near(snapshot.model.volume_m3 / ((2e-4 * 1e-4) * 5e-5), 1, "actual nonsquare volume", 1e-14); report.nonsquareVolume = snapshot.model.volume_m3; await writeFile(join(output, "nonsquare-state.json"), JSON.stringify(snapshot, null, 2) + "\n");
  const history = await holdOriginal("/api/history", "delayedHistory"), module = await holdOriginal("/assets/cell-viewer-3d.mjs", "delayedModule"); releaseHistory = history.release; releaseModule = module.release;
  await newPage();
  await check("A real Step commits current 2D/3D geometry and inspector before held original history; lazy activation uses latest snapshot", async () => {
    await bounded(history.captured, limits.operation, "original history capture"); const selected = snapshot.cells[0]; await search(selected.id); await inspect(selected, snapshot.tick);
    await page.locator("#view-mode").selectOption("3d"); await bounded(module.captured, limits.operation, "original 3D module capture"); assert.equal((await audit()).mode, "2d"); assert.match(await page.locator("#view-3d-status").textContent(), /Loading 3D.*2D remains shown/);
    const before = snapshot; snapshot = await step(before, "2d"); const current = snapshot.cells.find((c) => c.id === selected.id); assert.ok(current); await inspect(current, snapshot.tick); assert.equal(report.delayedHistory.status, "HELD"); module.release(); await shown(snapshot); await geometry(snapshot, "atomic-after-lazy-import-before-history"); await inspect(current, snapshot.tick);
    assert.equal(await page.locator("#history-state").textContent(), "history · loading"); assert.equal(report.delayedHistory.status, "HELD"); assert.ok(snapshot.cells.some((c) => before.cells.some((old) => old.id === c.id && c.position_m.some((n, i) => n !== old.position_m[i])))); report.atomicStep = { fromTick: before.tick, toTick: snapshot.tick, selectedId: selected.id, historyReleasedAtAssertion: false, lazyActivationTick: (await audit()).drawnTick }; history.release(); await eventually(async () => report.delayedHistory.status === "RELEASED" && report.delayedModule.status === "RELEASED", "original responses released"); assert.deepEqual(report.routeErrors || [], []);
  });
  const viewBefore = heldFacts(await state()), viewPosts = traffic.posts.length;
  await check("Real orbit, zoom, pan and reset preserve paused SI data and project actual centers with equal scale", async () => {
    await page.locator("#camera-reset").click(); const initial = await geometry(snapshot, "nonsquare-reset"); await boxPixels(snapshot, initial, "nonsquare-reset"); const first = initial.points.find((p) => p.inside && initial.points.every((q) => q.id === p.id || Math.hypot(q.x - p.x, q.y - p.y) > 18)); assert.ok(first); await tap(first); await inspect(snapshot.cells.find((c) => c.id === first.id), snapshot.tick);
    await drag(74, 38); const orbit = await geometry(snapshot, "actual-pointer-orbit"); assert.notDeepEqual(orbit.audit.camera.quaternion, initial.audit.camera.quaternion); assert.notEqual(sha(orbit.bytes), sha(initial.bytes)); assert.ok(orbit.points.some((p) => { const old = initial.points.find((q) => q.id === p.id); return Math.hypot(p.x - old.x, p.y - old.y) > 3; })); await boxPixels(snapshot, orbit, "orbit");
    const rect = orbit.audit.viewport.rect; await page.mouse.move(rect.left + orbit.audit.viewport.left + orbit.audit.viewport.width / 2, rect.top + orbit.audit.viewport.top + orbit.audit.viewport.height / 2); await page.mouse.wheel(0, -120); const zoom = await geometry(snapshot, "actual-wheel-zoom"); assert.ok(zoom.audit.camera.zoom > orbit.audit.camera.zoom);
    await drag(30, 16, "right"); const pan = await geometry(snapshot, "actual-right-pointer-pan"); assert.notDeepEqual(pan.audit.camera.target, zoom.audit.camera.target); assert.notEqual(sha(pan.bytes), sha(zoom.bytes));
    await page.locator("#camera-reset").click(); const reset = await geometry(snapshot, "actual-reset"); for (const key of ["position", "target", "quaternion"]) reset.audit.camera[key].forEach((n, i) => near(n, initial.audit.camera[key][i], `reset ${key}`)); assert.equal(reset.audit.camera.zoom, 1);
    await drag(reset.audit.viewport.width * .8, 0, "right"); const moved = await geometry(snapshot, "pan-outside-current-view"), outside = moved.points.find((p) => !p.inside); assert.ok(outside); await search(outside.id); await inspect(snapshot.cells.find((c) => c.id === outside.id), snapshot.tick); assert.equal(await page.locator("#selection-state").textContent(), "outside current view"); await page.locator("#camera-reset").click(); await shown(snapshot); assert.deepEqual(heldFacts(await state()), viewBefore); assert.equal(traffic.posts.length, viewPosts); report.camera = { actualRotate: true, actualPan: true, actualZoom: true, actualReset: true, outsideViewId: outside.id, pausedTick: snapshot.tick };
  });
  await check("Exact ID, arrows and peak-movement/cancel gestures use current camera revision without selecting on drag", async () => {
    const unknown = "18446744073709551615"; assert.ok(!snapshot.cells.some((c) => c.id === unknown)); await search(unknown); assert.equal(await page.locator("#selection-state").textContent(), "not present"); const absent = await page.locator("#cell-detail").textContent(); assert.ok(absent.includes(unknown)); assert.doesNotMatch(absent, /\bdead\b|\bdied\b/);
    const g = await geometry(snapshot, "keyboard-camera"), ids = g.points.filter((p) => p.inside).map((p) => p.id).sort((a, b) => BigInt(a) < BigInt(b) ? -1 : 1); assert.ok(ids.length > 1); await page.locator("#chamber-3d").focus(); await page.keyboard.press("ArrowRight"); await inspect(snapshot.cells.find((c) => c.id === ids[0]), snapshot.tick); await page.keyboard.press("ArrowLeft"); await inspect(snapshot.cells.find((c) => c.id === ids.at(-1)), snapshot.tick); assert.deepEqual((await audit()).camera, g.audit.camera);
    await search(unknown); await drag(30, 0, "left", true); assert.equal(await page.locator("#selection-state").textContent(), "not present"); assert.equal((await inspector()).id, undefined); assert.equal(await page.locator("#hit-candidates").isVisible(), false);
    const a = await audit(), p = project(snapshot.cells[0].position_m, a), session = await context.newCDPSession(page); try { await bounded(session.send("Input.dispatchTouchEvent", { type: "touchStart", touchPoints: [{ x: a.viewport.rect.left + p.x, y: a.viewport.rect.top + p.y }] }), limits.cdp, "native touch start"); await bounded(session.send("Input.dispatchTouchEvent", { type: "touchCancel", touchPoints: [] }), limits.cdp, "native touch cancel"); } finally { await bounded(session.detach(), limits.cdp, "input CDP detach"); }
    assert.equal(await page.locator("#selection-state").textContent(), "not present"); assert.equal(await page.locator("#hit-candidates").isVisible(), false); await page.locator("#camera-reset").click(); report.gestures = { arrowIds: [ids[0], ids.at(-1)], cameraUnchangedByArrow: true, dragReturnPeakCSSpx: 30, cancel: "Actual CDP touch input cancellation; input negative control, no fabricated cells" };
  });
  await check("Opacity and center/box/slice layers change actual pixels; hidden centers have no pointer targets", async () => {
    await search("18446744073709551615"); await page.locator("#layer-box").uncheck(); const full = await geometry(snapshot, "centers-only-full-opacity"), isolated = full.points.find((p) => p.inside && full.points.every((q) => q.id === p.id || Math.hypot(q.x - p.x, q.y - p.y) > 25)); assert.ok(isolated); const glyph = glyphPixels(full, isolated), strength = contrast(full.image, isolated.x * full.scaleX, isolated.y * full.scaleY);
    const v = full.audit.viewport; await page.mouse.move(v.rect.left + v.left + v.width / 2, v.rect.top + v.top + v.height / 2); await page.mouse.wheel(0, -120); const zoomed = await geometry(snapshot, "centers-only-zoom-fixed-glyph"), zoomGlyph = glyphPixels(zoomed, zoomed.points.find((p) => p.id === isolated.id)); assert.ok(zoomed.audit.camera.zoom > full.audit.camera.zoom); await page.locator("#camera-reset").click(); await shown(snapshot);
    await opacity(.2); const transparent = await geometry(snapshot, "centers-opacity-020"), low = contrast(transparent.image, isolated.x * transparent.scaleX, isolated.y * transparent.scaleY); assert.ok(low > 8 && low < strength * .65, `Actual opacity pixel contrast: ${low}/${strength}`); assert.notEqual(sha(full.bytes), sha(transparent.bytes));
    await opacity(0); const zero = await geometry(snapshot, "zero-opacity"); assert.ok(contrast(zero.image, isolated.x * zero.scaleX, isolated.y * zero.scaleY) < 4); await tap(isolated); assert.equal((await inspector()).id, undefined); assert.equal(await page.locator("#hit-candidates").isVisible(), false); await search(isolated.id); await inspect(snapshot.cells.find((c) => c.id === isolated.id), snapshot.tick); assert.equal(await page.locator("#selection-state").textContent(), "centers layer hidden");
    await opacity(1); await page.locator("#layer-centers").uncheck(); await geometry(snapshot, "centers-layer-off"); assert.equal(await page.locator("#selection-state").textContent(), "centers layer hidden"); await tap(isolated); assert.equal((await inspector()).id, undefined); assert.equal(await page.locator("#hit-candidates").isVisible(), false); await page.locator("#layer-centers").check();
    await page.locator("#layer-box").check(); const boxed = await geometry(snapshot, "box-layer-on"); await boxPixels(snapshot, boxed, "box-layer-on"); assert.notEqual(sha(boxed.bytes), sha(full.bytes)); await page.locator("#layer-box").uncheck(); const unboxed = await geometry(snapshot, "box-layer-off"); assert.notEqual(sha(boxed.bytes), sha(unboxed.bytes));
    await page.locator("#slice-enabled").check(); await slice(snapshot.model.dimensions_m[2] / 2, snapshot.model.dimensions_m[2] / 3); const plane = await geometry(snapshot, "slice-boundaries-on"); await page.locator("#layer-slice").uncheck(); const noPlane = await geometry(snapshot, "slice-boundaries-off"); assert.notEqual(sha(plane.bytes), sha(noPlane.bytes)); await page.locator("#layer-slice").check(); await page.locator("#slice-enabled").uncheck(); await page.locator("#layer-box").check(); await opacity(1); assert.deepEqual(heldFacts(await state()), viewBefore); report.layers = { fullContrast: strength, opacity020Contrast: low, opacityZeroContrast: contrast(zero.image, isolated.x * zero.scaleX, isolated.y * zero.scaleY), actualPixelChanges: true, noHiddenPointerTargets: true, glyph, zoomGlyph };
  });
  await check("All slice axes use inclusive real centers and exact zero-width inputs; outside selection stays inspectable", async () => {
    for (const [plane, axis] of [["xy", 2], ["xz", 1], ["yz", 0]]) { await page.locator("#projection-plane").selectOption(plane); await page.locator("#slice-enabled").check(); await slice(snapshot.model.dimensions_m[axis] / 2, snapshot.model.dimensions_m[axis]); const g = await geometry(snapshot, `full-inclusive-${plane}`), point = g.points.find((p) => p.inside && g.points.every((q) => p.id === q.id || Math.hypot(p.x - q.x, p.y - q.y) > 18)); assert.ok(point); await tap(point); await inspect(snapshot.cells.find((c) => c.id === point.id), snapshot.tick); }
    const edge = snapshot.cells.flatMap((cell) => cell.position_m.map((value, axis) => ({ cell, value, axis }))).find(({ value, axis }) => value > 0 && value < snapshot.model.dimensions_m[axis] / 2 && (value * 1e6) / 1e6 === value && (2 * value * 1e6) / 1e6 === 2 * value); assert.ok(edge); const plane = ["yz", "xz", "xy"][edge.axis]; await page.locator("#projection-plane").selectOption(plane);
    for (const [label, center, thickness] of [["inclusive-upper", 0, edge.value * 2], ["inclusive-lower", edge.value * 2, edge.value * 2], ["exact-zero-width", edge.value, 0]]) { const actual = await slice(center, thickness), member = visibleCells(snapshot, actual); assert.ok(member.some((c) => c.id === edge.cell.id)); assert.equal(label === "inclusive-upper" ? actual.center + actual.thickness / 2 : label === "inclusive-lower" ? actual.center - actual.thickness / 2 : actual.center, edge.value); await geometry(snapshot, label); }
    const camera = await audit(), currentSlice = await sliceFacts(), members = visibleCells(snapshot, currentSlice); const outside = snapshot.cells.find((c) => c.position_m[edge.axis] !== edge.value && members.every((inside) => { const a = project(c.position_m, camera), b = project(inside.position_m, camera); return Math.hypot(a.x - b.x, a.y - b.y) > 18; })); assert.ok(outside); await search(outside.id); await inspect(outside, snapshot.tick); assert.equal(await page.locator("#selection-state").textContent(), "outside slice"); const before = await geometry(snapshot, "outside-slice-selected"), hidden = project(outside.position_m, before.audit); await tap(hidden); assert.equal((await inspector()).id, undefined); assert.equal(await page.locator("#hit-candidates").isVisible(), false); await search(outside.id); await inspect(outside, snapshot.tick);
    report.sliceBoundary = { axis: edge.axis, plane, actualInputCenter_m: (await sliceFacts()).center, boundaryId: edge.cell.id, outsideId: outside.id, zeroWidthMembershipFromActualInputs: true }; await page.locator("#slice-enabled").uncheck(); await page.locator("#projection-plane").selectOption("xy");
  });
  await check("Paused target30/60 draws hold exact canvas/API state and preserve normal single-flight polling", async () => {
    await geometry(snapshot, "paused-before-display-controls");
    const windows = [], captures = [];
    report.pausedDraw = { tick: snapshot.tick, windows, captures, identity: "Exact dimensions and every decoded RGBA pixel of the whole compositor region; no tolerance or masking", achievedFPS: "UNASSERTED" };
    const heldLayers = async () => ({ ...await sliceFacts(), box: await page.locator("#layer-box").isChecked(), slice: await page.locator("#layer-slice").isChecked() });
    async function capture(label) {
      const entry = { label, file: `paused-${label}.png`, startedAtMs: performance.now() };
      captures.push(entry);
      Object.assign(entry, { apiBefore: heldFacts(await state()), layersBefore: await heldLayers(), auditBefore: await audit() });
      const bytes = await bounded(page.locator("#chamber-3d").screenshot(), limits.operation, `paused ${label} compositor PNG`);
      await writeFile(join(output, entry.file), bytes);
      Object.assign(entry, { pngBytes: bytes.length, pngSha256: sha(bytes), capturedAtMs: performance.now() });
      const image = pngPixels(bytes);
      Object.assign(entry, { width: image.width, height: image.height, rgbaSha256: sha(image.rgba), auditAfter: await audit(), layersAfter: await heldLayers(), apiAfter: heldFacts(await state()) });
      await writeFile(join(output, "paused-captures.json"), JSON.stringify(report.pausedDraw, null, 2) + "\n");
      return { entry, image };
    }
    const baseline = await capture("baseline");
    for (const fps of [30, 60]) {
      await page.locator("#screen-fps").selectOption(String(fps)); await page.locator("#screen-fps").evaluate((node) => node.blur());
      const requests = traffic.stateStarts.length, start = performance.now(); await sleep(1400);
      const measuredWallMs = performance.now() - start, actual = await capture(String(fps));
      const difference = pixelDifference(baseline.image, actual.image);
      windows.push({ fps, requestedHoldMs: 1400, measuredWallMs, stateRequests: traffic.stateStarts.length - requests, difference });
      await writeFile(join(output, "paused-captures.json"), JSON.stringify(report.pausedDraw, null, 2) + "\n");
    }
    // Retain all three original captures before checking identity, even when
    // the first hold mismatches. A mismatch remains sticky and fails the gate.
    for (const entry of captures) {
      assert.deepEqual(entry.apiBefore, viewBefore); assert.deepEqual(entry.apiAfter, viewBefore);
      for (const value of [entry.auditBefore, entry.auditAfter]) {
        assert.deepEqual(value.camera, baseline.entry.auditAfter.camera);
        assert.deepEqual(value.viewport, baseline.entry.auditAfter.viewport);
        for (const key of ["mode", "requestedMode", "revision", "drawnRevision", "drawnTick"]) assert.deepEqual(value[key], baseline.entry.auditAfter[key]);
      }
      assert.deepEqual(entry.layersBefore, baseline.entry.layersAfter); assert.deepEqual(entry.layersAfter, baseline.entry.layersAfter);
    }
    for (const { fps, difference } of windows) assert.equal(difference.equal, true, `Paused ${fps} exact whole-region RGBA mismatch: ${JSON.stringify(difference)}`);
    assert.ok(windows.every((w) => w.stateRequests >= 1 && w.stateRequests <= 3) && Math.abs(windows[0].stateRequests - windows[1].stateRequests) <= 1);
    assert.equal(traffic.maxState, 1); assert.equal(traffic.posts.length, viewPosts);
  });
  await check("Bounded actual Steps reach coincident daughters; both exact IDs are selectable and camera revision invalidates candidates", async () => {
    assert.equal(snapshot.summary.divisions, 0); const deadline = Date.now() + limits.division; let event, selectedParent, steps = 0;
    while (steps < 128 && snapshot.tick < 128 && Date.now() < deadline && !event) { selectedParent = [...snapshot.cells].sort((a, b) => b.mass_mol / b.division_mass_mol - a.mass_mol / a.division_mass_mol || (BigInt(a.id) < BigInt(b.id) ? -1 : 1))[0]; await search(selectedParent.id); await inspect(selectedParent, snapshot.tick); snapshot = await step(snapshot); steps++; event = snapshot.events.find((e) => e.kind === "division" && e.tick === snapshot.tick && e.parent_id === selectedParent.id); }
    assert.ok(event && snapshot.tick <= 128 && Date.now() <= deadline); assert.ok(!snapshot.cells.some((c) => c.id === event.parent_id)); assert.equal(await page.locator("#selection-state").textContent(), "not present"); const absent = await page.locator("#cell-detail").textContent(); assert.ok(absent.includes(event.parent_id)); assert.doesNotMatch(absent, /\bdead\b|\bdied\b/); const daughters = event.children.map((id) => snapshot.cells.find((c) => c.id === id)); assert.equal(daughters.length, 2); assert.ok(daughters.every(Boolean)); assert.deepEqual(daughters[0].position_m, daughters[1].position_m);
    const g = await geometry(snapshot, "first-real-division"), point = g.points.find((p) => p.id === daughters[0].id); assert.ok(point?.inside); await tap(point); assert.equal(await page.locator("#hit-candidates").isVisible(), true); const ids = await candidateIds(); assert.ok(daughters.every((c) => ids.includes(c.id))); const ordered = event.children.toSorted((a, b) => BigInt(a) < BigInt(b) ? -1 : 1); assert.ok(ids.indexOf(ordered[0]) < ids.indexOf(ordered[1])); for (const daughter of daughters) { await page.locator("#candidate-list").selectOption(daughter.id); await inspect(daughter, snapshot.tick); }
    report.division = { tick: snapshot.tick, realStepCount: steps, parentId: event.parent_id, daughterIds: event.children, position_m: daughters[0].position_m, candidateIds: ids, parentAbsenceIsNotDeath: true }; await writeFile(join(output, "first-division-state.json"), JSON.stringify(snapshot, null, 2) + "\n"); await screenshot("coincident-daughters.png"); const revision = (await audit()).revision; await drag(25, 12); await shown(snapshot); assert.ok((await audit()).revision > revision); assert.equal(await page.locator("#hit-candidates").isVisible(), false); assert.deepEqual(await candidateIds(), []); assert.equal((await state()).tick, snapshot.tick); await page.locator("#camera-reset").click();
    for (const plane of ["xy", "xz", "yz"]) { await page.locator("#projection-plane").selectOption(plane); await tap((await geometry(snapshot, `coincident-${plane}`)).points.find((p) => p.id === daughters[0].id)); assert.ok(daughters.every((c) => (ids.includes(c.id)))); const actual = await candidateIds(); assert.ok(event.children.every((id) => actual.includes(id))); for (const daughter of daughters) { await page.locator("#candidate-list").selectOption(daughter.id); await inspect(daughter, snapshot.tick); } }
  });
  await check("Toggles retain one context and resources only for current population; four viewport layouts show current geometry", async () => {
    const before = heldFacts(await state()), baseline = (await audit()).resources; for (let i = 0; i < 6; i++) { await page.locator("#view-mode").selectOption("2d"); await shown(snapshot, "2d"); assert.equal((await audit()).resources.contextCreations, 1); await page.locator("#view-mode").selectOption("3d"); const current = (await geometry(snapshot, `toggle-${i}`)).audit.resources; for (const key of ["materials", "textures", "geometries", "rendererGeometries", "rendererTextures", "paletteMaterials"]) assert.equal(current[key], baseline[key], `Resource grows on toggle: ${key}`); } assert.deepEqual(heldFacts(await state()), before); await responsive(snapshot); report.resourceToggles = { toggles: 6, contextCreations: (await audit()).resources.contextCreations, currentPopulation: snapshot.cells.length, baseline, resources: (await audit()).resources };
  });
  await check("Actual context-loss negative control falls back to current 2D; inspector and a real Step remain usable", async () => {
    const selected = snapshot.cells[0]; await search(selected.id); await inspect(selected, snapshot.tick); const available = await evaluate(() => { const gl = document.getElementById("chamber-3d").getContext("webgl2"), extension = gl?.getExtension("WEBGL_lose_context"); if (!extension) return false; extension.loseContext(); return true; }); assert.equal(available, true, "Actual WebGL loss extension required for the labelled negative control"); await shown(snapshot, "2d"); assert.match(await page.locator("#view-3d-status").textContent(), /^3D unavailable:.*showing 2D$/); assert.equal((await audit()).resources.contextCreations, 1); await inspect(selected, snapshot.tick); const before = snapshot; snapshot = await step(before, "2d"); const current = snapshot.cells.find((c) => c.id === selected.id); if (current) await inspect(current, snapshot.tick); else assert.equal(await page.locator("#selection-state").textContent(), "not present"); report.contextLoss = { label: "Synthetic GPU-loss negative control via actual native extension; no fabricated model state", current2DTick: snapshot.tick, realStepFrom: before.tick, resources: (await audit()).resources }; await screenshot("context-loss-current-2d.png");
  });
  await pageEnd();
  await check("Explicit unavailable-WebGL negative control retains current 2D and exact SI inspector", async () => { await newPage({ unavailable: true }); await page.locator("#view-mode").selectOption("3d"); await page.waitForFunction(() => document.getElementById("view-3d-status").textContent.startsWith("3D unavailable:")); await shown(snapshot, "2d"); assert.equal((await audit()).resources.contextCreations, 0); assert.equal(await page.locator("#chamber-3d").isVisible(), false); const selected = snapshot.cells[0]; await search(selected.id); await inspect(selected, snapshot.tick); report.unavailable = { label: "Synthetic allocation-negative control: only target canvas WebGL getContext returns null; actual API is unchanged", shownTick: snapshot.tick, contextCreations: 0 }; await screenshot("webgl-unavailable-current-2d.png"); await pageEnd(); });
  await stopHost();
  await check("Real chamber1 keeps schematic 2D without physical controls or loading WebGL vendor", async () => { const legacy = await startHost("legacy", null, false); await newPage(); await shown(legacy, "2d"); assert.equal(await page.locator("#projection-controls").isVisible(), false); assert.equal(await page.locator("#physical-state-note").isVisible(), false); assert.match(await page.locator("#schematic-caption").textContent(), /does not represent physical coordinates/); assert.equal((await audit()).resources.contextCreations, 0); assert.ok(!traffic.resources.some((r) => /cell-viewer-3d|three-r180/.test(r.url))); await search(legacy.cells[0].id); const fields = await inspector(); assert.equal(fields["x center"], undefined); report.legacy = { chamberFormat: legacy.chamber_format, tick: legacy.tick, schematic: true, no3DRequests: true }; await screenshot("legacy-schematic.png"); await pageEnd(); await stopHost(); });
  assert.deepEqual(await readFile(config), original); report.status = "PASS";
}

await rm(output, { recursive: true, force: true }); await mkdir(output, { recursive: true });
try { running = run(); await bounded(running, limits.run, "whole bounded real 3D acceptance"); } catch (error) { fail(error); releaseHistory?.(); releaseModule?.(); if (running) await bounded(running.catch(() => {}), limits.operation + limits.launch, "interrupted settlement").catch((error) => fail(error, "settlement")); }
finally {
  releaseHistory?.(); releaseModule?.(); async function cleanup(name, action, ms = limits.cleanup) { try { return { ok: true, value: await bounded(action(), ms, name) }; } catch (error) { report.cleanupErrors.push({ name, error: error.stack || String(error) }); fail(error, name); return { ok: false }; } }
  if (report.status !== "PASS" && page && !page.isClosed()) await cleanup("failure PNG", () => screenshot("failure.png"));
  if (tracing && context) { const saved = await cleanup("trace publication", async () => { await context.tracing.stop({ path: join(output, "trace.zip") }); const bytes = await readFile(join(output, "trace.zip")); assert.ok(bytes.length); return { bytes: bytes.length, sha256: sha(bytes) }; }, limits.trace); Object.assign(report.trace, saved.ok ? { status: "PASS", ...saved.value } : { status: "FAIL" }); }
  if (context) await cleanup("context cleanup", () => context.close()); if (browser) await cleanup("browser cleanup", () => browser.close()); await cleanup("host cleanup", stopHost, 7000); if (temporary) await cleanup("temporary config/data cleanup", () => rm(temporary, { recursive: true, force: true })); await sleep(50);
  if (report.status === "PASS") try {
    assert.equal(git("rev-parse", "HEAD"), report.sourceHead); assert.equal(git("rev-parse", "HEAD^{tree}"), report.sourceTree); assert.equal(git("status", "--porcelain", "--untracked-files=no"), ""); assert.deepEqual(report.pageErrors, []); assert.deepEqual(report.consoleErrors.filter((e) => !e.expectedNegativeControl), []); assert.equal(report.consoleErrors.filter((e) => e.expectedNegativeControl).length, 1); assert.deepEqual(report.unhandled, []); assert.deepEqual(report.cleanupErrors, []); assert.deepEqual(report.routeErrors || [], []); assert.deepEqual(report.prohibitedRequests || [], []);
    for (const p of report.pages) { assert.equal(p.closed, true); assert.deepEqual(p.failures, []); assert.deepEqual(p.external, []); assert.deepEqual(p.unhandled, []); assert.equal(p.maxState, 1); assert.equal(p.activeState, 0); assert.ok(p.nativeGL.creations <= 1); } assert.equal(report.pages.length, 4); assert.equal(report.pages[0].nativeGL.creations, 1); assert.equal(report.pages[1].nativeGL.creations, 1); assert.equal(report.pages[2].nativeGL.creations, 0); assert.equal(report.pages[3].nativeGL.creations, 0);
    assert.equal(report.checks.length, 13); assert.ok(report.checks.every((c) => c.status === "PASS")); assert.equal(report.oracle.status, "PASS"); assert.equal(report.trace.status, "PASS"); assert.equal(report.sandbox.status, "PASS"); assert.match(report.backend.version, /WebGL 2/i); assert.equal(report.assets.length, 6); assert.equal(report.layouts.length, 4); assert.equal(report.screenshots.length, 9); for (const key of ["atomicStep", "camera", "gestures", "layers", "sliceBoundary", "pausedDraw", "division", "resourceToggles", "contextLoss", "unavailable", "legacy"]) assert.ok(report[key], `Missing mandatory actual evidence: ${key}`); assert.equal(report.delayedHistory.status, "RELEASED"); assert.equal(report.delayedModule.status, "RELEASED");
  } catch (error) { fail(error, "post-cleanup gate"); }
  report.finishedAt = new Date().toISOString(); await writeFile(join(output, "host.log"), hostLog); await writeFile(join(output, "report.json"), JSON.stringify(report, null, 2) + "\n"); console.log(JSON.stringify({ status: report.status, sourceHead: report.sourceHead, checks: report.checks.length, output })); if (report.status !== "PASS") process.exitCode = 1;
}
