// LAB3a: исходник protected browser gate; Node oracle не доказывает browser PASS.
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { createServer } from "node:http";
import { once } from "node:events";
import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), ".."), output = join(root, "target/qa/lab-browser");
const sha = (b) => createHash("sha256").update(b).digest("hex"), git = (...args) => execFileSync("git", args, { cwd: root, encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).trim();
const sourceCommit = "21cbe90732128edee61963544e414d29a7420577", conditions = ["baseline", "mutation_off", "starvation", "oxygen_low", "exchange_half", "founder_k2"], seeds = ["1", "7", "42", "2026"];
const pins = { results: { bytes: 5294742, sha256: "6fd944f6fe2e25ca5418ac357dcb97ce68620afee569b2ecd6dc684c22f7d37a" }, comparisons: { bytes: 1116928, sha256: "e2faeda80c9f47ff23e5aff14879f3780627d867fae51aa655b77d4ad52a8ae3" }, manifest: { bytes: 82880, sha256: "f7a669548650754864a410a46e86593ab722116e0a01057e17f6efc84efcb2f3" } };
const limits = { run: 210_000, operation: 15_000, launch: 20_000, cdp: 5000, cleanup: 5000, trace: 15_000 };
const report = { status: "NOT_RUN", startedAt: new Date().toISOString(), limits, sourceCommit, pins, checks: [], sources: [], serverRequests: [], pages: [], screenshots: [], pageErrors: [], consoleErrors: [], nodeUnhandled: [], cleanupErrors: [], sandbox: { status: "NOT_RUN" }, trace: { status: "NOT_RUN" }, qualifications: ["Original saved aggregate JSON only; no model replay, new experiments/comparisons, generated cells, positions or full genomes.", "Source producer world30/chamber1/dt30 remains separate from the current delivery HEAD/tree.", "Exact integer comparisons use BigInt; mol/J plot values are derived exported displays, not an independent per-tick ledger proof.", "Four Chromium viewport sizes and keyboard/select/history controls; no native touch/full accessibility/achieved FPS or kernel-isolation attestation.", "An explicitly labelled numeric-exponent spelling integrity negative control changes one transport byte only, preserving all JSON observations."] };
report.workflowRun = process.env.GITHUB_RUN_ID ? `${process.env.GITHUB_SERVER_URL || "https://github.com"}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}` : null; report.runner = { node: process.version, os: process.env.RUNNER_OS || process.platform, image: process.env.ImageOS || null };
let browser, context, page, server, origin, tracing = false, stopped = false, running, data, descriptor, savedComparisons;
const assets = new Map(), raw = {};
const sleep = (ms) => new Promise((done) => setTimeout(done, ms));
function fail(error, stage = "run") { stopped = true; report.status = "FAIL"; process.exitCode = 1; (report.failures ||= []).push({ stage, error: error.stack || String(error) }); }
process.on("unhandledRejection", (e) => { report.nodeUnhandled.push(e?.stack || String(e)); fail(e instanceof Error ? e : new Error(String(e)), "Node unhandled rejection"); });
async function bounded(operation, ms, label) { let timer; try { return await Promise.race([operation, new Promise((_, reject) => { timer = setTimeout(() => reject(new Error(`Timed out: ${label}`)), ms); })]); } finally { clearTimeout(timer); } }
async function check(name, operation) { assert.equal(stopped, false); const start = performance.now(); try { await operation(); report.checks.push({ name, status: "PASS", elapsedMs: performance.now() - start }); } catch (e) { report.checks.push({ name, status: "FAIL", error: e.stack || String(e) }); throw e; } }
async function eventually(predicate, label) { const end = Date.now() + limits.operation; while (Date.now() < end) { assert.equal(stopped, false); if (await predicate()) return; await sleep(30); } throw new Error(`Timed out: ${label}`); }
async function evaluate(...args) { return bounded(page.evaluate(...args), limits.operation, "browser evaluation"); }

// Независимый oracle читает raw runner samples, не импортирует product lab-data.
function integer(value) { if (typeof value === "number") { assert.ok(Number.isSafeInteger(value)); return BigInt(value); } assert.ok(typeof value === "string" && /^(?:0|-?[1-9][0-9]{0,127})$/.test(value)); return BigInt(value); }
function exactDelta(condition, baseline) { return (integer(condition) - integer(baseline)).toString(); }
function run(condition, seed) { const matches = data.runs.filter((r) => r.condition === condition && r.seed === seed); assert.equal(matches.length, 1); return matches[0]; }
function sample(r, tick) { return r.samples.find((s) => s.tick === tick) || null; }
function paired(condition, tick, runs = data.runs) {
  return seeds.map((seed) => { const a = runs.find((r) => r.condition === condition && r.seed === seed), b = runs.find((r) => r.condition === "baseline" && r.seed === seed); assert.ok(a && b); assert.deepEqual(a.identity.matter_scales.find((m) => m.id === "BIO"), b.identity.matter_scales.find((m) => m.id === "BIO")); const actual = sample(a, tick), baseline = sample(b, tick); return { seed, tick, available: !!actual && !!baseline, delta: actual && baseline ? { living: exactDelta(actual.living_cells, baseline.living_cells), fissions: exactDelta(actual.lifecycle.fissions, baseline.lifecycle.fissions), deaths: exactDelta(actual.lifecycle.deaths, baseline.lifecycle.deaths), structural_mass_units: exactDelta(actual.structural_mass_units, baseline.structural_mass_units), growth_extent: exactDelta(actual.accounting.growth_extent, baseline.accounting.growth_extent) } : null }; });
}
function range(pairs, metric) { const values = pairs.filter((p) => p.available).map((p) => integer(p.delta[metric])); if (!values.length) return { available: 0, minimum: null, maximum: null, span: null }; const minimum = values.reduce((a, b) => a < b ? a : b), maximum = values.reduce((a, b) => a > b ? a : b); return { available: values.length, minimum: minimum.toString(), maximum: maximum.toString(), span: (maximum - minimum).toString() }; }
function value(s, metric) { if (metric === "living_cells") return s.living_cells; if (metric === "structural_mass_mol") return s.structural_mass_mol; return s.matter.find((m) => m.id === (metric === "food_free_mol" ? "FOOD" : "O2")).free_mol; }
export function oracleCheck() {
  assert.equal(exactDelta("9007199254740993", "9007199254740992"), "1"); assert.equal(exactDelta("-170141183460469231731687303715884105728", "170141183460469231731687303715884105727"), "-340282366920938463463374607431768211455"); assert.throws(() => integer(9007199254740992)); assert.throws(() => integer("01")); assert.deepEqual(range([], "living"), { available: 0, minimum: null, maximum: null, span: null }); assert.deepEqual(range([{ available: true, delta: { living: "-3" } }, { available: true, delta: { living: "9" } }], "living"), { available: 2, minimum: "-3", maximum: "9", span: "12" });
  return { status: "PASS", kind: "Synthetic arithmetic/unknown-value controls, not biological observations", cases: 6 };
}
function rawOracle() {
  assert.equal(data.source_commit, sourceCommit); assert.equal(data.runs.length, 24); assert.equal(data.runs.reduce((n, r) => n + r.samples.length, 0), 4044);
  for (const c of conditions) for (const seed of seeds) { const r = run(c, seed); assert.equal(r.identity.world_format_version, 30); assert.equal(r.identity.chamber_format, 1); assert.equal(r.identity.dt_seconds, 30); assert.equal(r.samples.at(-1).tick, r.checked_ticks); assert.equal(r.checked_ticks, c === "starvation" ? 454 : 20000); assert.equal(r.samples.length, c === "starvation" ? 6 : 201); }
  const comparisons = savedComparisons ||= JSON.parse(raw.comparisons), metrics = { living: "living_cells", fissions: "fissions", deaths: "deaths", structural_mass_units: "structural_mass_units", growth_extent: "growth_extent" }; let checkedPairs = 0;
  for (const landmark of comparisons.landmark_comparisons) { const expected = paired(landmark.condition, landmark.tick); assert.equal(landmark.available_pairs, expected.filter((p) => p.available).length); assert.equal(landmark.expected_pairs, 4); for (const pair of expected) { const saved = landmark.pairs.find((p) => p.seed === pair.seed); assert.equal(saved.available, pair.available); if (!pair.available) assert.equal(saved.delta, null); else for (const [key, metric] of Object.entries(metrics)) assert.equal(integer(saved.delta[metric]).toString(), pair.delta[key]); checkedPairs++; } }
  for (const latest of comparisons.latest_common_samples) { const condition = run(latest.condition, latest.seed), baseline = run("baseline", latest.seed), ticks = condition.samples.filter((s) => sample(baseline, s.tick)); assert.equal(latest.tick, ticks.at(-1).tick); assert.equal(latest.tick, latest.condition === "starvation" ? 400 : 20000); const expected = paired(latest.condition, latest.tick).find((p) => p.seed === latest.seed); for (const [key, metric] of Object.entries(metrics)) assert.equal(integer(latest.delta[metric]).toString(), expected.delta[key]); checkedPairs++; }
  assert.deepEqual(range(paired("starvation", 500), "living"), { available: 0, minimum: null, maximum: null, span: null }); assert.equal(run("starvation", "1").samples.at(-1).tick, 454); assert.equal(sample(run("starvation", "1"), 500), null); const divergent = sample(run("baseline", "1"), 1800); assert.equal(Object.keys(divergent.allele_histogram).length, 2); assert.equal(divergent.observed_allele_richness, 3);
  for (const [condition, section, key, expected] of [["baseline", "initial.concentration", "FOOD", 10], ["mutation_off", "genome", "mutation_probability", 0], ["starvation", "medium.concentration", "FOOD", 0], ["oxygen_low", "initial.concentration", "O2", .05], ["exchange_half", "chamber", "medium_exchange_per_s", 1e-6], ["founder_k2", "founder.genome", "kinetics", 2]]) assert.equal(declared(condition, section, key), expected);
  return { status: "PASS", scope: "Static exact-integer differences/missing pairs over exported samples; no browser/model/ledger recomputation", checkedPairs, runs: 24, samples: 4044 };
}
function integrityTransport(original) {
  assert.equal(original.length, pins.results.bytes); assert.equal(sha(original), pins.results.sha256);
  const field = "runs[0].identity.volume_m3", token = "1e-12", tokenOffset = 5495, byteOffset = 5496;
  assert.equal(original.subarray(tokenOffset - 12, tokenOffset + token.length).toString("utf8"), '"volume_m3":1e-12'); assert.equal(original[byteOffset], 0x65); assert.equal(JSON.parse(original).runs[0].identity.volume_m3, 1e-12);
  const bytes = Buffer.from(original); bytes[byteOffset] = 0x45; assert.equal(bytes.length, original.length); assert.equal(bytes[byteOffset], 0x45); assert.deepEqual(JSON.parse(bytes), JSON.parse(original)); assert.notEqual(sha(bytes), sha(original)); assert.equal(sha(bytes), "58407c180b65782bafeeacef46dede6ced435ef2bb1f1ca0c79624f4dc313f2e");
  return { bytes, receipt: { label: "Transport-only single numeric exponent e→E spelling; same length and all parsed binary64/string/structural values; no model changes", field, originalToken: token, modifiedToken: "1E-12", tokenOffset, byteOffset, originalByte: 0x65, deliveredByte: 0x45, originalSha256: sha(original), deliveredSha256: sha(bytes), bytes: bytes.length } };
}
async function source(filename) { const bytes = await readFile(join(root, filename)); assert.deepEqual(bytes, execFileSync("git", ["show", `HEAD:${filename}`], { cwd: root, maxBuffer: 16 * 1024 * 1024 })); report.sources.push({ filename, bytes: bytes.length, sha256: sha(bytes) }); return bytes; }
async function prepare() {
  for (const [name, pin] of Object.entries(pins)) { const bytes = await source(`site/data/lab-2/${name}.json`); assert.equal(bytes.length, pin.bytes); assert.equal(sha(bytes), pin.sha256); assert.deepEqual(bytes, await source(`docs/experiments/lab-2/${name}.json`)); raw[name] = bytes; assets.set(`/data/lab-2/${name}.json`, { bytes, mime: "application/json" }); }
  const descriptorBytes = await source("site/data/lab-2/descriptor.json"); assert.equal(descriptorBytes.length, 50708); assert.equal(sha(descriptorBytes), "457d0d92616472f4007539bb9b92d755057f7b7eb536493ddda90c77daef26bb"); data = JSON.parse(raw.results); descriptor = JSON.parse(descriptorBytes); assert.equal(data.source_commit, sourceCommit); assert.equal(descriptor.source.source_commit, sourceCommit); assert.equal(descriptor.source.world_format_version, 30); assert.equal(descriptor.source.chamber_format, 1); assert.equal(descriptor.source.dt_seconds, 30); assert.equal(descriptor.source.provenance.build_attestation, false); assert.equal(descriptor.delivery.numerical_recalculation, false); assert.equal(descriptor.delivery.total_raw_bytes, 6494550); assert.deepEqual(descriptor.matrix.seeds, seeds); assert.deepEqual(descriptor.matrix.conditions, conditions); assert.equal(descriptor.capabilities.aggregate_samples, true); for (const key of ["individual_cells", "spatial_positions", "full_genomes", "resumable_states", "event_reconstruction"]) assert.equal(descriptor.capabilities[key], false); assert.equal(data.runs.length, 24); assert.equal(data.runs.reduce((n, r) => n + r.samples.length, 0), 4044);
  for (const [name, pin] of Object.entries(pins)) { assert.equal(descriptor.files[name].url, `./data/lab-2/${name}.json`); assert.equal(descriptor.files[name].bytes, pin.bytes); assert.equal(descriptor.files[name].sha256, pin.sha256); }
  report.rawArithmetic = rawOracle(); report.batchObservationOracle = batchObservationCheck(); report.integrityControlSource = integrityTransport(raw.results).receipt;
  const types = { "lab.html": "text/html", "lab.js": "text/javascript", "lab.css": "text/css", "lab-data.mjs": "text/javascript", "data/lab-2/descriptor.json": "application/json" }; for (const [name, mime] of Object.entries(types)) assets.set(`/${name}`, { bytes: await source(`site/${name}`), mime });
  report.dataIdentity = { bytes: 6494550, runs: 24, samples: 4044, producer: descriptor.source, capabilities: descriptor.capabilities, descriptorSha256: sha(assets.get("/data/lab-2/descriptor.json").bytes) }; report.oracle = oracleCheck();
}
async function startServer() {
  server = createServer((request, response) => { const url = new URL(request.url, "http://127.0.0.1"), asset = assets.get(url.pathname), record = { method: request.method, path: url.pathname, time: Date.now() }; report.serverRequests.push(record); if (request.method !== "GET" || !asset) { record.status = 404; response.writeHead(404); response.end("Unknown QA route"); return; } record.status = 200; record.bytes = asset.bytes.length; record.sha256 = sha(asset.bytes); response.writeHead(200, { "content-type": asset.mime, "content-length": asset.bytes.length, "cache-control": "no-store" }); response.end(asset.bytes); }); server.listen(0, "127.0.0.1"); await bounded(once(server, "listening"), limits.cdp, "loopback server listen"); origin = `http://127.0.0.1:${server.address().port}`; report.origin = origin;
}
async function newPage(url = "", negative = false) {
  assert.equal(stopped, false);
  page = await bounded(context.newPage(), limits.operation, "browser page"); const pending = new Set(), observations = { url, negative, requests: [], failed: [], external: [], responses: [], responseErrors: [], closed: false, pending }; report.pages.push(observations);
  page.on("request", (request) => { observations.requests.push({ method: request.method(), url: request.url() }); if (new URL(request.url()).origin !== origin) observations.external.push(request.url()); }); page.on("requestfailed", (request) => observations.failed.push({ url: request.url(), error: request.failure()?.errorText })); page.on("pageerror", (e) => report.pageErrors.push(e.stack || String(e))); page.on("console", (m) => { if (m.type() === "error") report.consoleErrors.push({ text: m.text(), location: m.location(), negative }); });
  page.on("response", (response) => { const path = new URL(response.url()).pathname, expected = assets.get(path); if (!expected) return; const task = (async () => { assert.ok(pending.size < 16); const bytes = await bounded(response.body(), limits.operation, "actual browser response bytes"), entry = { path, status: response.status(), bytes: bytes.length, sha256: sha(bytes), contentType: response.headers()["content-type"] }; observations.responses.push(entry); assert.equal(entry.status, 200); assert.equal(entry.bytes, expected.bytes.length); assert.equal(entry.sha256, negative && path === "/data/lab-2/results.json" ? report.integrityNegative.deliveredSha256 : sha(expected.bytes)); })().catch((e) => observations.responseErrors.push(e.stack || String(e))).finally(() => pending.delete(task)); pending.add(task); });
  await page.addInitScript(() => { window.__labQaUnhandled = []; addEventListener("unhandledrejection", (e) => window.__labQaUnhandled.push(String(e.reason?.stack || e.reason))); });
  if (negative) await page.route(origin + "/data/lab-2/results.json", async (route) => { try { const response = await route.fetch({ timeout: limits.operation }), original = await response.body(); assert.deepEqual(original, raw.results); const { bytes, receipt } = integrityTransport(original); assert.deepEqual(JSON.parse(bytes), data); report.integrityNegative = receipt; await route.fulfill({ response, body: bytes }); } catch (error) { (report.routeErrors ||= []).push(error.stack || String(error)); await route.abort().catch((error) => (report.routeErrors ||= []).push(String(error))); } });
  await page.goto(origin + "/lab.html" + url, { waitUntil: "domcontentloaded" }); return observations;
}
async function drainResponses(observations) { await bounded((async () => { while (observations.pending.size) await Promise.all([...observations.pending]); })(), limits.operation, "response observation settlement before navigation/closure"); assert.deepEqual(observations.responseErrors, []); assert.deepEqual(observations.failed, []); }
async function closePage(observations) { await drainResponses(observations); observations.unhandled = await evaluate(() => window.__labQaUnhandled); assert.deepEqual(observations.unhandled, []); await page.close(); observations.closed = true; page = null; }
async function screenshot(filename) { const bytes = await bounded(page.screenshot({ path: join(output, filename), fullPage: true }), limits.operation, "actual full-page PNG"); report.screenshots.push({ filename, bytes: bytes.length, sha256: sha(bytes) }); }
async function ready() { await page.waitForFunction(() => { const plots = document.getElementById("plots"), svg = [...plots.querySelectorAll(".metric-plot")]; return !document.getElementById("lab-workspace").hidden && document.getElementById("lab-workspace").getAttribute("aria-busy") === "false" && document.getElementById("lab-error").hidden && !document.getElementById("condition-select").disabled && plots.dataset.layout === "ready" && plots.getAttribute("aria-busy") === "false" && svg.length === 4 && svg.every((n) => getComputedStyle(n).visibility === "visible" && n.getBoundingClientRect().width > 96); }); }
async function fields(selector) { return page.locator(`${selector} [data-field]`).evaluateAll((nodes) => Object.fromEntries(nodes.map((n) => [n.dataset.field, n.textContent]))); }
async function field(selector, key, expected) { const node = page.locator(`${selector} [data-field="${key}"]`); assert.equal(await node.getAttribute("data-value"), expected === null ? "null" : String(expected)); const text = (await node.textContent()).replaceAll(",", ""); if (expected === null) assert.match(text, /unknown|unavailable/); else if (typeof expected === "number") { const actual = Number(text); assert.ok(Number.isFinite(actual) && Math.abs(actual - expected) <= Math.abs(expected) * 1e-6 + Number.MIN_VALUE, `Visible field ${key}: ${text}/${expected}`); } else assert.equal(text, String(expected).replaceAll(",", "")); }
function fieldIndex(records) { const result = Object.fromEntries(records.map((r) => [r.field, r])); assert.equal(Object.keys(result).length, records.length, "No duplicate DOM field may be hidden by batching"); return result; }
function observedField(records, key, expected) { const node = records[key]; assert.ok(node, `Missing actual DOM field ${key}`); assert.equal(node.value, expected === null ? "null" : String(expected)); const text = node.text.replaceAll(",", ""); if (expected === null) assert.match(text, /unknown|unavailable/); else if (typeof expected === "number") { const actual = Number(text); assert.ok(Number.isFinite(actual) && Math.abs(actual - expected) <= Math.abs(expected) * 1e-6 + Number.MIN_VALUE, `Visible field ${key}: ${text}/${expected}`); } else assert.equal(text, String(expected).replaceAll(",", "")); }
function batchObservationCheck() {
  // Synthetic error-channel controls, not model samples or browser evidence.
  const exact = { field: "counter", value: "9007199254740993", text: "9007199254740993" }; observedField(fieldIndex([exact]), "counter", exact.value);
  assert.throws(() => fieldIndex([exact, exact])); assert.throws(() => observedField({}, "counter", exact.value));
  assert.throws(() => observedField(fieldIndex([{ ...exact, text: "9007199254740992" }]), "counter", exact.value));
  observedField(fieldIndex([{ field: "unknown", value: "null", text: "unknown · genesis" }]), "unknown", null);
  assert.throws(() => observedField(fieldIndex([{ field: "unknown", value: "null", text: "0" }]), "unknown", null));
  return { status: "PASS", kind: "Synthetic batched observation precision/duplicate/missing/null controls; not biology or browser", cases: 6 };
}
async function detail(condition, seed, tick) {
  const r = run(condition, seed), s = sample(r, tick); assert.ok(s);
  await page.waitForFunction(({ runId, tick }) => { const stamp = document.getElementById("sample-stamp"); return stamp.dataset.runId === runId && stamp.dataset.tick === String(tick); }, { runId: r.run_id, tick });
  // One atomic actual-DOM read; all expected arithmetic remains independent Node raw math.
  const ratios = Object.fromEntries(Object.entries(s.allele_histogram).map(([allele, count]) => [allele, count / s.living_cells * 100]));
  const shown = await evaluate((expected) => {
    const fields = (id) => [...document.querySelectorAll(`#${id} [data-field]`)].map((n) => ({ field: n.dataset.field, value: n.dataset.value, text: n.textContent, label: n.previousElementSibling.textContent }));
    return { runId: document.getElementById("sample-stamp").dataset.runId, tick: document.getElementById("sample-stamp").dataset.tick, detail: fields("run-detail"), exact: fields("exact-counters"), environment: fields("environment"), living: document.getElementById("living-alleles").dataset.count, richness: document.getElementById("allele-history").dataset.richness, historyText: document.getElementById("allele-history").textContent,
      histogram: [...document.querySelectorAll("#allele-histogram .hist-row")].map((row) => { const allele = row.dataset.allele, reference = document.createElement("div"); reference.style.width = `${expected[allele]}%`; return { allele, count: Number(row.dataset.count), text: row.lastElementChild.textContent, rawRatioPercent: expected[allele], cssWidth: row.querySelector(".hist-fill").style.width, referenceCssWidth: reference.style.width }; }) };
  }, ratios);
  assert.equal(shown.runId, r.run_id); assert.equal(shown.tick, String(tick)); const details = fieldIndex(shown.detail), exact = fieldIndex(shown.exact);
  for (const [key, expected] of Object.entries({ run_id: r.run_id, seed, tick, time_seconds: s.time_seconds, living_cells: s.living_cells, structural_mass_mol: s.structural_mass_mol, food_free_mol: value(s, "food_free_mol"), oxygen_free_mol: value(s, "oxygen_free_mol"), status: r.status, stop_reason: r.stop_reason, terminal_tick: r.checked_ticks, requested_steps: r.requested_steps, sample_count: r.samples.length, peak_cells: s.peak_cells, max_generation_observed: s.max_generation_observed })) observedField(details, key, expected);
  for (const [key, expected] of Object.entries({ ...s.lifecycle, ...s.accounting, structural_mass_units: s.structural_mass_units, internal_energy_units: s.internal_energy_units, bath_heat_units: s.bath_heat_units, energy_units_per_joule: r.identity.energy_units_per_joule })) if (typeof expected === "string") observedField(exact, key, expected);
  for (let i = 0; i < s.accounting.medium_matter_units.length; i++) observedField(exact, `medium_matter_${s.matter[i].id}`, s.accounting.medium_matter_units[i]); observedField(exact, "ledger_checked_ticks", s.ledger.checked_ticks); observedField(exact, "energy_residual", s.ledger.energy_residual_last_checked); observedField(exact, "matter_residual", s.ledger.matter_residual_last_checked === null ? null : s.ledger.matter_residual_last_checked.join(", "));
  const histogram = shown.histogram; assert.deepEqual(Object.fromEntries(histogram.map((row) => [row.allele, row.count])), s.allele_histogram); assert.equal(histogram.length, Object.keys(s.allele_histogram).length);
  for (const row of histogram) { assert.equal(row.text, String(row.count)); assert.ok(Number.isFinite(row.rawRatioPercent) && row.referenceCssWidth.endsWith("%")); assert.equal(row.cssWidth, row.referenceCssWidth, "Living allele histogram exact CSSOM width from independent raw counts"); }
  (report.histogramDeclarations ||= []).push({ runId: r.run_id, tick, living: s.living_cells, rows: histogram, scope: "Exact CSSOM declaration serialization; not bar pixel geometry" });
  assert.equal(shown.living, String(Object.keys(s.allele_histogram).length)); assert.equal(shown.richness, String(s.observed_allele_richness)); assert.match(shown.historyText, /Historical.*richness/);
  (report.samples ||= []).push({ runId: r.run_id, tick, living: s.living_cells, currentAlleles: Object.keys(s.allele_histogram).length, historicalRichness: s.observed_allele_richness, exactCounters: "MATCHED_ORIGINAL_STRINGS", observation: "One atomic actual DOM snapshot; unchanged independent Node assertions" }); return shown;
}
function declared(condition, section, key) { const toml = JSON.parse(raw.manifest).runs.find((r) => r.condition === condition).scenario_toml, escaped = section.replaceAll(".", "\\."), block = toml.match(new RegExp(`^\\[${escaped}\\]\\n([\\s\\S]*?)(?=^\\[|$(?![\\s\\S]))`, "m")); assert.ok(block, section); const number = block[1].match(new RegExp(`^${key} = ([0-9.e+\\-]+)$`, "m")); assert.ok(number, `${section}.${key}`); return Number(number[1]); }
async function environment(condition, shown) {
  const actual = fieldIndex(shown.environment), details = fieldIndex(shown.detail);
  for (const [fieldName, section, key] of [["volume_m3", "chamber", "volume_m3"], ["temperature_k", "chamber", "temperature_k"], ["medium_exchange_per_s", "chamber", "medium_exchange_per_s"], ["mutation_probability", "genome", "mutation_probability"], ["founder_kinetics", "founder.genome", "kinetics"], ...["initial", "medium"].flatMap((arm) => ["FOOD", "O2"].map((substance) => [`${arm}_${substance}`, `${arm}.concentration`, substance]))]) { observedField(actual, fieldName, declared(condition, section, key)); if (/_(FOOD|O2)$/.test(fieldName)) assert.match(actual[fieldName].label, /mol\/m³/); }
  assert.match(details.food_free_mol.label, /mol$/); assert.match(details.structural_mass_mol.label, /mol$/);
}
async function select(condition, seed, tick) {
  const current = () => evaluate(() => ({ condition: document.getElementById("condition-select").value, seed: document.getElementById("seed-select").value, tick: document.getElementById("sample-select").value }));
  let shown = await current(); if (shown.condition !== condition) { await page.locator("#condition-select").selectOption(condition); shown = await current(); }
  if (shown.seed !== seed) { await page.locator("#seed-select").selectOption(seed); shown = await current(); }
  if (shown.tick !== String(tick)) await page.locator("#sample-select").selectOption(String(tick)); await ready();
}
function closeNumber(actual, expected, label, tolerance = .01) { assert.ok(Number.isFinite(actual) && Number.isFinite(expected) && Math.abs(actual - expected) <= tolerance, `${label}: ${actual}/${expected}`); }
async function curves(condition, label) {
  await page.waitForFunction(() => { const host = document.getElementById("plots"), plots = [...host.querySelectorAll(".metric-plot")]; return host.dataset.layout === "ready" && host.getAttribute("aria-busy") === "false" && plots.length === 4 && plots.every((svg) => getComputedStyle(svg).visibility === "visible" && svg.getBoundingClientRect().width > 96 && Math.abs(svg.viewBox.baseVal.width - svg.getBoundingClientRect().width) <= .02); });
  const shown = await evaluate(() => ({ seed: document.getElementById("seed-select").value, window: Number(document.getElementById("plot-window").value), plots: [...document.querySelectorAll("#plots .metric-plot")].map((svg) => ({ metric: svg.dataset.metric, viewBox: [svg.viewBox.baseVal.x, svg.viewBox.baseVal.y, svg.viewBox.baseVal.width, svg.viewBox.baseVal.height], cssWidth: svg.getBoundingClientRect().width, cssHeight: svg.getBoundingClientRect().height, frame: Object.fromEntries(["x0", "x1", "y0", "y1"].map((key) => [key, Number(svg.dataset[key])])), xMax: Number(svg.dataset.xMax), yMax: Number(svg.dataset.yMax), paths: [...svg.querySelectorAll("path[data-condition]")].map((p) => ({ condition: p.dataset.condition, seed: p.dataset.seed, metric: p.dataset.metric, lastTick: Number(p.dataset.lastTick), count: Number(p.dataset.sampleCount), d: p.getAttribute("d"), opacity: Number(p.getAttribute("opacity")), width: Number(p.getAttribute("stroke-width")), dash: p.getAttribute("stroke-dasharray"), stroke: p.getAttribute("stroke") })), dots: [...svg.querySelectorAll("circle[data-condition]")].map((p) => ({ condition: p.dataset.condition, seed: p.dataset.seed, tick: Number(p.dataset.tick), cx: Number(p.getAttribute("cx")), cy: Number(p.getAttribute("cy")), radius: Number(p.getAttribute("r")), opacity: Number(p.getAttribute("opacity")) })) })) }));
  assert.equal(shown.plots.length, 4); const arms = condition === "baseline" ? ["baseline"] : ["baseline", condition]; const expectedRuns = arms.flatMap((arm) => seeds.map((seed) => run(arm, seed))); const observations = [];
  assert.deepEqual(shown.plots.map((p) => p.metric), ["living_cells", "structural_mass_mol", "food_free_mol", "oxygen_free_mol"]);
  for (const plot of shown.plots) { assert.deepEqual(plot.viewBox.slice(0, 2), [0, 0]); assert.equal(plot.viewBox[3], 210); closeNumber(plot.viewBox[2], plot.cssWidth, "Actual plot one SVG unit per CSS px", .02); assert.equal(plot.cssHeight, 210); assert.deepEqual(plot.frame, { x0: 72, x1: plot.viewBox[2] - 12, y0: 12, y1: 178 }); const expectedX = (time) => 72 + time / plot.xMax * (plot.viewBox[2] - 84), expectedY = (amount) => 178 - amount / plot.yMax * 166; assert.equal(plot.xMax, shown.window * 30); const maximum = Math.max(...expectedRuns.flatMap((r) => r.samples.filter((s) => s.tick <= shown.window).map((s) => value(s, plot.metric)))); assert.equal(plot.yMax, maximum || 1); assert.equal(plot.paths.length, expectedRuns.length);
    for (const r of expectedRuns) { const points = r.samples.filter((s) => s.tick <= shown.window), matches = plot.paths.filter((p) => p.condition === r.condition && p.seed === r.seed); assert.equal(matches.length, 1); const path = matches[0]; assert.equal(path.metric, plot.metric); assert.equal(path.lastTick, points.at(-1).tick); assert.equal(path.count, points.length); assert.match(path.d, /^M/); assert.equal((path.d.match(/M/g) || []).length, 1); assert.equal((path.d.match(/L/g) || []).length, points.length - 1); assert.doesNotMatch(path.d, /[CQASTHZcqastzhz]/); assert.equal(path.opacity, r.seed === shown.seed ? 1 : .6); assert.equal(path.width, r.seed === shown.seed ? 2 : 1); assert.equal(path.dash, condition !== "baseline" && r.condition === "baseline" ? "5 4" : "none"); assert.match(path.stroke, /^#[0-9a-f]{6}$/i); const numbers = path.d.match(/-?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?/gi).map(Number); assert.equal(numbers.length, points.length * 2); for (let i = 0; i < points.length; i++) { closeNumber(numbers[i * 2], expectedX(points[i].time_seconds), "Independent actual observation SVG x", .00001); closeNumber(numbers[i * 2 + 1], expectedY(value(points[i], plot.metric)), "Independent actual observation SVG y", .00001); }
      const dots = plot.dots.filter((p) => p.condition === r.condition && p.seed === r.seed); assert.equal(dots.length, points.length); for (let i = 0; i < points.length; i++) { assert.equal(dots[i].tick, points[i].tick); assert.equal(dots[i].radius, r.seed === shown.seed ? 1.8 : 1.1); assert.equal(dots[i].opacity, r.seed === shown.seed ? 1 : .5); closeNumber(dots[i].cx, expectedX(points[i].time_seconds), "Actual SVG observation dot x", .00001); closeNumber(dots[i].cy, expectedY(value(points[i], plot.metric)), "Actual SVG observation dot y", .00001); }
      observations.push({ metric: plot.metric, condition: r.condition, seed: r.seed, actualSampleCount: points.length, actualLastTick: points.at(-1).tick, actualPathSha256: sha(path.d) });
    }
  }
  (report.curves ||= []).push({ label, window: shown.window, independentRawToActualSVG: true, observations });
}
async function typography(label) {
  const condition = await page.locator("#condition-select").inputValue(), window = Number(await page.locator("#plot-window").inputValue());
  const originalRuns = (condition === "baseline" ? ["baseline"] : ["baseline", condition]).flatMap((arm) => seeds.map((seed) => run(arm, seed)));
  const plots = await evaluate(() => [...document.querySelectorAll("#plots .metric-plot")].map((svg) => {
    const rect = svg.getBoundingClientRect();
    return { metric: svg.dataset.metric, rect: rect.toJSON(), labels: [...svg.querySelectorAll("text.axis-label")].map((node) => {
      const matrix = node.getScreenCTM(), font = parseFloat(getComputedStyle(node).fontSize);
      return { axis: node.dataset.axis, value: Number(node.dataset.value), text: node.textContent, rect: node.getBoundingClientRect().toJSON(), declaredFont: font, effectiveFontCSS: matrix ? font * Math.hypot(matrix.c, matrix.d) : null };
    }) };
  }));
  assert.equal(plots.length, 4);
  for (const plot of plots) {
    assert.equal(plot.labels.length, 6);
    const originalMaximum = Math.max(...originalRuns.flatMap((r) => r.samples.filter((s) => s.tick <= window).map((s) => value(s, plot.metric)))) || 1;
    assert.deepEqual(plot.labels.filter((text) => text.axis === "x").map((text) => text.value), [0, window * 30 / 7200, window * 30 / 3600], "Axis hour values from original sampled model-time domain");
    assert.deepEqual(plot.labels.filter((text) => text.axis === "y").map((text) => text.value), [0, originalMaximum / 2, originalMaximum], "Axis quantities from original displayed observations");
    for (const text of plot.labels) {
      assert.ok(Number.isFinite(text.effectiveFontCSS) && text.effectiveFontCSS >= 10, `${label}/${plot.metric}: actual axis font ${text.effectiveFontCSS}CSSpx`);
      assert.equal(text.declaredFont, 11); assert.ok(text.rect.width > 0 && text.rect.height > 0);
      assert.ok(text.rect.left >= plot.rect.left - .5 && text.rect.right <= plot.rect.right + .5 && text.rect.top >= plot.rect.top - .5 && text.rect.bottom <= plot.rect.bottom + .5, `${label}/${plot.metric}: clipped actual axis label ${text.text}`);
      assert.ok(Number.isFinite(text.value)); assert.equal(Number.parseFloat(text.text), Number(text.value.toPrecision(3)), "Axis-only three-significant-digit display"); if (text.axis === "x") assert.match(text.text, / h$/);
    }
    for (let i = 0; i < plot.labels.length; i++) for (let j = i + 1; j < plot.labels.length; j++) {
      const a = plot.labels[i].rect, b = plot.labels[j].rect;
      assert.ok(a.right <= b.left || b.right <= a.left || a.bottom <= b.top || b.bottom <= a.top, `${label}/${plot.metric}: overlapping actual axis labels`);
    }
  }
  (report.typography ||= []).push({ label, scope: "Observed CSS scale and uncut nonoverlapping label boxes; original data/axis units unchanged", plots });
}
async function comparisons(condition, seed, choice = "latest") {
  const saved = savedComparisons, landmarks = saved.landmark_comparisons.filter((r) => r.condition === condition), latest = saved.latest_common_samples.filter((r) => r.condition === condition);
  if (condition !== "baseline" && await page.locator("#comparison-select").inputValue() !== String(choice)) await page.locator("#comparison-select").selectOption(String(choice));
  const shown = await evaluate(() => ({ condition: document.getElementById("condition-select").value, seed: document.getElementById("seed-select").value, disabled: document.getElementById("comparison-select").disabled, choice: document.getElementById("comparison-select").value, status: { tick: document.getElementById("comparison-status").dataset.tick, kind: document.getElementById("comparison-status").dataset.kind, text: document.getElementById("comparison-status").textContent },
    landmarks: [...document.querySelectorAll("#landmark-summary tbody tr")].map((n) => ({ tick: Number(n.dataset.tick), available: Number(n.dataset.availablePairs), expected: Number(n.dataset.expectedPairs), text: n.textContent })), common: [...document.querySelectorAll("#latest-common-summary tbody tr")].map((n) => ({ seed: n.dataset.seed, tick: Number(n.dataset.tick), terminal: Number(n.children[2].textContent) })),
    pairs: [...document.querySelectorAll("#pair-comparison tbody tr")].map((row) => ({ metric: row.dataset.metric, available: row.dataset.available, cells: [...row.querySelectorAll("td[data-arm]")].map((cell) => ({ arm: cell.dataset.arm, value: cell.dataset.value, min: cell.dataset.min, max: cell.dataset.max, width: cell.dataset.width, count: cell.dataset.count, text: cell.textContent })) })) }));
  assert.equal(shown.condition, condition); assert.equal(shown.seed, seed); const rows = shown.landmarks, common = shown.common; assert.equal(rows.length, condition === "baseline" ? 0 : 7);
  for (const row of rows) { const original = landmarks.find((r) => r.tick === row.tick); assert.ok(original); assert.equal(row.available, original.available_pairs); assert.equal(row.expected, 4); assert.ok(row.text.includes(`${row.available} of 4`)); }
  assert.equal(common.length, condition === "baseline" ? 0 : 4); for (const row of common) { assert.equal(row.tick, latest.find((r) => r.seed === row.seed).tick); assert.equal(row.terminal, run(condition, row.seed).checked_ticks); }
  if (condition === "baseline") { assert.equal(shown.disabled, true); assert.equal(shown.pairs.length, 0); return; }
  assert.equal(shown.disabled, false); assert.equal(shown.choice, String(choice)); const landmark = landmarks.find((r) => String(r.tick) === String(choice)), expected = choice === "latest" ? latest.find((r) => r.seed === seed) : landmark.pairs.find((r) => r.seed === seed); assert.equal(shown.status.tick, String(expected.tick)); assert.equal(shown.status.kind, choice === "latest" ? "latest-common" : "landmark");
  const actual = shown.pairs; assert.equal(actual.length, 9); assert.equal(new Set(actual.map((r) => r.metric)).size, 9);
  for (const row of actual) { assert.equal(row.available, String(expected.available)); const cells = Object.fromEntries(row.cells.map((c) => [c.arm, c])); assert.deepEqual(Object.keys(cells).sort(), ["baseline", "condition_metrics", "delta", "range"]); assert.equal(row.cells.length, 4);
    for (const arm of ["baseline", "condition_metrics", "delta"]) { const original = expected[arm]?.[row.metric] ?? null, cell = cells[arm]; assert.equal(cell.value, original === null ? "null" : String(original)); if (original === null) assert.match(cell.text, /unavailable/); else if (typeof original === "string") assert.equal(cell.text, original); else { const numeric = Number(cell.text.replaceAll(",", "")); assert.ok(Number.isFinite(numeric) && Math.abs(numeric - original) <= Math.abs(original) * 1e-6 + Number.MIN_VALUE); } }
    const originalRange = landmark?.ranges.delta[row.metric], cell = cells.range; for (const [key, attr] of [["min", "min"], ["max", "max"], ["width", "width"], ["count", "count"]]) assert.equal(cell[attr], originalRange?.[key] === null || originalRange?.[key] === undefined ? "null" : String(originalRange[key])); if (originalRange?.count === 0) assert.match(cell.text, /unavailable.*0 of 4/); if (!originalRange) assert.equal(cell.text, "not pooled");
  }
  (report.pairs ||= []).push({ condition, seed, choice, tick: expected.tick, terminalTick: run(condition, seed).checked_ticks, available: expected.available, rowCount: actual.length, landmarks: rows, latestCommon: common, observation: "One atomic actual DOM snapshot; nine pinned published metrics/ranges plus the existing separate five-integer raw oracle" });
}
async function provenance() { for (const [key, expected] of Object.entries({ source_commit: sourceCommit, world_format_version: 30, chamber_format: 1, dt_seconds: 30, build_attestation: "false", descriptor_sha256: report.dataIdentity.descriptorSha256 })) await field("#provenance", key, expected); const links = await page.locator("#source-links a").evaluateAll((nodes) => nodes.map((n) => ({ href: n.href, text: n.textContent, source: n.dataset.source, sha256: n.dataset.sha256 }))); assert.ok(links.some((l) => l.href === `https://github.com/emevart/liminis/tree/${sourceCommit}`)); for (const [name, pin] of Object.entries(pins)) { const link = links.find((l) => l.source === name); assert.ok(link); assert.equal(link.href, `${origin}/data/lab-2/${name}.json`); assert.equal(link.sha256, pin.sha256); assert.ok(!link.href.includes(sourceCommit)); } report.provenanceLinks = links; }
async function postScreenshot(filename) { await ready(); const label = `after-full-page-${filename}`; await curves(await page.locator("#condition-select").inputValue(), label); await typography(label); assert.deepEqual(report.pageErrors, []); assert.deepEqual(report.consoleErrors, []); assert.deepEqual(await evaluate(() => window.__labQaUnhandled), []); (report.postScreenshot ||= []).push({ filename, plots: 4, fullRawSVGOracle: true, typography: true, stickyErrors: 0 }); }
async function layout(filename, width, height) { await page.setViewportSize({ width, height }); await ready(); await curves(await page.locator("#condition-select").inputValue(), `layout-${filename}`); await typography(filename); const bounds = await evaluate(() => ({ documentWidth: document.documentElement.scrollWidth, innerWidth, controls: ["condition-select", "seed-select", "sample-select", "comparison-select", "plot-window"].map((id) => { const rect = document.getElementById(id).getBoundingClientRect(); return { id, left: rect.left, right: rect.right, width: rect.width, height: rect.height }; }), plots: [...document.querySelectorAll(".metric-plot")].map((n) => { const r = n.getBoundingClientRect(); return { width: r.width, height: r.height, left: r.left, right: r.right }; }) })); assert.ok(bounds.documentWidth <= bounds.innerWidth); assert.ok(bounds.controls.every((c) => c.width > 0 && c.height > 0 && c.left >= 0 && c.right <= width + 1)); assert.ok(bounds.plots.every((p) => p.width > 0 && p.height > 0 && p.left >= 0 && p.right <= width + 1)); for (const id of ["condition-select", "seed-select", "sample-select", "comparison-select", "plot-window"]) assert.equal(await page.locator(`#${id}`).isVisible(), true); assert.equal(await page.locator("#lab-error").isVisible(), false); (report.layouts ||= []).push({ filename, width, height, bounds }); await screenshot(filename); await postScreenshot(filename); }
async function fatalVisible(pattern, filename) { await page.waitForFunction(() => !document.getElementById("lab-error").hidden); assert.match(await page.locator("#lab-error").textContent(), pattern); assert.equal(await page.locator("#lab-error").isVisible(), true); assert.equal(await page.locator("#lab-workspace").isVisible(), false); assert.equal(await page.locator("#plots .metric-plot").count(), 0); for (const id of ["condition-select", "seed-select", "sample-select", "comparison-select", "plot-window"]) assert.equal(await page.locator(`#${id}`).isDisabled(), true); await screenshot(filename);
  const after = await evaluate(() => ({ visibleError: !document.getElementById("lab-error").hidden, hiddenWorkspace: document.getElementById("lab-workspace").hidden, charts: document.querySelectorAll("#plots .metric-plot").length, disabled: ["condition-select", "seed-select", "sample-select", "comparison-select", "plot-window"].every((id) => document.getElementById(id).disabled), unhandled: window.__labQaUnhandled })); assert.equal(after.visibleError, true); assert.equal(after.hiddenWorkspace, true); assert.equal(after.charts, 0); assert.equal(after.disabled, true); assert.deepEqual(after.unhandled, []); assert.deepEqual(report.pageErrors, []); assert.deepEqual(report.consoleErrors, []); (report.postScreenshotNegative ||= []).push({ filename, charts: 0, controlsDisabled: true, visibleError: true, stickyErrors: 0 });
}


async function main() {
  report.sourceHead = git("rev-parse", "HEAD"); report.sourceTree = git("rev-parse", "HEAD^{tree}"); assert.equal(report.sourceHead, process.env.LIMINIS_EXPECTED_HEAD); assert.equal(report.sourceTree, process.env.LIMINIS_EXPECTED_TREE); assert.equal(git("status", "--porcelain", "--untracked-files=no"), ""); await source("scripts/check_lab_browser.mjs"); await prepare(); await startServer();
  const require = createRequire(import.meta.url), moduleId = process.env.LIMINIS_PLAYWRIGHT_MODULE; assert.ok(moduleId); const pkg = require(`${moduleId}/package.json`); assert.equal(pkg.name, "playwright"); assert.equal(pkg.version, "1.61.1"); browser = await require(moduleId).chromium.launch({ headless: true, chromiumSandbox: true, args: ["--enable-automation"], timeout: limits.launch }); report.browser = { version: browser.version(), playwright: pkg.version };
  await check("Observed official Chromium sandbox argv with unchanged stock launch", async () => { const session = await bounded(browser.newBrowserCDPSession(), limits.cdp, "CDP session"); try { const { arguments: argv } = await bounded(session.send("Browser.getBrowserCommandLine"), limits.cdp, "actual argv"); report.sandbox.arguments = argv; const banned = new Set(["--no-sandbox", "--no-zygote-sandbox", "--disable-setuid-sandbox", "--disable-namespace-sandbox", "--disable-seccomp-filter-sandbox", "--disable-gpu-sandbox", "--allow-sandbox-debugging", "--single-process", "--ignore-gpu-blocklist", "--disable-web-security"]); assert.ok(argv.length && argv.every((s) => typeof s === "string")); assert.deepEqual(argv.map((s) => s.split("=", 1)[0]).filter((s) => banned.has(s) || /^--disable-.*sandbox$/.test(s)), []); report.sandbox.status = "PASS"; report.sandbox.launchSettings = { headless: true, chromiumSandbox: true, args: ["--enable-automation"] }; report.sandbox.qualification = "Pinned official defaults retained, including stock SwiftShader if observed; no custom GPU switch or hardware/kernel-isolation claim."; } finally { await bounded(session.detach(), limits.cdp, "CDP detach"); } });
  assert.equal(stopped, false); context = await bounded(browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 }), limits.operation, "browser context"); context.setDefaultTimeout(limits.operation); context.setDefaultNavigationTimeout(limits.operation); await context.route("**/*", async (route) => { if (new URL(route.request().url()).origin !== origin) { (report.blockedRequests ||= []).push(route.request().url()); await route.abort(); } else await route.continue(); }); await bounded(context.tracing.start({ screenshots: true, snapshots: true, sources: true }), limits.cdp, "trace start"); tracing = true; report.status = "RUNNING";
  const positive = await newPage("?condition=baseline&seed=1&sample=0"); await ready();
  await check("Original 6.5MB JSON is verified before showing the full 6×4 matrix and historical source", async () => {
    await drainResponses(positive);
    const rows = await page.locator("#run-matrix tbody tr").evaluateAll((nodes) => nodes.map((n) => ({ condition: n.dataset.condition, seed: n.dataset.seed, runId: n.dataset.runId, lastTick: Number(n.dataset.lastTick), living: Number(n.dataset.living), status: n.dataset.status, stop: n.dataset.stopReason, text: [...n.children].map((c) => c.textContent) }))); assert.equal(rows.length, 24); assert.equal(new Set(rows.map((r) => r.runId)).size, 24);
    for (const row of rows) { const original = run(row.condition, row.seed); assert.equal(row.runId, original.run_id); assert.equal(row.lastTick, original.checked_ticks); assert.equal(row.living, original.summary.living_cells); assert.equal(row.status, original.status); assert.equal(row.stop, original.stop_reason); assert.deepEqual(row.text.slice(1), [row.seed, String(original.checked_ticks), String(original.summary.living_cells), original.status, original.stop_reason]); }
    assert.deepEqual(await page.locator("#condition-select option").evaluateAll((n) => n.map((o) => o.value)), conditions); assert.deepEqual(await page.locator("#seed-select option").evaluateAll((n) => n.map((o) => o.value)), seeds); await page.locator("details:has(#exact-counters) > summary").click(); await page.locator("details:has(#landmark-summary) > summary").click(); await detail("baseline", "1", 0); await provenance(); report.matrix = rows;
  });
  const dataRequestsBeforeSelections = positive.requests.filter((r) => r.url.includes("/data/lab-2/")).length;
  await check("Every real run exposes genesis and terminal samples/counters/environment; all four seed curves match raw observations", async () => {
    for (const condition of conditions) { for (const seed of seeds) { const original = run(condition, seed); await select(condition, seed, 0); await detail(condition, seed, 0); await select(condition, seed, original.checked_ticks); const terminal = await detail(condition, seed, original.checked_ticks); await environment(condition, terminal); } await curves(condition, `all-seeds-${condition}`); }
    assert.equal(positive.requests.filter((r) => r.url.includes("/data/lab-2/")).length, dataRequestsBeforeSelections, "Selection/rendering must not reload the 6.5MB evidence"); report.completeRunLoop = { runs: 24, checkedEndpoints: 48, dataRequestsDuringSelection: 0 };
  });
  await check("Published pair records retain exact differences/ranges and missing 0/4 across every condition and seed", async () => {
    for (const condition of conditions.slice(1)) for (const seed of seeds) { await select(condition, seed, run(condition, seed).checked_ticks); await comparisons(condition, seed, "latest"); for (const tick of [100, 500, 1000, 2000, 5000, 10000, 20000]) await comparisons(condition, seed, tick); }
    assert.equal(report.pairs.length, 160); report.completePairLoop = { publishedLandmarkPairs: 140, publishedLatestCommonPairs: 20, newComparisons: 0 };
  });
  await check("Baseline/mutation-off/starvation controls distinguish living alleles, historical richness, terminal454 and common400", async () => {
    await select("baseline", "1", 1800); await detail("baseline", "1", 1800); assert.equal(await page.locator("#living-alleles").getAttribute("data-count"), "2"); assert.equal(await page.locator("#allele-history").getAttribute("data-richness"), "3"); await comparisons("baseline", "1");
    await select("mutation_off", "1", 20000); await detail("mutation_off", "1", 20000); assert.deepEqual(sample(run("mutation_off", "1"), 20000).allele_histogram, { "0": 101 }); assert.ok(integer(sample(run("mutation_off", "1"), 20000).lifecycle.fissions) > 0n);
    await select("starvation", "42", 454); await detail("starvation", "42", 454); assert.deepEqual(await page.locator("#sample-select option").evaluateAll((n) => n.map((o) => Number(o.value))), [0, 100, 200, 300, 400, 454]); await comparisons("starvation", "42", "latest"); assert.match(await page.locator("#comparison-status").textContent(), /tick 400.*terminal tick 454/); await comparisons("starvation", "42", 500); assert.match(await page.locator("#comparison-status").textContent(), /0 of 4.*unavailable/); await curves("starvation", "terminal454-never-carried-forward"); await screenshot("starvation-terminal454-missing500.png"); await postScreenshot("starvation-terminal454-missing500.png");
    await page.locator("#plot-window").selectOption("1000"); await curves("starvation", "first1000-observations-only"); await page.locator("#plot-window").selectOption("20000"); report.boundaries = { terminal: 454, latestCommon: 400, landmark: 500, available: 0, expected: 4, missingRange: "null/unavailable", baseline1800CurrentAlleles: 2, historicalRichness: 3 };
  });
  await check("Real URL/back/reload and keyboard selectors retain only exported observations without creating comparisons", async () => {
    await select("mutation_off", "42", 1000); await comparisons("mutation_off", "42", 500); const before = page.url(); await page.locator("#sample-select").selectOption("2000"); await detail("mutation_off", "42", 2000); assert.equal(await page.locator("#comparison-status").getAttribute("data-tick"), "500"); assert.equal(new URL(page.url()).searchParams.get("sample"), "2000"); await page.goBack(); await ready(); await detail("mutation_off", "42", 1000); assert.equal(page.url(), before); await drainResponses(positive); await page.reload({ waitUntil: "domcontentloaded" }); await ready(); await drainResponses(positive); await detail("mutation_off", "42", 1000); assert.equal(new URL(page.url()).searchParams.get("condition"), "mutation_off"); assert.equal(new URL(page.url()).searchParams.get("seed"), "42");
    await page.locator("#sample-select").focus(); await page.keyboard.press("Home"); await page.keyboard.press("ArrowDown"); await page.keyboard.press("Tab"); await detail("mutation_off", "42", 100); await page.locator("#seed-select").focus(); await page.keyboard.press("Home"); await page.keyboard.press("ArrowDown"); await page.keyboard.press("Tab"); await detail("mutation_off", "7", 100); const matrix = page.locator('#run-matrix tbody tr[data-condition="starvation"][data-seed="2026"] a'); await matrix.click(); await detail("starvation", "2026", 454); report.navigation = { back: true, reload: true, actualKeyboardSample: 100, actualKeyboardSeed: "7", realMatrixLinkRun: "seed-2026-starvation", retainedSampleOnly: true };
  });
  await check("Desktop/short/390/320 layouts keep selectors and four actual observation charts visible without page overflow", async () => { await comparisons("starvation", "2026", 500); for (const [filename, width, height] of [["desktop.png", 1440, 900], ["short.png", 1440, 720], ["mobile390.png", 390, 844], ["mobile320.png", 320, 844]]) await layout(filename, width, height); });
  await closePage(positive);
  await check("Same-length original numeric-exponent spelling transport mutation produces visible SHA refusal before committing any chart", async () => { const observations = await newPage("?condition=baseline&seed=1&sample=0", true); await fatalVisible(/results SHA-256/, "integrity-error-visible.png"); assert.ok(report.integrityNegative); await closePage(observations); });
  await check("Absent starvation sample500 deep URL fails visibly instead of clamping/interpolating a model observation", async () => { const observations = await newPage("?condition=starvation&seed=1&sample=500"); await fatalVisible(/sample must be a retained observation/, "absent-sample-error-visible.png"); report.absentSample = { requestedTick: 500, actualTerminalTick: 454, noCommit: true }; await closePage(observations); });
  assert.equal(stopped, false); report.status = "PASS";
}

if (process.argv.includes("--oracle-only")) console.log(JSON.stringify(oracleCheck()));
else if (process.argv.includes("--raw-oracle-only")) { for (const [name, pin] of Object.entries(pins)) { raw[name] = await readFile(join(root, `docs/experiments/lab-2/${name}.json`)); assert.equal(raw[name].length, pin.bytes); assert.equal(sha(raw[name]), pin.sha256); } data = JSON.parse(raw.results); console.log(JSON.stringify({ synthetic: oracleCheck(), raw: rawOracle(), browser: "NOT_RUN" })); }
else if (process.argv.includes("--source-preflight-only")) { await prepare(); console.log(JSON.stringify({ status: "PASS", scope: "Source/copy/pin preflight only", raw: report.rawArithmetic, descriptorSha256: report.dataIdentity.descriptorSha256, assets: assets.size, batchObservation: report.batchObservationOracle, transportControl: report.integrityControlSource, browser: "NOT_RUN" })); }
else {
  await rm(output, { recursive: true, force: true }); await mkdir(output, { recursive: true });
  try { running = main(); await bounded(running, limits.run, "whole LAB browser gate"); } catch (e) { fail(e); if (running) await bounded(running.catch(() => {}), limits.operation + limits.launch, "interrupted settlement").catch((e) => fail(e, "settlement")); }
  finally {
    const cleanup = async (label, action, ms = limits.cleanup) => { try { await bounded(action(), ms, label); } catch (e) { report.cleanupErrors.push({ label, error: e.stack || String(e) }); fail(e, label); } };
    if (page && !page.isClosed()) await cleanup("failure PNG", () => screenshot("failure.png"));
    if (tracing) await cleanup("trace publication", async () => { await context.tracing.stop({ path: join(output, "trace.zip") }); const bytes = await readFile(join(output, "trace.zip")); assert.ok(bytes.length); report.trace = { status: "PASS", bytes: bytes.length, sha256: sha(bytes) }; }, limits.trace);
    if (context) await cleanup("context close", () => context.close()); if (browser) await cleanup("browser close", () => browser.close()); if (server) await cleanup("server close", () => new Promise((done, reject) => { server.close((e) => e ? reject(e) : done()); server.closeAllConnections(); })); await sleep(50);
    if (report.status === "PASS") try {
      assert.equal(stopped, false); assert.equal(git("rev-parse", "HEAD"), report.sourceHead); assert.equal(git("rev-parse", "HEAD^{tree}"), report.sourceTree); assert.equal(git("status", "--porcelain", "--untracked-files=no"), ""); assert.deepEqual(report.pageErrors, []); assert.deepEqual(report.consoleErrors, []); assert.deepEqual(report.nodeUnhandled, []); assert.deepEqual(report.cleanupErrors, []); assert.deepEqual(report.routeErrors || [], []); assert.deepEqual(report.blockedRequests || [], []); assert.equal(report.trace.status, "PASS"); assert.equal(report.sandbox.status, "PASS"); assert.equal(report.oracle.status, "PASS"); assert.equal(report.rawArithmetic.checkedPairs, 160); assert.equal(report.batchObservationOracle.status, "PASS"); assert.equal(report.batchObservationOracle.cases, 6); assert.equal(report.checks.length, 9); assert.ok(report.checks.every((c) => c.status === "PASS")); assert.equal(report.pages.length, 3);
      for (const p of report.pages) { await bounded(Promise.all([...p.pending]), limits.operation, "post-cleanup response settlement"); assert.equal(p.pending.size, 0); assert.equal(p.closed, true); assert.deepEqual(p.failed, []); assert.deepEqual(p.external, []); assert.deepEqual(p.unhandled, []); assert.deepEqual(p.responseErrors, []); for (const name of Object.keys(pins)) assert.ok(p.responses.some((r) => r.path === `/data/lab-2/${name}.json`)); p.pendingCount = p.pending.size; delete p.pending; }
      assert.ok(report.serverRequests.every((r) => r.method === "GET" && r.status === 200)); assert.equal(report.layouts.length, 4); assert.equal(report.typography.length, 9); assert.equal(report.postScreenshot.length, 5); assert.equal(report.postScreenshotNegative.length, 2); assert.equal(report.screenshots.length, 7); assert.equal(report.completeRunLoop.checkedEndpoints, 48); assert.equal(report.completePairLoop.publishedLandmarkPairs, 140); assert.equal(report.completePairLoop.publishedLatestCommonPairs, 20); assert.equal(report.completePairLoop.newComparisons, 0); assert.ok(report.samples.length >= 52); assert.equal(new Set(report.samples.map((s) => s.runId)).size, 24); assert.equal(report.boundaries.terminal, 454); assert.equal(report.boundaries.latestCommon, 400); assert.equal(report.boundaries.available, 0); assert.ok(report.navigation.back && report.navigation.reload); assert.ok(report.integrityNegative && report.absentSample);
      // Recheck after settlement: no later callback can turn a prior failure green.
      assert.deepEqual(report.nodeUnhandled, []); assert.deepEqual(report.pageErrors, []); assert.deepEqual(report.consoleErrors, []); assert.deepEqual(report.cleanupErrors, []); assert.equal(stopped, false);
    } catch (e) { fail(e, "post-cleanup aggregate"); }
    report.finishedAt = new Date().toISOString(); await writeFile(join(output, "report.json"), JSON.stringify(report, null, 2) + "\n"); console.log(JSON.stringify({ status: report.status, sourceHead: report.sourceHead, output })); if (report.status !== "PASS") process.exitCode = 1;
  }
}
