// Подготовленный отдельный public smoke. Null deployed head запрещает сеть/browser.
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), ".."), output = join(root, "target/qa/public-lab"), expectedPath = "scripts/lab-public-expected-assets.json";
const sha = (bytes) => createHash("sha256").update(bytes).digest("hex"), git = (...args) => execFileSync("git", args, { cwd: root, encoding: "utf8" }).trim();
const paths = ["lab.html", "lab.js", "lab.css", "lab-data.mjs", "data/lab-2/descriptor.json", "data/lab-2/results.json", "data/lab-2/comparisons.json", "data/lab-2/manifest.json"];
const producer = "21cbe90732128edee61963544e414d29a7420577", seeds = ["1", "7", "42", "2026"], conditions = ["baseline", "mutation_off", "starvation", "oxygen_low", "exchange_half", "founder_k2"];
const metrics = ["living_cells", "structural_mass_mol", "food_free_mol", "oxygen_free_mol"];
const limits = { whole: 330_000, deployment: 180_000, retry: 5000, fetch: 15_000, operation: 15_000, viewport: 50_000, launch: 20_000, cdp: 5000, cleanup: 5000, trace: 15_000 };
const report = { status: "NOT_RUN", startedAt: new Date().toISOString(), scope: "Partial read-only PUBLIC LAB smoke; does not replace the private nine-gate LAB browser acceptance, main CI or scientific validation.", limits, checks: [], sources: [], assetAttempts: [], publicAssets: [], pages: [], screenshots: [], nodeUnhandled: [], cleanupErrors: [], prohibitedRequests: [], sandbox: { status: "NOT_RUN" }, trace: { status: "NOT_RUN" }, qualifications: ["Only the frozen eight HTTPS asset pins and exact previously accepted 367-byte analytics insertion may match; no general HTML normalization.", "Scientific producer21cbe907/world30/chamber1/dt30 is separate from deployed product HEAD and current QA HEAD/tree.", "Original aggregates and published pairs only; no models, cells, positions, full genomes, new science/comparisons or per-tick ledger proof.", "Analytics is blocked at CDP Request stage before transmission. Its execution/hosting/kernel isolation, full accessibility and FPS are unasserted.", "Deployment byte matching is bounded; failed browser actions are never retried until green."] };
let expected, base, browser, context, tracing = false, stopped = false, running;
const local = new Map(), finalizers = [];
const sleep = (ms) => new Promise((done) => setTimeout(done, ms));
function fail(error, stage = "run") { stopped = true; report.status = "FAIL"; process.exitCode = 1; (report.failures ||= []).push({ stage, error: error.stack || String(error) }); }
process.on("unhandledRejection", (e) => { report.nodeUnhandled.push(e?.stack || String(e)); fail(e instanceof Error ? e : new Error(String(e)), "Node unhandled rejection"); });
async function bounded(operation, timeout, label) { let timer; try { return await Promise.race([operation, new Promise((_, reject) => { timer = setTimeout(() => reject(new Error(`Timed out: ${label}`)), timeout); })]); } finally { clearTimeout(timer); } }
async function check(name, action) { assert.equal(stopped, false); const start = performance.now(); try { await action(); report.checks.push({ name, status: "PASS", elapsedMs: performance.now() - start }); } catch (error) { report.checks.push({ name, status: "FAIL", error: error.stack || String(error) }); throw error; } }
const keys = (value, names) => { assert.ok(value && typeof value === "object" && !Array.isArray(value)); assert.deepEqual(Object.keys(value).sort(), [...names].sort()); };
const isHead = (value) => typeof value === "string" && /^[a-f0-9]{40}$/.test(value), isSha = (value) => typeof value === "string" && /^[a-f0-9]{64}$/.test(value);
function validateExpected(value, preparation) {
  keys(value, ["schema_version", "scope", "public_origin", "product_candidate_head", "product_candidate_tree", "deployed_product_head", "assets", "html_hosting_exception"]); assert.equal(value.schema_version, 1); assert.equal(value.scope, "public_lab_smoke_preparation"); assert.equal(value.public_origin, "https://liminis.dev/"); assert.ok(isHead(value.product_candidate_head) && isHead(value.product_candidate_tree));
  if (preparation) assert.ok(value.deployed_product_head === null || isHead(value.deployed_product_head)); else assert.ok(isHead(value.deployed_product_head), "REFUSED: deployed_product_head is not pinned to an accepted actual product merge; no public request/browser may run");
  assert.ok(Array.isArray(value.assets)); assert.deepEqual(value.assets.map((a) => a.filename), paths); for (const a of value.assets) { keys(a, ["filename", "bytes", "sha256"]); assert.ok(Number.isSafeInteger(a.bytes) && a.bytes > 0 && a.bytes < 8 * 1024 * 1024 && isSha(a.sha256)); }
  const e = value.html_hosting_exception; keys(e, ["source_body_close_offset", "bytes", "sha256", "script_url"]); assert.equal(e.source_body_close_offset, 5377); assert.equal(e.bytes, 367); assert.equal(e.sha256, "bbba70d1fbb140fe2cff2d40386e726bfe911227760ad6e69e29644e42b6f40a"); assert.equal(e.script_url, "https://static.cloudflareinsights.com/beacon.min.js/v31edd6df95cf4e85bb4c19e7a9bdbcba1788362987495"); return value;
}
async function prepare(preparation) {
  expected = validateExpected(JSON.parse(await readFile(join(root, expectedPath))), preparation); base = new URL(expected.public_origin); report.expected = expected;
  assert.equal(git("rev-parse", `${expected.product_candidate_head}^{tree}`), expected.product_candidate_tree);
  for (const asset of expected.assets) { const bytes = await readFile(join(root, "site", asset.filename)); assert.equal(bytes.length, asset.bytes); assert.equal(sha(bytes), asset.sha256); assert.deepEqual(bytes, execFileSync("git", ["show", `${expected.product_candidate_head}:site/${asset.filename}`], { cwd: root, maxBuffer: 8 * 1024 * 1024 })); if (expected.deployed_product_head !== null) assert.deepEqual(bytes, execFileSync("git", ["show", `${expected.deployed_product_head}:site/${asset.filename}`], { cwd: root, maxBuffer: 8 * 1024 * 1024 })); local.set(asset.filename, bytes); report.sources.push(asset); }
  assert.equal(local.get("lab.html").indexOf(Buffer.from("</body>")), expected.html_hosting_exception.source_body_close_offset); report.productCandidateHead = expected.product_candidate_head; report.deployedProductHead = expected.deployed_product_head;
}
function verifyBytes(asset, bytes) {
  const result = { rawBytes: bytes.length, rawSha256: sha(bytes), rawMatchesSource: bytes.length === asset.bytes && sha(bytes) === asset.sha256, knownEdgeInsertionVerified: false }; let source = bytes;
  if (!result.rawMatchesSource && asset.filename === "lab.html") { const e = expected.html_hosting_exception; assert.equal(bytes.length, asset.bytes + e.bytes); assert.equal(sha(bytes.subarray(e.source_body_close_offset, e.source_body_close_offset + e.bytes)), e.sha256); source = Buffer.concat([bytes.subarray(0, e.source_body_close_offset), bytes.subarray(e.source_body_close_offset + e.bytes)]); result.knownEdgeInsertionVerified = true; }
  assert.equal(source.length, asset.bytes); assert.equal(sha(source), asset.sha256); result.sourceBytes = source.length; result.sourceSha256 = sha(source); return result;
}
function redirectAllowed(from, to) { const a = new URL(from), b = new URL(to); return a.origin === base.origin && b.origin === base.origin && a.protocol === "https:" && b.protocol === "https:" && !a.username && !a.password && !b.username && !b.password && a.pathname === "/lab.html" && b.pathname === "/lab" && !a.search && !b.search && !a.hash && !b.hash; }
function originalMetric(sample, metric) { if (metric === "living_cells" || metric === "structural_mass_mol") return sample[metric]; const id = metric === "food_free_mol" ? "FOOD" : "O2", item = sample.matter.find((m) => m.id === id); assert.ok(item); return item.free_mol; }
async function fetchAsset(asset, attempt, timeout) {
  const observation = { filename: asset.filename, status: "MISMATCH", redirects: [] }, controller = new AbortController(), timer = setTimeout(() => controller.abort(), timeout); let reader, response;
  try {
    let url = new URL(asset.filename, base);
    response = await fetch(url, { signal: controller.signal, redirect: "manual", cache: "no-store", headers: { "Cache-Control": "no-cache" } });
    if ([301, 302, 303, 307, 308].includes(response.status)) { const target = new URL(response.headers.get("location"), url); assert.ok(asset.filename === "lab.html" && redirectAllowed(url, target), "Unexpected redirect: refusal before next request"); observation.redirects.push({ from: url.href, to: target.href, status: response.status }); await bounded(response.body?.cancel(), limits.cleanup, "redirect body cancellation"); url = target; response = await fetch(url, { signal: controller.signal, redirect: "manual", cache: "no-store", headers: { "Cache-Control": "no-cache" } }); }
    observation.finalUrl = url.href; observation.httpStatus = response.status; observation.contentType = response.headers.get("content-type"); assert.equal(response.status, 200); assert.ok(response.body); reader = response.body.getReader(); const cap = asset.bytes + (asset.filename === "lab.html" ? expected.html_hosting_exception.bytes : 0), chunks = []; let size = 0;
    for (;;) { const next = await reader.read(); if (next.done) break; size += next.value.length; assert.ok(size <= cap, "Public decoded response exceeds the pinned bounded byte budget"); chunks.push(next.value); }
    const bytes = Buffer.concat(chunks, size); observation.rawBytes = bytes.length; observation.rawSha256 = sha(bytes); if (asset.filename === "lab.html") { observation.rawHtmlFilename = `node-html-attempt-${attempt}.html`; await writeFile(join(output, observation.rawHtmlFilename), bytes); } Object.assign(observation, verifyBytes(asset, bytes)); observation.status = "PASS";
  } catch (e) { observation.error = e.message || String(e); if (/Unexpected redirect/.test(observation.error)) throw e; }
  finally { clearTimeout(timer); if (reader) await bounded(reader.cancel(), limits.cleanup, "public response cancellation").catch((e) => (observation.cleanupError = String(e))); else if (response?.body) await bounded(response.body.cancel(), limits.cleanup, "public response disposal").catch((e) => (observation.cleanupError = String(e))); controller.abort(); }
  return observation;
}
async function waitForAssets() {
  const deadline = Date.now() + limits.deployment, pending = new Map(expected.assets.map((a) => [a.filename, a])); let attempt = 0;
  while (pending.size) { assert.equal(stopped, false); const batch = await Promise.all([...pending.values()].map((a) => fetchAsset(a, attempt, Math.min(limits.fetch, Math.max(1, deadline - Date.now()))))); report.assetAttempts.push({ attempt: attempt++, observations: batch }); for (const r of batch) if (r.status === "PASS") { assert.equal(r.cleanupError, undefined); pending.delete(r.filename); report.publicAssets.push(r); } if (!pending.size) return; assert.ok(Date.now() < deadline, "Deployment did not match frozen LAB pins within 180s"); await sleep(Math.min(limits.retry, deadline - Date.now())); }
}

async function smoke(name, viewport) {
  assert.equal(stopped, false); const page = await bounded(context.newPage(), limits.operation, "public LAB page"); page.setDefaultTimeout(limits.operation); page.setDefaultNavigationTimeout(limits.operation); await page.setViewportSize(viewport);
  const observation = { name, viewport, status: "RUNNING", requests: [], requestFailures: [], consoleErrors: [], pageErrors: [], runtimeExceptions: [], sources: [], redirects: [], analytics: [], errors: [], guard: { status: "RUNNING", allowed: 0, blocked: 0 } }; report.pages.push(observation);
  const session = await bounded(context.newCDPSession(page), limits.cdp, "every-hop request guard"), actions = new Set(), bodyReads = [], guardedHops = new Map(), pathAssets = new Map(expected.assets.map((a) => [`/${a.filename}`, a])); pathAssets.set("/lab", expected.assets[0]); const document = report.publicAssets.find((a) => a.filename === "lab.html"), finalUrl = document.finalUrl; observation.guard.hops = [];
  session.on("Fetch.requestPaused", (event) => { const action = (async () => {
    const request = event.request, url = new URL(request.url);
    assert.ok(guardedHops.size < 64 && !guardedHops.has(event.requestId), "Each bounded Request-stage hop has a distinct CDP identity");
    const previous = event.redirectedRequestId ? guardedHops.get(event.redirectedRequestId) : null;
    if (event.redirectedRequestId) { assert.ok(previous && redirectAllowed(previous.url, url.href), "Refuse any noncanonical redirected hop before transmission"); assert.ok(document.redirects.some((r) => r.from === previous.url && r.to === url.href), "Redirected hop must already be byte-attested by Node HTTPS"); }
    const hop = { requestId: event.requestId, networkId: event.networkId, redirectedRequestId: event.redirectedRequestId || null, url: url.href, method: request.method }; guardedHops.set(event.requestId, hop); observation.guard.hops.push(hop);
    if (request.method === "GET" && url.protocol === "https:" && url.origin === base.origin && !url.username && !url.password && !url.search && !url.hash && pathAssets.has(url.pathname)) { observation.guard.allowed++; await bounded(session.send("Fetch.continueRequest", { requestId: event.requestId }), limits.cdp, "same-origin GET guard acknowledgement"); }
    else if (request.method === "GET" && url.href === expected.html_hosting_exception.script_url && event.resourceType === "Script") { const tree = await bounded(session.send("Page.getFrameTree"), limits.cdp, "analytics main-document attribution"); assert.equal(event.frameId, tree.frameTree.frame.id); assert.equal(tree.frameTree.frame.url, finalUrl); const item = { url: url.href, requestId: event.requestId, networkId: event.networkId, frameId: event.frameId, documentUrl: finalUrl, method: "GET", resourceType: "Script", status: "PENDING_ACK", measurement: "CDP Request stage before transmission" }; observation.analytics.push(item); await bounded(session.send("Fetch.failRequest", { requestId: event.requestId, errorReason: "BlockedByClient" }), limits.cdp, "pinned analytics block acknowledgement"); item.status = "BLOCKED_ACKNOWLEDGED"; }
    else { observation.guard.blocked++; report.prohibitedRequests.push({ url: request.url, method: request.method, requestId: event.requestId }); await bounded(session.send("Fetch.failRequest", { requestId: event.requestId, errorReason: "BlockedByClient" }), limits.cdp, "out-of-scope refusal before transmission"); }
  })().catch(async (e) => { observation.errors.push(e.stack || String(e)); observation.guard.status = "FAIL"; await bounded(session.send("Fetch.failRequest", { requestId: event.requestId, errorReason: "BlockedByClient" }), limits.cdp, "failed guard refusal").catch((e) => observation.errors.push(String(e))); }).finally(() => actions.delete(action)); actions.add(action); });
  page.on("request", (r) => observation.requests.push({ url: r.url(), method: r.method() })); page.on("requestfailed", (r) => observation.requestFailures.push({ url: r.url(), method: r.method(), error: r.failure()?.errorText })); page.on("pageerror", (e) => observation.pageErrors.push(e.stack || String(e))); page.on("console", (m) => { if (m.type() === "error") observation.consoleErrors.push({ text: m.text(), location: m.location() }); });
  session.on("Runtime.exceptionThrown", (event) => observation.runtimeExceptions.push(event.exceptionDetails));
  await page.addInitScript(() => { window.__publicLabUnhandled = []; addEventListener("unhandledrejection", (e) => window.__publicLabUnhandled.push(String(e.reason?.stack || e.reason))); });
  page.on("response", (r) => { const url = new URL(r.url()), asset = url.origin === base.origin ? pathAssets.get(url.pathname) : null; if (!asset) { observation.errors.push(`Unpinned response: ${r.url()}`); return; }
    if ([301, 302, 303, 307, 308].includes(r.status())) { const item = { from: r.url(), status: r.status(), verdict: "FAIL" }; observation.redirects.push(item); try { const target = new URL(r.headers().location, r.url()), pinned = document.redirects.find((d) => d.from === r.url()); assert.ok(pinned && redirectAllowed(r.url(), target)); assert.equal(pinned.to, target.href); assert.equal(pinned.status, r.status()); item.to = target.href; item.verdict = "PASS"; } catch (e) { item.error = String(e); } return; }
    const item = { filename: asset.filename, url: r.url(), status: "FAIL", httpStatus: r.status() }; observation.sources.push(item); bodyReads.push(bounded(r.body(), limits.operation, "actual public browser response bytes").then(async (bytes) => { item.rawBytes = bytes.length; item.rawSha256 = sha(bytes); if (asset.filename === "lab.html") { item.rawHtmlFilename = `${name}-raw.html`; await writeFile(join(output, item.rawHtmlFilename), bytes); observation.html = item; } assert.equal(r.status(), 200); Object.assign(item, verifyBytes(asset, bytes)); item.status = "PASS"; }).catch((e) => (item.error = e.stack || String(e))));
  });
  let closed = false, passed = false;
  async function drain() { await bounded((async () => { while (actions.size) await Promise.all([...actions]); let n = 0; while (n < bodyReads.length) { const next = bodyReads.slice(n); n += next.length; await Promise.all(next); } })(), limits.operation, "public callbacks drain"); }
  async function finalProof() { await drain(); assert.equal(closed, true); assert.equal(passed, true); assert.equal(actions.size, 0); assert.deepEqual(observation.errors, []); assert.deepEqual(observation.pageErrors, []); assert.deepEqual(observation.runtimeExceptions, []); assert.deepEqual(observation.unhandled, []); assert.ok(observation.sources.every((s) => s.status === "PASS")); for (const asset of expected.assets) assert.ok(observation.sources.some((s) => s.filename === asset.filename && s.status === "PASS")); assert.ok(observation.redirects.every((r) => r.verdict === "PASS")); assert.deepEqual(observation.redirects.map(({ from, to, status }) => ({ from, to, status })), document.redirects); assert.equal(observation.guard.blocked, 0); assert.ok(observation.guard.allowed >= 8); assert.notEqual(observation.guard.status, "FAIL");
    const count = observation.html.knownEdgeInsertionVerified ? 1 : 0; assert.equal(observation.analytics.length, count); assert.ok(observation.analytics.every((a) => a.status === "BLOCKED_ACKNOWLEDGED")); assert.ok(observation.requests.every((r) => r.method === "GET" && (new URL(r.url).origin === base.origin || count === 1 && r.url === expected.html_hosting_exception.script_url))); const failures = observation.requestFailures.filter((r) => count === 1 && r.url === expected.html_hosting_exception.script_url && r.method === "GET" && /^net::ERR_BLOCKED_BY_CLIENT(?:\.Inspector)?$/.test(r.error || "")); assert.equal(failures.length, count); assert.equal(observation.requestFailures.length, failures.length); const consoles = observation.consoleErrors.filter((r) => count === 1 && r.location.url === expected.html_hosting_exception.script_url && /^Failed to load resource: net::ERR_BLOCKED_BY_CLIENT(?:\.Inspector)?$/.test(r.text)); assert.ok(consoles.length <= count); assert.equal(observation.consoleErrors.length, consoles.length); assert.deepEqual(observation.controlRequests, []); observation.expectedAnalyticsErrors = { requestFailures: failures, consoleErrors: consoles }; observation.guard.status = "PASS"; observation.status = "PASS";
  }
  finalizers.push(finalProof);
  async function plotsReady() {
    await page.waitForFunction(() => {
      const host = document.getElementById("plots"), charts = [...host.querySelectorAll(".metric-plot")];
      return host.getAttribute("aria-busy") !== "true" && host.dataset.layout !== "pending" && charts.length === 4 && charts.every((svg) => {
        const width = svg.getBoundingClientRect().width, box = svg.getAttribute("viewBox")?.split(/\s+/).map(Number);
        return Number.isFinite(width) && width > 96 && box?.length === 4 && Math.abs(box[2] - width) < .01 && getComputedStyle(svg).visibility === "visible";
      });
    });
  }
  try {
    await bounded(session.send("Runtime.enable"), limits.cdp, "capture runtime errors through page closure"); await bounded(session.send("Network.setCacheDisabled", { cacheDisabled: true }), limits.cdp, "disable public cache"); await bounded(session.send("Fetch.enable", { patterns: [{ urlPattern: "*", requestStage: "Request" }] }), limits.cdp, "enable every-hop Request-stage guard"); await page.goto(new URL("lab.html", base).href, { waitUntil: "domcontentloaded" }); await page.waitForFunction(() => !document.getElementById("lab-workspace").hidden && document.getElementById("lab-error").hidden && document.getElementById("lab-workspace").getAttribute("aria-busy") === "false"); await page.waitForLoadState("networkidle"); await drain(); assert.equal(new URL(page.url()).pathname, new URL(finalUrl).pathname);
    const results = JSON.parse(local.get("data/lab-2/results.json")), comparisons = JSON.parse(local.get("data/lab-2/comparisons.json")); const runs = (condition, seed) => results.runs.find((r) => r.condition === condition && r.seed === seed);
    const matrix = await page.locator("#run-matrix tbody tr").evaluateAll((rows) => rows.map((r) => ({ condition: r.dataset.condition, seed: r.dataset.seed, run: r.dataset.runId, tick: Number(r.dataset.lastTick), living: Number(r.dataset.living), status: r.dataset.status, stop: r.dataset.stopReason }))); assert.equal(matrix.length, 24); assert.equal(new Set(matrix.map((r) => r.run)).size, 24); for (const row of matrix) { const original = runs(row.condition, row.seed); assert.ok(original); assert.equal(row.run, original.run_id); assert.equal(row.tick, original.checked_ticks); assert.equal(row.living, original.summary.living_cells); assert.equal(row.status, original.status); assert.equal(row.stop, original.stop_reason); } observation.matrix = matrix;
    assert.deepEqual(await page.locator("#condition-select option").evaluateAll((n) => n.map((o) => o.value)), conditions); assert.deepEqual(await page.locator("#seed-select option").evaluateAll((n) => n.map((o) => o.value)), seeds); const beforeControls = observation.requests.length;
    async function select(condition, seed, tick) { await page.locator("#condition-select").selectOption(condition); await page.locator("#seed-select").selectOption(seed); await page.locator("#sample-select").selectOption(String(tick)); const sample = runs(condition, seed).samples.find((s) => s.tick === tick); assert.ok(sample); assert.equal(await page.locator("#sample-stamp").getAttribute("data-run-id"), runs(condition, seed).run_id); assert.equal(await page.locator("#sample-stamp").getAttribute("data-tick"), String(tick)); assert.equal(await page.locator('#run-detail [data-field="living_cells"]').getAttribute("data-value"), String(sample.living_cells)); const url = new URL(page.url()); assert.equal(url.origin, base.origin); assert.equal(url.searchParams.get("condition"), condition); assert.equal(url.searchParams.get("seed"), seed); assert.equal(url.searchParams.get("sample"), String(tick)); }
    await select("mutation_off", "7", 20000); assert.equal(await page.locator("#living-alleles").getAttribute("data-count"), "1"); await select("starvation", "42", 454); assert.equal(await page.locator('#run-detail [data-field="terminal_tick"]').getAttribute("data-value"), "454"); assert.deepEqual(await page.locator("#sample-select option").evaluateAll((n) => n.map((o) => Number(o.value))), [0, 100, 200, 300, 400, 454]); await page.locator("#comparison-select").selectOption("latest"); assert.equal(await page.locator("#comparison-status").getAttribute("data-tick"), "400"); await page.locator("#comparison-select").selectOption("500"); assert.match(await page.locator("#comparison-status").textContent(), /0 of 4.*unavailable/); const published = comparisons.landmark_comparisons.find((r) => r.condition === "starvation" && r.tick === 500); assert.equal(published.available_pairs, 0); const missing = await page.locator('#pair-comparison td[data-arm="delta"]').evaluateAll((n) => n.map((d) => ({ value: d.dataset.value, text: d.textContent }))); assert.equal(missing.length, 9); assert.ok(missing.every((d) => d.value === "null" && /unavailable/.test(d.text))); await page.locator("details:has(#landmark-summary) > summary").click();
    const missingRanges = await page.locator('#pair-comparison td[data-arm="range"]').evaluateAll((nodes) => nodes.map((n) => ({ count: n.dataset.count, min: n.dataset.min, max: n.dataset.max, width: n.dataset.width, text: n.textContent })));
    assert.equal(missingRanges.length, 9); assert.ok(missingRanges.every((r) => r.count === "0" && r.min === "null" && r.max === "null" && r.width === "null" && /unavailable/.test(r.text)));
    const commonRows = await page.locator('#latest-common-summary tbody tr').evaluateAll((nodes) => nodes.map((n) => ({ seed: n.dataset.seed, tick: Number(n.dataset.tick) }))); assert.deepEqual(commonRows, seeds.map((seed) => ({ seed, tick: 400 })));
    async function auditCurves(label) {
      await plotsReady();
    const curves = await page.locator(".metric-plot").evaluateAll((nodes) => nodes.map((svg) => ({ metric: svg.dataset.metric, viewBox: svg.getAttribute("viewBox").split(/\s+/).map(Number), cssWidth: svg.getBoundingClientRect().width, cssHeight: svg.getBoundingClientRect().height, frame: [Number(svg.dataset.x0), Number(svg.dataset.x1), Number(svg.dataset.y0), Number(svg.dataset.y1)], axisFonts: [...svg.querySelectorAll(".axis-label")].map((n) => parseFloat(getComputedStyle(n).fontSize)), xmax: Number(svg.dataset.xMax), ymax: Number(svg.dataset.yMax), curves: [...svg.querySelectorAll(".observed-curve")].map((p) => { const dots = [...svg.querySelectorAll(".observed-dot")].filter((d) => d.dataset.condition === p.dataset.condition && d.dataset.seed === p.dataset.seed), last = dots.at(-1); return { condition: p.dataset.condition, seed: p.dataset.seed, count: Number(p.dataset.sampleCount), last: Number(p.dataset.lastTick), d: p.getAttribute("d"), stroke: p.getAttribute("stroke"), opacity: Number(p.getAttribute("opacity")), dotCount: dots.length, endpoint: { tick: Number(last.dataset.tick), x: Number(last.getAttribute("cx")), y: Number(last.getAttribute("cy")) } }; }) })));
    assert.deepEqual(curves.map((p) => p.metric), metrics);
    for (const plot of curves) {
      assert.ok(Number.isFinite(plot.cssWidth) && plot.cssWidth > 96); assert.equal(plot.viewBox.length, 4); assert.deepEqual(plot.viewBox.slice(0, 2), [0, 0]); assert.ok(Math.abs(plot.viewBox[2] - plot.cssWidth) < .01); assert.equal(plot.viewBox[3], 210); assert.ok(Math.abs(plot.cssHeight - 210) < .01); assert.deepEqual(plot.frame, [72, plot.cssWidth - 12, 12, 178]); assert.equal(plot.axisFonts.length, 6); assert.ok(plot.axisFonts.every((v) => Number.isFinite(v) && v >= 10)); assert.equal(plot.xmax, 20_000 * 30); assert.equal(plot.curves.length, 8);
      const originalArms = ["baseline", "starvation"].flatMap((arm) => seeds.map((seed) => runs(arm, seed))), ymax = Math.max(...originalArms.flatMap((r) => r.samples.map((sample) => originalMetric(sample, plot.metric)))) || 1; assert.equal(plot.ymax, ymax);
      for (const arm of ["baseline", "starvation"]) for (const seed of seeds) {
        const matching = plot.curves.filter((p) => p.condition === arm && p.seed === seed); assert.equal(matching.length, 1); const actual = matching[0], original = runs(arm, seed), last = original.samples.at(-1); assert.equal(actual.count, original.samples.length); assert.equal(actual.dotCount, original.samples.length); assert.equal(actual.last, original.checked_ticks); assert.equal(actual.endpoint.tick, last.tick); assert.ok(actual.d.startsWith("M") && actual.stroke !== "none" && actual.opacity > 0);
        // Independent original retained sample -> SVG endpoint. No product helper import.
        const x = 72 + last.time_seconds / plot.xmax * (plot.cssWidth - 84), y = 178 - originalMetric(last, plot.metric) / ymax * 166, path = actual.d.trim().split(/[ML\s]+/).filter(Boolean).map(Number); assert.equal(path.length, original.samples.length * 2); assert.ok(path.every(Number.isFinite));
        assert.ok(Math.abs(actual.endpoint.x - x) < .000001 && Math.abs(actual.endpoint.y - y) < .000001); assert.ok(Math.abs(path.at(-2) - x) <= .000001 && Math.abs(path.at(-1) - y) <= .000001); delete actual.d;
      }
    }
      const audit = { label, scope: "Four metrics, four paired seed arms; CSS pixel frame/fonts, counts/domains/original-sample endpoints; not every private geometry gate", plots: curves };
      (observation.curveAudits ||= []).push(audit); return audit;
    }
    observation.curves = await auditCurves("before-fullPage-capture"); observation.boundaries = { terminal: 454, common: 400, missingLandmark: 500, available: 0, expected: 4, missingRanges, commonRows };
    await page.locator("#sample-select").selectOption("400"); assert.equal(new URL(page.url()).searchParams.get("sample"), "400"); await page.evaluate(() => history.back()); await page.waitForFunction(() => document.getElementById("sample-stamp").dataset.tick === "454"); assert.equal(new URL(page.url()).searchParams.get("sample"), "454"); observation.urlBack = { selected: 400, restored: 454, url: page.url() };
    assert.equal(await page.locator('#provenance [data-field="source_commit"]').getAttribute("data-value"), producer); for (const [field, value] of [["world_format_version", "30"], ["chamber_format", "1"], ["dt_seconds", "30"], ["build_attestation", "false"]]) assert.equal(await page.locator(`#provenance [data-field="${field}"]`).getAttribute("data-value"), value); const links = await page.locator("#source-links a").evaluateAll((n) => n.map((a) => a.href)); assert.ok(links.includes(`https://github.com/emevart/liminis/tree/${producer}`)); for (const file of ["results", "comparisons", "manifest"]) assert.ok(links.includes(new URL(`data/lab-2/${file}.json`, base).href)); observation.provenanceLinks = links;
    const layout = await page.evaluate(() => ({ width: document.documentElement.scrollWidth, viewport: innerWidth, controls: ["condition-select", "seed-select", "sample-select", "comparison-select", "plot-window"].map((id) => { const r = document.getElementById(id).getBoundingClientRect(); return { id, width: r.width, height: r.height, left: r.left, right: r.right }; }) })); assert.ok(layout.width <= layout.viewport); assert.ok(layout.controls.every((c) => c.width > 0 && c.height > 0 && c.left >= 0 && c.right <= layout.viewport + 1)); assert.equal(await page.locator("#lab-error").isVisible(), false); observation.layout = layout; const png = await page.screenshot({ path: join(output, `${name}.png`), fullPage: true }); report.screenshots.push({ filename: `${name}.png`, bytes: png.length, sha256: sha(png) }); observation.curvesAfterCapture = await auditCurves("after-fullPage-capture"); observation.unhandled = await page.evaluate(() => window.__publicLabUnhandled); observation.controlRequests = observation.requests.slice(beforeControls); passed = true;
  } finally {
    if (!passed && !page.isClosed()) await bounded(page.screenshot({ path: join(output, `${name}-failure.png`), fullPage: true }), limits.cleanup, "unmasked public failure PNG").catch((e) => observation.errors.push(String(e))); if (!page.isClosed()) await bounded(page.close(), limits.cleanup, "public page close"); closed = true; await drain(); observation.guard.lifecycle = "Guard remains attached until acknowledged page closure disposes its CDP target; aggregate also requires successful context/browser cleanup";
  }
  await finalProof();
}

async function main() {
  // Guard is first: null deployment pin cannot produce even a Node HTTPS GET.
  await prepare(false); assert.equal(expected.deployed_product_head, process.env.LIMINIS_LAB_PRODUCT_HEAD); report.qaHead = git("rev-parse", "HEAD"); report.qaTree = git("rev-parse", "HEAD^{tree}"); assert.equal(report.qaHead, process.env.LIMINIS_EXPECTED_HEAD); assert.equal(report.qaTree, process.env.LIMINIS_EXPECTED_TREE); assert.equal(git("status", "--porcelain", "--untracked-files=no"), ""); for (const path of [expectedPath, "scripts/check_public_lab_browser.mjs"]) assert.deepEqual(await readFile(join(root, path)), execFileSync("git", ["show", `HEAD:${path}`], { cwd: root })); report.status = "RUNNING";
  await check("Actual HTTPS eight assets match frozen product bytes before browser", waitForAssets);
  const require = createRequire(import.meta.url), moduleId = process.env.LIMINIS_PLAYWRIGHT_MODULE; assert.ok(moduleId); const pkg = require(`${moduleId}/package.json`); assert.equal(pkg.name, "playwright"); assert.equal(pkg.version, "1.61.1"); assert.equal(stopped, false); browser = await require(moduleId).chromium.launch({ headless: true, chromiumSandbox: true, args: ["--enable-automation"], timeout: limits.launch }); report.browser = { version: browser.version(), playwright: pkg.version }; report.runtime = { workflowRun: process.env.GITHUB_RUN_ID || null, runAttempt: process.env.GITHUB_RUN_ATTEMPT || null, runnerOS: process.env.RUNNER_OS || null, node: process.version, httpCoverage: "Node verified body bytes and separate Playwright response body observations; browser request events are not a public server counter", stockSoftwareBackend: "Pinned Playwright stock defaults unchanged; no hardware FPS/kernel isolation attestation" };
  await check("Actual official CDP argv retains the stock sandbox process model", async () => { const session = await bounded(browser.newBrowserCDPSession(), limits.cdp, "argv CDP"); try { const { arguments: argv } = await bounded(session.send("Browser.getBrowserCommandLine"), limits.cdp, "actual argv"); report.sandbox.arguments = argv; const forbidden = new Set(["--no-sandbox", "--no-zygote-sandbox", "--disable-setuid-sandbox", "--disable-namespace-sandbox", "--disable-seccomp-filter-sandbox", "--disable-gpu-sandbox", "--allow-sandbox-debugging", "--single-process", "--ignore-gpu-blocklist", "--disable-web-security"]); assert.ok(argv.length && argv.every((s) => typeof s === "string")); assert.deepEqual(argv.map((s) => s.split("=", 1)[0]).filter((s) => forbidden.has(s) || /^--disable-.*sandbox$/.test(s)), []); report.sandbox.status = "PASS"; report.sandbox.launchSettings = { headless: true, chromiumSandbox: true, args: ["--enable-automation"] }; } finally { await bounded(session.detach(), limits.cdp, "argv CDP detach"); } });
  context = await bounded(browser.newContext({ acceptDownloads: false, deviceScaleFactor: 1 }), limits.operation, "public context"); await bounded(context.tracing.start({ screenshots: true, snapshots: true, sources: true }), limits.cdp, "public trace start"); tracing = true;
  for (const [name, viewport] of [["desktop", { width: 1440, height: 900 }], ["mobile390", { width: 390, height: 844 }], ["mobile320", { width: 320, height: 844 }]]) await check(`Actual public LAB partial smoke ${name}`, () => bounded(smoke(name, viewport), limits.viewport, `${name} public actions`)); assert.equal(stopped, false); report.status = "PASS";
}
function sourceSelfChecks() {
  let checks = 0; const rejects = (action, pattern) => { assert.throws(action, pattern); checks++; };
  rejects(() => validateExpected({ ...expected, deployed_product_head: null }, false), /REFUSED/);
  for (const field of ["product_candidate_head", "product_candidate_tree", "deployed_product_head"]) rejects(() => validateExpected({ ...expected, [field]: [expected.product_candidate_head] }, true));
  const arrayDigest = structuredClone(expected); arrayDigest.assets.at(-1).sha256 = [arrayDigest.assets.at(-1).sha256]; rejects(() => validateExpected(arrayDigest, true));
  rejects(() => validateExpected({ ...expected, unknown: true }, true));
  assert.ok(redirectAllowed("https://liminis.dev/lab.html", "https://liminis.dev/lab")); checks++;
  for (const target of ["https://example.test/lab", "http://liminis.dev/lab", "https://user@liminis.dev/lab", "https://liminis.dev/lab?x=1", "https://liminis.dev/lab.js", "https://liminis.dev/lab.html"]) { assert.equal(redirectAllowed("https://liminis.dev/lab.html", target), false); checks++; }
  assert.equal(redirectAllowed("https://liminis.dev/lab", "https://liminis.dev/lab"), false); checks++;
  const asset = expected.assets.find((a) => a.filename === "data/lab-2/descriptor.json"), original = local.get(asset.filename); assert.equal(verifyBytes(asset, original).rawMatchesSource, true); checks++;
  // Synthetic source-admission control only; never supplied to a product/browser.
  const changed = Buffer.from(original); assert.equal(changed.at(-1), 10); changed[changed.length - 1] = 32; assert.deepEqual(JSON.parse(changed), JSON.parse(original)); rejects(() => verifyBytes(asset, changed));
  const html = expected.assets[0]; rejects(() => verifyBytes(html, Buffer.concat([local.get("lab.html"), Buffer.alloc(367)]))); return checks;
}
if (process.argv.includes("--source-preflight-only")) { await prepare(true); const checks = sourceSelfChecks(); console.log(JSON.stringify({ status: "PASS", scope: "Preparation/source pins/refusal/canonical-redirect/source-admission controls ONLY", productCandidateHead: expected.product_candidate_head, deployedProductHead: expected.deployed_product_head, assetCount: expected.assets.length, sourceControls: checks, publicNetwork: "NOT_RUN", browser: "NOT_RUN" })); }
else {
  await rm(output, { recursive: true, force: true }); await mkdir(output, { recursive: true }); try { running = main(); await bounded(running, limits.whole, "whole bounded public LAB smoke"); } catch (e) { fail(e); if (running) await bounded(running.catch(() => {}), limits.operation + limits.launch, "interrupted settlement").catch((e) => fail(e, "settlement")); }
  finally {
    const cleanup = async (name, action, timeout = limits.cleanup) => { try { await bounded(action(), timeout, name); } catch (e) { report.cleanupErrors.push({ name, error: e.stack || String(e) }); fail(e, name); } }; if (tracing) await cleanup("trace publication", async () => { await context.tracing.stop({ path: join(output, "trace.zip") }); const bytes = await readFile(join(output, "trace.zip")); assert.ok(bytes.length); report.trace = { status: "PASS", bytes: bytes.length, sha256: sha(bytes) }; }, limits.trace); if (context) await cleanup("context close", () => context.close()); if (browser) await cleanup("browser close", () => browser.close()); for (const final of finalizers) await cleanup("final public evidence proof", final, limits.operation); await sleep(50);
    if (report.status === "PASS") try { assert.equal(stopped, false); assert.equal(git("rev-parse", "HEAD"), report.qaHead); assert.equal(git("rev-parse", "HEAD^{tree}"), report.qaTree); assert.equal(git("status", "--porcelain", "--untracked-files=no"), ""); assert.deepEqual(report.nodeUnhandled, []); assert.deepEqual(report.cleanupErrors, []); assert.deepEqual(report.prohibitedRequests, []); assert.equal(report.checks.length, 5); assert.ok(report.checks.every((c) => c.status === "PASS")); assert.equal(report.publicAssets.length, 8); assert.equal(report.pages.length, 3); assert.ok(report.pages.every((p) => p.status === "PASS" && p.guard.status === "PASS")); assert.equal(report.screenshots.length, 3); assert.equal(report.trace.status, "PASS"); assert.equal(report.sandbox.status, "PASS"); } catch (e) { fail(e, "post-cleanup aggregate"); }
    report.finishedAt = new Date().toISOString(); await writeFile(join(output, "report.json"), JSON.stringify(report, null, 2) + "\n"); console.log(JSON.stringify({ status: report.status, qaHead: report.qaHead, deployedProductHead: report.deployedProductHead, output })); if (report.status !== "PASS") process.exitCode = 1;
  }
}
