// ONE A/B compatibility probe; originals remain FAIL and no production fix is made.
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { once } from "node:events";
import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { createServer } from "node:http";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";


const root = resolve(dirname(fileURLToPath(import.meta.url)), ".."), outputBase = join(root, "target/qa/lab-transport-ab");
const scriptPath = "scripts/check_lab_transport_ab.mjs", manifestPath = "scripts/lab-transport-ab-assets.json", variantPath = "scripts/fixtures/lab-transport-ab/lab-data-pipe-to.mjs";
const candidate = "1be0d0940ef75aa00d6152e5b718df0cc5fb446f", candidateTree = "64bdb5f4794f48907f99886c540f6391571b1914";
const filenames = ["lab.html", "lab.js", "lab.css", "lab-data.mjs", "data/lab-2/descriptor.json", "data/lab-2/results.json", "data/lab-2/comparisons.json", "data/lab-2/manifest.json"];
const initialSearch = "?condition=baseline&seed=1&sample=0", limits = { run: 150_000, operation: 15_000, cdp: 5000, launch: 20_000, cleanup: 5000, requests: 32, events: 4096, activeCallbacks: 32 };
const sha = (b) => createHash("sha256").update(b).digest("hex"), git = (...args) => execFileSync("git", args, { cwd: root, encoding: "utf8" }).trim(), sleep = (ms) => new Promise((done) => setTimeout(done, ms));
function keys(value, names) { assert.ok(value && typeof value === "object" && !Array.isArray(value)); assert.deepEqual(Object.keys(value).sort(), [...names].sort()); }
async function bounded(promise, ms, label) { let timer; try { return await Promise.race([promise, new Promise((_, reject) => { timer = setTimeout(() => reject(new Error(`Timed out: ${label}`)), ms); })]); } finally { clearTimeout(timer); } }
const overall = { status: "AB_PROBE_NOT_RUN", scope: "ONE diagnostic A/B compatibility probe ONLY, not LAB acceptance, scientific validation, a production fix, or exact-head full CI. Any arm failure stays overall FAIL. Both transport passes are inconclusive and stop further causal runs.", startedAt: new Date().toISOString(), limits, sources: [], arms: [], nodeUnhandled: [], errors: [], decision: "NOT_RUN", qualifications: ["A is byte-exact product1be. B differs ONLY in the explicit fixture readBytes function using bounded native pipeTo/WritableStream. Seven other assets and all published raw biological data are byte-identical.", "Two sequential fresh browser contexts/pages use the same official pinned runtime, stock sandbox settings, pre-send Request guards and original-response body pins. This probe uses no Debugger, route fulfillment, second fetch, Promise observer, retained Response/Reader, forced GC or liveness timer.", "Response-stage Fetch.getResponseBody changes delivery timing; every continueResponse passes requestId alone. Network terminal failure remains failure even after full original body admission.", "A fail plus B pass identifies only a candidate UA compatibility path. It does not prove a Chromium cancellation cause, biological effect or production readiness. Existing failures/reports and mandatory nine LAB gates remain unchanged."] };
let sourceManifest, variantBytes, activeArm, probeRunning, probeStopped = false;
const originalAssets = new Map();
process.on("unhandledRejection", (error) => { const text = error?.stack || String(error); overall.nodeUnhandled.push(text); if (activeArm) { activeArm.report.nodeUnhandled.push(text); activeArm.fail(error, "Node unhandled rejection"); } overall.status = "AB_PROBE_FAIL"; process.exitCode = 1; });
async function prepare() {
  sourceManifest = JSON.parse(await readFile(join(root, manifestPath))); keys(sourceManifest, ["schema_version", "scope", "candidate_head", "candidate_tree", "assets", "variant"]); assert.equal(sourceManifest.schema_version, 1); assert.equal(sourceManifest.scope, "one_ab_native_stream_compatibility_probe_only"); assert.equal(sourceManifest.candidate_head, candidate); assert.equal(sourceManifest.candidate_tree, candidateTree); assert.equal(git("rev-parse", `${candidate}^{tree}`), candidateTree); assert.ok(Array.isArray(sourceManifest.assets)); assert.deepEqual(sourceManifest.assets.map((a) => a.filename), filenames); let total = 0;
  for (const asset of sourceManifest.assets) { keys(asset, ["filename", "bytes", "sha256"]); assert.ok(Number.isSafeInteger(asset.bytes) && asset.bytes > 0 && typeof asset.sha256 === "string" && /^[a-f0-9]{64}$/.test(asset.sha256)); total += asset.bytes; assert.ok(total <= 8 * 1024 * 1024); const filename = `site/${asset.filename}`, bytes = await readFile(join(root, filename)); assert.equal(bytes.length, asset.bytes); assert.equal(sha(bytes), asset.sha256); for (const head of [candidate, "HEAD"]) assert.deepEqual(bytes, execFileSync("git", ["show", `${head}:${filename}`], { cwd: root, maxBuffer: 8 * 1024 * 1024 })); originalAssets.set(`/${asset.filename}`, { ...asset, bytesBuffer: bytes, mime: asset.filename.endsWith(".json") ? "application/json" : asset.filename.endsWith(".css") ? "text/css" : asset.filename.endsWith(".html") ? "text/html" : "text/javascript" }); overall.sources.push(asset); }
  const v = sourceManifest.variant; keys(v, ["filename", "serves", "bytes", "sha256", "original_sha256", "original_function_sha256", "variant_function_sha256", "difference"]); assert.equal(v.filename, variantPath); assert.equal(v.serves, "lab-data.mjs"); assert.equal(v.bytes, 20280); assert.equal(v.sha256, "51dac9a199089718fcd5624f7ca7998867e5f924d22badbe76d8473e2b19b38e"); assert.equal(v.original_sha256, "b0341865222c0692a86daf73b8611205aa99d27e54f96968c8a31851a0c2353a"); assert.equal(v.original_function_sha256, "d6484a68a09e8318452e376e7c092f2565fca8ef9f1bdc827c8e2d705812c07a"); assert.equal(v.variant_function_sha256, "3129290bf9cbe4eccfd8b17bdf1628547d8fde5273a12f3a5e13cbe600f59a92"); assert.equal(typeof v.difference, "string"); variantBytes = await readFile(join(root, variantPath)); assert.equal(variantBytes.length, v.bytes); assert.equal(sha(variantBytes), v.sha256);
  const original = originalAssets.get("/lab-data.mjs").bytesBuffer, slice = (b) => { const start = b.indexOf("async function readBytes("), end = b.indexOf("export async function loadLab(", start); assert.ok(start > 0 && end > start); assert.equal(b.indexOf("async function readBytes(", start + 1), -1); return { prefix: b.subarray(0, start), body: b.subarray(start, end), suffix: b.subarray(end) }; }, a = slice(original), b = slice(variantBytes); assert.deepEqual(a.prefix, b.prefix); assert.deepEqual(a.suffix, b.suffix); assert.equal(sha(a.body), v.original_function_sha256); assert.equal(sha(b.body), v.variant_function_sha256);
  overall.candidateHead = candidate; overall.candidateTree = candidateTree; overall.candidateTotalBytes = total; overall.diagnosticHead = git("rev-parse", "HEAD"); overall.diagnosticTree = git("rev-parse", "HEAD^{tree}"); overall.scriptSha256 = sha(await readFile(join(root, scriptPath))); overall.manifestSha256 = sha(await readFile(join(root, manifestPath))); overall.variant = { ...v, prefixAndSuffixByteExact: true, differenceBytes: variantBytes.length - original.length };
}
async function runArm(label) {
  const output = join(outputBase, label), assets = new Map([...originalAssets].map(([path, asset]) => [path, label === "B" && path === "/lab-data.mjs" ? { ...asset, bytes: variantBytes.length, sha256: sourceManifest.variant.sha256, bytesBuffer: variantBytes } : { ...asset }])), manifest = { assets: [...assets.values()].map(({ bytesBuffer, mime, ...pin }) => pin) };
  const report = { label, status: "TRANSPORT_NOT_RUN", scope: label === "A" ? "Exact unchanged original1be arm" : "Explicit diagnostic-only pipeTo module variant; not a production fix", startedAt: new Date().toISOString(), sources: manifest.assets, candidateHead: candidate, candidateTree, diagnosticHead: overall.diagnosticHead, diagnosticTree: overall.diagnosticTree, scriptSha256: overall.scriptSha256, manifestSha256: overall.manifestSha256, variant: label === "B" ? overall.variant : null, serverRequests: [], network: [], fetch: [], requestFailures: [], pageErrors: [], runtimeExceptions: [], consoleErrors: [], nodeUnhandled: [], callbackErrors: [], cleanupErrors: [], guard: { status: "NOT_RUN", blocked: [] }, sandbox: { status: "NOT_RUN" }, screenshot: { status: "NOT_RUN" } };
  overall.arms.push(report); let browser, context, page, session, server, origin, stopped = false, running, actionsPassed = false, pageClosed = false, eventCount = 0, mainSettled = false, lifecyclePhase = "main";
  const networks = new Map(), fetchByNetwork = new Map(), paused = new Map(), actions = new Set();
  function fail(error, stage) { stopped = true; report.status = "TRANSPORT_FAIL"; (report.failures ||= []).push({ stage, error: error?.stack || String(error) }); }
  activeArm = { report, fail };
// Не сохраняем произвольные query/userinfo внешних URL. Allowed URL здесь literal loopback.
function location(url) { try { const u = new URL(url); return { origin: u.origin, path: assets.has(u.pathname) ? u.pathname : "UNAPPROVED_PATH", initialQuery: u.pathname === "/lab.html" && u.search === initialSearch }; } catch { return { invalid: true }; } }
function admitted(url, method) { const u = new URL(url); return method === "GET" && u.origin === origin && !u.username && !u.password && !u.hash && assets.has(u.pathname) && u.search === (u.pathname === "/lab.html" ? initialSearch : ""); }
function timeline(id, event, fields) { assert.ok(typeof id === "string" && id.length <= 128); assert.ok(++eventCount <= limits.events, "Bounded CDP event inventory"); let entry = networks.get(id); if (!entry) { assert.ok(networks.size < limits.requests); entry = { requestId: id, events: [] }; networks.set(id, entry); report.network.push(entry); } entry.events.push({ event, observedMonotonicMs: performance.now(), ...fields }); return entry; }
function ownedEvent(name, handler) { session.on(name, (event) => { try { handler(event); } catch (e) { report.callbackErrors.push({ event: name, error: e.stack || String(e) }); fail(e, name); } }); }
async function startServer() {
  server = createServer((request, response) => { const url = new URL(request.url, "http://127.0.0.1"), asset = assets.get(url.pathname), entry = { id: report.serverRequests.length + 1, method: request.method, path: asset ? url.pathname : "UNAPPROVED_PATH", receivedUnixMs: Date.now() }; report.serverRequests.push(entry); if (report.serverRequests.length > limits.requests) fail(new Error("Server request inventory overflow"), "server"); response.once("finish", () => { entry.finishedUnixMs = Date.now(); }); response.once("close", () => { entry.closedUnixMs = Date.now(); entry.closedAfterFinish = response.writableFinished; }); request.once("aborted", () => { entry.abortedUnixMs = Date.now(); });
    if (request.method !== "GET" || !asset) { entry.status = 404; response.writeHead(404); response.end("Unknown diagnostic route"); return; } entry.status = 200; entry.bytes = asset.bytes; entry.sha256 = asset.sha256; response.writeHead(200, { "content-type": asset.mime, "content-length": asset.bytes, "cache-control": "no-store" }); response.end(asset.bytesBuffer);
  }); server.listen(0, "127.0.0.1"); await bounded(once(server, "listening"), limits.cdp, "loopback listen"); origin = `http://127.0.0.1:${server.address().port}`; report.origin = origin;
}
async function pausedRequest(event) {
  assert.ok(actions.size <= limits.activeCallbacks); assert.ok(typeof event.networkId === "string", "Every paused hop must map to a native Network request ID"); const url = new URL(event.request.url), asset = assets.get(url.pathname), responseStage = event.responseStatusCode !== undefined || event.responseErrorReason !== undefined;
  if (!responseStage) {
    assert.ok(!fetchByNetwork.has(event.networkId), "One Request-stage pause per original network ID; redirects/retries are not admitted");
    const entry = { networkId: event.networkId, requestFetchId: event.requestId, method: event.request.method, location: location(event.request.url), requestPausedMs: performance.now(), status: "REQUEST_PAUSED" }; assert.ok(report.fetch.length < limits.requests); fetchByNetwork.set(event.networkId, entry); report.fetch.push(entry); paused.set(event.requestId, "Request");
    if (!admitted(event.request.url, event.request.method)) { report.guard.blocked.push(entry); fail(new Error("Out-of-scope request refused BEFORE transmission"), "Request-stage guard"); await bounded(session.send("Fetch.failRequest", { requestId: event.requestId, errorReason: "BlockedByClient" }), limits.cdp, "out-of-scope block"); paused.delete(event.requestId); entry.status = "BLOCKED"; return; }
    entry.filename = asset.filename; await bounded(session.send("Fetch.continueRequest", { requestId: event.requestId }), limits.cdp, "unchanged Request-stage continuation"); paused.delete(event.requestId); entry.requestContinuedMs = performance.now(); entry.status = "REQUEST_CONTINUED"; return;
  }
  const entry = fetchByNetwork.get(event.networkId); assert.ok(entry && admitted(event.request.url, event.request.method)); assert.equal(entry.filename, asset.filename); assert.equal(entry.responseFetchId, undefined); entry.responseFetchId = event.requestId; entry.responsePausedMs = performance.now(); entry.httpStatus = event.responseStatusCode; entry.responseErrorReason = event.responseErrorReason || null; paused.set(event.requestId, "Response");
  try {
    assert.equal(event.responseErrorReason, undefined); assert.equal(event.responseStatusCode, 200); assert.ok(Array.isArray(event.responseHeaders) && event.responseHeaders.length <= 32); const headers = event.responseHeaders.filter((h) => ["content-length", "content-type", "content-encoding"].includes(h.name.toLowerCase())); assert.ok(headers.every((h) => typeof h.value === "string" && h.value.length <= 256)); entry.headers = headers;
    const length = headers.filter((h) => h.name.toLowerCase() === "content-length"), encoding = headers.filter((h) => h.name.toLowerCase() === "content-encoding"); assert.equal(length.length, 1); assert.equal(length[0].value, String(asset.bytes)); assert.equal(encoding.length, 0);
    entry.getBodyStartedMs = performance.now(); const body = await bounded(session.send("Fetch.getResponseBody", { requestId: event.requestId }), limits.operation, "original response-stage body"); entry.getBodyCompletedMs = performance.now(); assert.equal(typeof body.body, "string"); assert.equal(typeof body.base64Encoded, "boolean"); const bytes = Buffer.from(body.body, body.base64Encoded ? "base64" : "utf8"); if (body.base64Encoded) assert.equal(bytes.toString("base64"), body.body); entry.body = { bytes: bytes.length, sha256: sha(bytes), base64Encoded: body.base64Encoded }; assert.equal(bytes.length, asset.bytes); assert.equal(entry.body.sha256, asset.sha256); entry.status = "ORIGINAL_BODY_PINNED";
  } catch (e) { entry.status = "BODY_PROOF_FAILED"; entry.error = e.stack || String(e); throw e; }
  finally {
    // Даже при diagnostic FAIL освобождаем только original response, без replacement.
    await bounded(session.send("Fetch.continueResponse", { requestId: event.requestId }), limits.cdp, "original response continuation with no overrides"); paused.delete(event.requestId); entry.responseContinuedMs = performance.now(); entry.continuationArguments = ["requestId"];
  }
}
async function drain() { await bounded((async () => { while (actions.size) await Promise.all([...actions]); })(), limits.operation, "owned CDP callback drain"); }
function installObservers() {
  ownedEvent("Network.requestWillBeSent", (e) => { const entry = timeline(e.requestId, "requestWillBeSent", { timestamp: e.timestamp, wallTime: e.wallTime, method: e.request.method, location: location(e.request.url), type: e.type }); assert.equal(entry.started, undefined); assert.equal(e.redirectResponse, undefined); assert.ok(admitted(e.request.url, e.request.method)); entry.started = true; entry.filename = assets.get(new URL(e.request.url).pathname).filename; });
  ownedEvent("Network.responseReceived", (e) => { const entry = timeline(e.requestId, "responseReceived", { timestamp: e.timestamp, status: e.response.status, mimeType: e.response.mimeType, encodedDataLength: e.response.encodedDataLength, fromDiskCache: e.response.fromDiskCache, fromServiceWorker: e.response.fromServiceWorker }); assert.equal(entry.responseSeen, undefined); entry.responseSeen = true; assert.equal(e.response.status, 200); });
  ownedEvent("Network.dataReceived", (e) => { const entry = timeline(e.requestId, "dataReceived", { timestamp: e.timestamp, dataLength: e.dataLength, encodedDataLength: e.encodedDataLength }); assert.ok(Number.isFinite(e.dataLength) && e.dataLength >= 0 && Number.isFinite(e.encodedDataLength) && e.encodedDataLength >= 0); entry.decodedDataLength = (entry.decodedDataLength || 0) + e.dataLength; entry.encodedDataLength = (entry.encodedDataLength || 0) + e.encodedDataLength; });
  ownedEvent("Network.loadingFinished", (e) => { const entry = timeline(e.requestId, "loadingFinished", { timestamp: e.timestamp, encodedDataLength: e.encodedDataLength }); assert.equal(entry.terminal, undefined); entry.terminal = "loadingFinished"; });
  ownedEvent("Network.loadingFailed", (e) => { const entry = timeline(e.requestId, "loadingFailed", { timestamp: e.timestamp, errorText: e.errorText, canceled: e.canceled === true, blockedReason: e.blockedReason || null, type: e.type, observerPhase: lifecyclePhase }); entry.terminal = "loadingFailed"; fail(new Error(`Native Network loadingFailed: ${e.errorText}`), "Network loadingFailed"); });
  ownedEvent("Runtime.exceptionThrown", (e) => { report.runtimeExceptions.push(e.exceptionDetails); fail(new Error(e.exceptionDetails.text), "Runtime exception"); });
  session.on("Fetch.requestPaused", (event) => { const action = pausedRequest(event).catch((e) => { report.callbackErrors.push({ event: "Fetch.requestPaused", networkId: event.networkId, requestId: event.requestId, error: e.stack || String(e) }); fail(e, "Fetch callback"); }).finally(() => actions.delete(action)); actions.add(action); });
  page.on("requestfailed", (request) => { const entry = { method: request.method(), location: location(request.url()), errorText: request.failure()?.errorText, observedMonotonicMs: performance.now(), observerPhase: lifecyclePhase }; report.requestFailures.push(entry); fail(new Error(entry.errorText), "Playwright requestfailed"); });
  page.on("pageerror", (e) => { report.pageErrors.push(e.stack || String(e)); fail(e, "Page error"); }); page.on("console", (m) => { if (m.type() === "error") { report.consoleErrors.push({ text: m.text(), location: location(m.location().url), observedMonotonicMs: performance.now() }); fail(new Error(m.text()), "Console error"); } });
}
function readyUi() {
  const host = document.getElementById("plots"), workspace = document.getElementById("lab-workspace"), error = document.getElementById("lab-error"), plots = [...(host?.querySelectorAll(".metric-plot") || [])];
  return !!host && workspace?.hidden === false && error?.hidden === true && host.dataset.layout === "ready" && host.getAttribute("aria-busy") === "false" && plots.length === 4 && plots.every((svg) => getComputedStyle(svg).visibility === "visible" && svg.getBoundingClientRect().width > 96);
}
function uiState() {
  const host = document.getElementById("plots"), workspace = document.getElementById("lab-workspace"), error = document.getElementById("lab-error"), stamp = document.getElementById("sample-stamp"), plots = [...(host?.querySelectorAll(".metric-plot") || [])].map((svg) => ({ metric: svg.dataset.metric, visible: getComputedStyle(svg).visibility, width: svg.getBoundingClientRect().width, height: svg.getBoundingClientRect().height }));
  return { ready: !!host && workspace?.hidden === false && error?.hidden === true && host.dataset.layout === "ready" && host.getAttribute("aria-busy") === "false" && plots.length === 4 && plots.every((svg) => svg.visible === "visible" && svg.width > 96), workspaceHidden: workspace?.hidden, errorVisible: error?.hidden !== true, layout: host?.dataset.layout, ariaBusy: host?.getAttribute("aria-busy"), status: document.getElementById("lab-status")?.textContent, matrixRows: document.querySelectorAll("#run-matrix tbody tr").length, plots, runId: stamp?.dataset.runId, tick: stamp?.dataset.tick, unhandled: window.__labTransportUnhandled || [] };
}
function proof() {
  assert.equal(actionsPassed, true); assert.equal(mainSettled, true); assert.equal(pageClosed, true); assert.equal(actions.size, 0); assert.equal(paused.size, 0); assert.equal(stopped, false); for (const name of ["requestFailures", "pageErrors", "runtimeExceptions", "consoleErrors", "nodeUnhandled", "callbackErrors", "cleanupErrors"]) assert.deepEqual(report[name], []); assert.deepEqual(report.guard.blocked, []); assert.equal(networks.size, 8); assert.equal(report.fetch.length, 8); assert.equal(report.serverRequests.length, 8);
  for (const asset of manifest.assets) { const network = report.network.filter((n) => n.filename === asset.filename), fetched = report.fetch.filter((f) => f.filename === asset.filename), served = report.serverRequests.filter((r) => r.path === `/${asset.filename}`); assert.equal(network.length, 1); assert.equal(fetched.length, 1); assert.equal(served.length, 1); assert.equal(network[0].started, true); assert.equal(network[0].responseSeen, true); assert.equal(network[0].terminal, "loadingFinished"); assert.equal(fetched[0].networkId, network[0].requestId); assert.equal(fetched[0].status, "ORIGINAL_BODY_PINNED"); assert.equal(fetched[0].body.bytes, asset.bytes); assert.equal(fetched[0].body.sha256, asset.sha256); assert.ok(fetched[0].responseContinuedMs >= fetched[0].getBodyCompletedMs); assert.deepEqual(fetched[0].continuationArguments, ["requestId"]); assert.equal(served[0].method, "GET"); assert.equal(served[0].status, 200); assert.ok(served[0].finishedUnixMs && served[0].closedAfterFinish); assert.equal(served[0].abortedUnixMs, undefined); }
  assert.equal(report.screenshot.status, "PASS"); for (const state of [report.ui, report.finalPage]) { assert.equal(state.ready, true); assert.equal(state.workspaceHidden, false); assert.equal(state.errorVisible, false); assert.equal(state.layout, "ready"); assert.equal(state.ariaBusy, "false"); assert.equal(state.matrixRows, 24); assert.equal(state.runId, "seed-1-baseline"); assert.equal(state.tick, "0"); assert.deepEqual(state.unhandled, []); } assert.equal(report.sandbox.status, "PASS"); report.guard.status = "PASS";
}
async function main() {
  await startServer();
  const require = createRequire(import.meta.url), moduleId = process.env.LIMINIS_PLAYWRIGHT_MODULE; assert.ok(moduleId); const pkg = require(`${moduleId}/package.json`); assert.equal(pkg.name, "playwright"); assert.equal(pkg.version, "1.61.1"); browser = await require(moduleId).chromium.launch({ headless: true, chromiumSandbox: true, args: ["--enable-automation"], timeout: limits.launch }); report.browser = { playwright: pkg.version, version: browser.version(), node: process.version, runner: process.env.ImageOS || null, workflowRun: process.env.GITHUB_RUN_ID || null };
  const argvSession = await bounded(browser.newBrowserCDPSession(), limits.cdp, "argv CDP"); try { const { arguments: argv } = await bounded(argvSession.send("Browser.getBrowserCommandLine"), limits.cdp, "actual argv"); const forbidden = new Set(["--no-sandbox", "--no-zygote-sandbox", "--disable-setuid-sandbox", "--disable-namespace-sandbox", "--disable-seccomp-filter-sandbox", "--disable-gpu-sandbox", "--allow-sandbox-debugging", "--single-process", "--ignore-gpu-blocklist", "--disable-web-security"]); report.sandbox.arguments = argv; assert.ok(argv.length && argv.every((a) => typeof a === "string")); assert.deepEqual(argv.map((a) => a.split("=", 1)[0]).filter((a) => forbidden.has(a) || /^--disable-.*sandbox$/.test(a)), []); report.sandbox.status = "PASS"; report.sandbox.launchSettings = { headless: true, chromiumSandbox: true, args: ["--enable-automation"] }; } finally { await bounded(argvSession.detach(), limits.cdp, "argv detach"); }
  context = await bounded(browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1, acceptDownloads: false }), limits.operation, "one context"); page = await bounded(context.newPage(), limits.operation, "one page"); page.setDefaultTimeout(limits.operation); page.setDefaultNavigationTimeout(limits.operation); session = await bounded(context.newCDPSession(page), limits.cdp, "sole page Fetch owner"); installObservers();
  await page.addInitScript(() => { window.__labTransportUnhandled = []; addEventListener("unhandledrejection", (e) => window.__labTransportUnhandled.push(String(e.reason?.stack || e.reason))); }); for (const [method, args] of [["Network.enable", {}], ["Network.setCacheDisabled", { cacheDisabled: true }], ["Runtime.enable", {}], ["Fetch.enable", { patterns: [{ urlPattern: "*", requestStage: "Request" }, { urlPattern: "*", requestStage: "Response" }] }]]) await bounded(session.send(method, args), limits.cdp, method); assert.equal(stopped, false); report.guard.status = "RUNNING"; report.status = "TRANSPORT_RUNNING";
  await page.goto(origin + "/lab.html" + initialSearch, { waitUntil: "domcontentloaded" }); await page.waitForFunction(readyUi);
  report.ui = await page.evaluate(uiState); assert.equal(report.ui.ready, true); assert.equal(report.ui.matrixRows, 24); assert.equal(report.ui.runId, "seed-1-baseline"); assert.equal(report.ui.tick, "0");
  await bounded((async () => { while (networks.size !== 8 || [...networks.values()].some((n) => !n.terminal)) { assert.equal(stopped, false); await sleep(20); } })(), limits.operation, "native request terminal settlement after UI ready"); await drain(); assert.equal(stopped, false); actionsPassed = true;
}
  await mkdir(output, { recursive: true }); try { running = (async () => { try { return await main(); } finally { mainSettled = true; } })(); await bounded(running, limits.run, "one diagnostic run"); } catch (e) { fail(e, "main"); if (running) await bounded(running.catch((e) => fail(e, "main settlement")), limits.operation + limits.launch, "interrupted main settlement").catch((e) => fail(e, "settlement deadline")); }
  finally {
    lifecyclePhase = "cleanup";
    const cleanup = async (name, action, ms = limits.cleanup) => { try { await bounded(action(), ms, name); } catch (e) { report.cleanupErrors.push({ name, error: e.stack || String(e) }); fail(e, name); } };
    if (page && !page.isClosed()) { await cleanup("actual PNG even on diagnostic failure", async () => { const bytes = await page.screenshot({ path: join(output, "page.png"), fullPage: true, timeout: limits.cleanup }); report.screenshot = { status: "PASS", bytes: bytes.length, sha256: sha(bytes) }; }, limits.cleanup); if (actionsPassed) await cleanup("actual post-PNG ready plots", () => page.waitForFunction(readyUi, undefined, { timeout: limits.cleanup })); await cleanup("final live-page state and unhandled observation", async () => { report.finalPage = await page.evaluate(uiState); assert.deepEqual(report.finalPage.unhandled, []); if (actionsPassed) { assert.equal(report.finalPage.ready, true); assert.equal(report.finalPage.errorVisible, false); } }); await cleanup("preclose owned callbacks", drain, limits.operation); await cleanup("acknowledged page closure with guard retained", async () => { await page.close(); pageClosed = true; }); }
    if (context) await cleanup("context close", () => context.close()); if (browser) await cleanup("browser close", () => browser.close()); await cleanup("postclose owned callbacks", drain, limits.operation); if (server) await cleanup("server close", () => new Promise((done, reject) => { server.close((e) => e ? reject(e) : done()); server.closeAllConnections(); })); await sleep(50);
    try { proof(); assert.equal(git("rev-parse", "HEAD"), report.diagnosticHead); assert.equal(git("rev-parse", "HEAD^{tree}"), report.diagnosticTree); assert.equal(git("status", "--porcelain", "--untracked-files=no"), ""); report.status = "TRANSPORT_PASS"; } catch (e) { fail(e, "post-cleanup aggregate"); } report.finalization = { pageClosed, mainSettled, pendingCallbacks: actions.size, pausedRequests: paused.size, contextAndBrowserCleanupErrors: report.cleanupErrors.length, networkRequests: networks.size, timelineEvents: eventCount, actionsPassed }; report.finishedAt = new Date().toISOString();
  }
  activeArm = undefined; return { report, revalidate: () => { try { proof(); report.status = "TRANSPORT_PASS"; } catch (e) { fail(e, "final probe aggregate"); } } };
}
// Только advisory metadata: эта функция не меняет failed arm или overall FAIL.
function comparableCancellation(report) {
  const failed = report.network.filter((n) => n.terminal === "loadingFailed"); if (!failed.length || report.requestFailures.length !== failed.length || report.sandbox.status !== "PASS" || report.guard.blocked.length || !report.ui?.ready || !report.finalPage?.ready || report.finalPage.errorVisible || report.screenshot.status !== "PASS" || report.finalization?.pendingCallbacks || report.finalization?.pausedRequests || !report.finalization?.pageClosed) return false;
  for (const state of [report.ui, report.finalPage]) if (!state.ready || state.workspaceHidden !== false || state.errorVisible !== false || state.layout !== "ready" || state.ariaBusy !== "false" || state.matrixRows !== 24 || state.runId !== "seed-1-baseline" || state.tick !== "0" || !Array.isArray(state.unhandled) || state.unhandled.length) return false;
  if (["pageErrors", "runtimeExceptions", "consoleErrors", "nodeUnhandled", "callbackErrors", "cleanupErrors"].some((k) => report[k].length)) return false;
  if (report.network.length !== 8 || report.fetch.length !== 8 || report.serverRequests.length !== 8) return false;
  for (const pin of report.sources) { const n = report.network.filter((x) => x.filename === pin.filename), f = report.fetch.filter((x) => x.filename === pin.filename), s = report.serverRequests.filter((x) => x.path === "/" + pin.filename); if (n.length !== 1 || f.length !== 1 || s.length !== 1 || !n[0].started || !n[0].responseSeen || !["loadingFinished", "loadingFailed"].includes(n[0].terminal) || f[0].networkId !== n[0].requestId || f[0].httpStatus !== 200 || f[0].responseErrorReason !== null || f[0].status !== "ORIGINAL_BODY_PINNED" || f[0].body?.bytes !== pin.bytes || f[0].body?.sha256 !== pin.sha256 || !(f[0].responseContinuedMs >= f[0].getBodyCompletedMs) || JSON.stringify(f[0].continuationArguments) !== '["requestId"]' || s[0].method !== "GET" || s[0].status !== 200 || s[0].bytes !== pin.bytes || s[0].sha256 !== pin.sha256 || !s[0].finishedUnixMs || !s[0].closedAfterFinish || s[0].abortedUnixMs) return false; }
  return failed.every((n) => { const pin = report.sources.find((p) => p.filename === n.filename), raw = n.events.filter((e) => e.event === "loadingFailed"), pw = report.requestFailures.filter((e) => e.location.path === "/" + n.filename); return n.filename.startsWith("data/lab-2/") && n.filename.endsWith(".json") && n.decodedDataLength === pin.bytes && raw.length === 1 && raw[0].canceled === true && raw[0].blockedReason === null && raw[0].errorText === "net::ERR_ABORTED" && raw[0].observerPhase === "main" && pw.length === 1 && pw[0].method === "GET" && pw[0].errorText === "net::ERR_ABORTED" && pw[0].observerPhase === "main"; });
}
async function probe() {
  await prepare(); assert.equal(overall.diagnosticHead, process.env.LIMINIS_EXPECTED_HEAD); assert.equal(overall.diagnosticTree, process.env.LIMINIS_EXPECTED_TREE); assert.equal(git("status", "--porcelain", "--untracked-files=no"), ""); for (const path of [scriptPath, manifestPath, variantPath]) assert.deepEqual(await readFile(join(root, path)), execFileSync("git", ["show", `HEAD:${path}`], { cwd: root }));
  const a = await runArm("A"); if (probeStopped || overall.nodeUnhandled.length || a.report.sandbox.status !== "PASS" || a.report.guard.blocked.length || !a.report.finalization?.pageClosed || !a.report.finalization?.mainSettled || a.report.finalization.pendingCallbacks !== 0 || a.report.finalization.pausedRequests !== 0 || a.report.cleanupErrors.length) { overall.decision = "STOP_A_SECURITY_OR_SEQUENTIAL_CLEANUP_FAILED_B_NOT_RUN"; overall.status = "AB_PROBE_FAIL"; return [a]; }
  const b = await runArm("B"); return [a, b];
}
if (process.argv.includes("--source-preflight-only")) { await prepare(); console.log(JSON.stringify({ status: "SOURCE_PREFLIGHT_PASS", scope: overall.scope, candidateHead: candidate, candidateTree, diagnosticHead: overall.diagnosticHead, diagnosticTree: overall.diagnosticTree, scriptSha256: overall.scriptSha256, manifestSha256: overall.manifestSha256, assets: overall.sources, totalBytes: overall.candidateTotalBytes, variant: overall.variant, network: "NOT_RUN", browser: "NOT_RUN" })); }
else {
  await rm(outputBase, { recursive: true, force: true }); await mkdir(outputBase, { recursive: true }); let arms = []; try { probeRunning = probe(); arms = await bounded(probeRunning, 2 * (limits.run + limits.operation + limits.launch + 8 * limits.cleanup), "ONE two-arm probe deadline"); } catch (error) { probeStopped = true; if (activeArm) activeArm.fail(error, "whole probe deadline"); overall.errors.push(error.stack || String(error)); overall.status = "AB_PROBE_FAIL"; overall.decision = "INCONCLUSIVE_STOP_PROBE_ERROR"; if (probeRunning) await bounded(probeRunning.catch((e) => overall.errors.push(e.stack || String(e))), limits.operation + limits.launch, "probe settlement").catch((e) => overall.errors.push(e.stack || String(e))); }
  await sleep(50); for (const arm of arms) arm.revalidate();
  if (overall.errors.length || overall.nodeUnhandled.length || overall.arms.length !== 2) overall.status = "AB_PROBE_FAIL";
  else { const [a, b] = overall.arms; if (a.status !== "TRANSPORT_PASS" || b.status !== "TRANSPORT_PASS") { overall.status = "AB_PROBE_FAIL"; overall.decision = a.status === "TRANSPORT_FAIL" && comparableCancellation(a) && b.status === "TRANSPORT_PASS" ? "CANDIDATE_UA_COMPATIBILITY_ONLY_REQUIRES_INDEPENDENT_REVIEW_AND_FULL_LAB_CI" : "INCONCLUSIVE_STOP_NO_FURTHER_CAUSAL_RUNS"; } else { overall.status = "AB_PROBE_INCONCLUSIVE_STOP"; overall.decision = "BOTH_PASS_INCONCLUSIVE_NO_PRODUCTION_FIX_OR_FURTHER_CAUSAL_RUNS"; } }
  try { assert.equal(git("rev-parse", "HEAD"), overall.diagnosticHead); assert.equal(git("rev-parse", "HEAD^{tree}"), overall.diagnosticTree); assert.equal(git("status", "--porcelain", "--untracked-files=no"), ""); } catch (e) { overall.errors.push(e.stack || String(e)); overall.status = "AB_PROBE_FAIL"; overall.decision = "INCONCLUSIVE_STOP_SOURCE_IDENTITY_FAILED"; }
  overall.finishedAt = new Date().toISOString(); for (const arm of overall.arms) { await mkdir(join(outputBase, arm.label), { recursive: true }); await writeFile(join(outputBase, arm.label, "report.json"), JSON.stringify(arm, null, 2) + "\n"); } await writeFile(join(outputBase, "report.json"), JSON.stringify(overall, null, 2) + "\n"); console.log(JSON.stringify({ status: overall.status, decision: overall.decision, candidateHead: candidate, diagnosticHead: overall.diagnosticHead, output: outputBase })); if (overall.status === "AB_PROBE_FAIL") process.exitCode = 1;
}
